### ISSUE TITLE
Memory leak while doing Batch insert.

### ISSUE THREAD

**Issue by maximecaron** [aspnet/EntityFramework6#304] opened 2017-06-22 17:44 UTC
I am using Entity Framework Code-First and doing insert of batch of Object creating a new context for each batch.
Very quickly the process memory usage go over 25GB and become unstable.

Looking and the object heap from a dump file show the result below: 

![image](https://user-images.githubusercontent.com/1174484/27447919-a6a560ea-5737-11e7-8bba-1bedeeed51e6.png)

```
        public void WriteBatch(ConcurrentBag<SubscriberScanResult> batch)
        {
            using (var ctx = new WatchDogDbContext(_connectionString))
            {
                try
                {
                    ctx.Configuration.AutoDetectChangesEnabled = false;
                    ctx.Configuration.ValidateOnSaveEnabled = false;
                    ctx.Configuration.ProxyCreationEnabled = false;
                    ctx.SubscriberScanResults.AddRange(batch);
                    ctx.SaveChanges();
                }
                catch (Exception ex)
                {
                    logger.Error("Exception in WriteBatch(ConcurrentBag<SubscriberScanResult> batch) for DatabaseWriter");
                    logger.Exception(ex);
                    Environment.Exit(0);
                }
            }
        }
```

**Comment by ajcvickers** [comment] 2017-06-23 18:37
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment] 2017-06-30 16:14
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2017-06-30 16:14 UTC
Labels: closed-could-not-reproduce
