### ISSUE TITLE
Does EF6 support SQL Synonyms?

### ISSUE THREAD

**Issue by jwstemper** [aspnet/EntityFramework6#228] opened 2017-03-22 19:14 UTC
I have a requirement to use several tables that are synonyms from a second db. Is this possible with EF6 or when will it be added?

**Comment by ajcvickers** [comment] 2017-03-27 19:59
@jwstemper Can you be more specific about what support you are looking for? Reverse engineering a model from a database does not support synonyms, but manually added mappings for table synonyms should work.

**Comment by ajcvickers** [comment] 2017-04-04 18:29
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2017-04-04 18:29 UTC
