### ISSUE TITLE
Query with Include() and Single() returns null when first column in generated SQL is null

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework6#336] opened 2017-08-10 22:21 UTC
I have received this other code for a repro:

``` C#
public async Task<Model.Issue> Get(long userId, long issueId) 
{
  using (var context = new Context()) {
  var result = await
    context.Issues
      .Include(i => i.Step)
      .SingleAsync(i => i.UserId == userId && w.IssueId== issueId);

    return result; // this is null
  }
}


public class Step 
{
  public DateTime Created { get; set; }
  [Required]
  [StringLength(100)]
  public string Description { get; set; }
  [Required]
  [StringLength(20)]
  public string Name { get; set; }
  public int StepId { get; set; }
}

public class Issue 
{
  public DateTime Created { get; set; }
  public DateTime? Ended { get; set; }
  public Step Step { get; set; }
  public int StepID { get; set; }
  public long IssueId { get; set; }
}

```
Customer dug a bit into this and believes that there may be an assumption in some of our logic that the column in the SQL projection is the primary key but this is not always the case.

He also believes it is similar to something described in https://stackoverflow.com/questions/10212913/entity-framework-returns-null-for-a-row-if-the-first-column-in-that-row-is-null/11039030#11039030.

**Comment by ajcvickers** [comment] 2019-03-18 22:38
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment] 2019-06-26 18:37
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-06-26 18:37 UTC
Labels: blocked
