### ISSUE TITLE
 ef tool in the new .csproj format

### ISSUE THREAD

**Issue by Varorbc** [aspnet/EntityFramework6#645] opened 2018-10-09 14:02 UTC
in the new csproj format, an exception appears from the database generation code by ef tool

```
Exception message:System.Exception
```

### Further technical details
EF version: 6.2
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8

**Comment by ajcvickers** [comment] 2018-10-10 16:46
Duplicate of #231

**Closed by ajcvickers** 2018-10-10 16:46 UTC
