### ISSUE TITLE
About Dynamic Table Names

### ISSUE THREAD

**Issue by MuhammedEminTiftikci** [aspnet/EntityFramework6#497] opened 2018-03-16 16:39 UTC
Hello everyone,

I just created a infrastructure of database like this:

- MainTableA
- MainTableB
- MainTableC
- SubTableYear2018A
- SubTableYear2018B
- SubTableYear2018C
- SubTableYear2019A
- SubTableYear2019B
- SubTableYear2019C

so, as you see _year_ is dynamic area that i want to auto-create and access by ef.
Because i want to split my data for years.
I must CURD them.

Is that possible or in your plans?

I have tried that use inheritance TableNameAttribute and change table name in base constructor parameter, but throws database changed exception.

**Comment by ajcvickers** [comment] 2018-07-27 15:58
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2018-07-27 15:58 UTC
