### ISSUE TITLE
Child collections empty upon save changes

### ISSUE THREAD

**Issue by davemanton** [aspnet/EntityFramework6#1445] opened 2019-11-05 14:00 UTC
I am inserting a new Product into my database.

The product has an ICollection of ProductVersions within and that collection has another collection of ProductDescriptions within that.

I populate properties in the Product, the version collection and the description collection within that one.

When I save, the data get's saved to the database correctly.

However, the reference to the descriptions collection is now an empty collection in the versions collection, meaning I cannot map that object back in a response to an API call.

There are no exceptions and everything is saved correctly. It's just the collection of descriptions is now empty where it had data before

### Classes
```c#
public class Product
    {
        private ProductVersion _workingVersion;

        private Product()
        {
            ProductVersions = new HashSet<ProductVersion>();

            _workingVersion = new ProductVersion(1, "SYSTEM");
            ProductVersions.Add(_workingVersion);
        }

        public Product(CultureInfo cultureInfo, string name) : this()
        {
            _workingVersion.PutDescription(cultureInfo, name, string.Empty, string.Empty)
        } 

        public int ProductId { get; private set; }

        public ICollection<ProductVersion> ProductVersions { get; private set; }
    }

```

```c#
public class ProductVersion
    {
        private ProductVersion()
        {
            ProductDescriptions = new HashSet<ProductDescription>();
         
            Created = DateTime.UtcNow;
            LastModified = DateTime.UtcNow;
        }

        internal ProductVersion(
            int version,
            string username)
            : this()
        {
            Version = version;
            CreatedBy = username;
            ModifiedBy = username;
        }
        public int ProductId { get; private set; }
        public int Version { get; private set; }
        public DateTime Created { get; private set; }
        public string CreatedBy { get; private set; }
        public DateTime LastModified { get; private set; }
        public string ModifiedBy { get; private set; }
        public DateTime? Replaced { get; private set; }
     
        public ICollection<ProductDescription> ProductDescriptions { get; private set; }
    
        public Product Product { get; private set; }

        public void PutProductDescription(CultureInfo cultureInfo, string name, string shortDescription, string description)
        {
            var productDescription = ProductDescriptions.FirstOrDefault(x => x.LanguageCode == cultureInfo.TwoLetterISOLanguageName);

            if (productDescription == null)
            {
                CreateProductDescription(cultureInfo, name, shortDescription, description);
                return;
            }

            productDescription.Update(Version, name, shortDescription, description, "SYSTEM");
        }

        private void CreateProductDescription(CultureInfo cultureInfo, string name, string shortDescription,
            string description)
        {
            var productDescription = new ProductDescription(Version, cultureInfo, name, shortDescription, description, "SYSTEM");
            ProductDescriptions.Add(productDescription);
        }
        
    }

```

```c#
 public class ProductDescription
    {
        internal ProductDescription(
            int modifiedInVersion,
            CultureInfo cultureInfo,
            string name,
            string shortDescription,
            string description,
            string username)
        {
            LanguageCode = cultureInfo.TwoLetterISOLanguageName;
            Name = name;
            ShortDescription = shortDescription;
            Description = description;
            ModifiedBy = username;
            LastModifiedInVersion = modifiedInVersion;
        }

        public int ProductId { get; private set; }
        public int Version { get; private set; }
        public string LanguageCode { get; private set; }
        public string Name { get; private set; }
        public string ShortDescription { get; private set; }
        public string Description { get; private set; }
        public int LastModifiedInVersion { get; private set; }
        public string ModifiedBy { get; private set; }

        public ProductVersion ProductVersion { get; private set; }

        public void Update(int productVersion, string name, string shortDescription, string description, string username)
        {
            LastModifiedInVersion = productVersion;
            Name = name;
            ShortDescription = shortDescription;
            Description = description;
            ModifiedBy = username;
        }      
    }
```

### Further technical details
EF version: 6.3
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10 
IDE: Visual Studio 2019 16.3.6

**Comment by davemanton** [comment] 2019-11-05 14:57
We've done some further investigation with other tables in our database.

The ProductVersion has a composite primary key of ProductId and Version

The ProductDescription primary key is made of ProductId, ProductVersion and LanguageCode
The ProductDescription has the ProductId and ProductVersion as the composite foreign key back to the ProductVersion

Any table in our database which has a single foreign key seems to work in nested collections and will continue to appear after the item has been saved.

However we have a number of tables with composite foreign keys where the primary key is not the same as the foreign key, these all end up with empty collections after save changes is called

**Comment by ajcvickers** [comment] 2019-11-05 18:06
@davemanton I don't see anything obvious here. If you post a small, runnable project/solution that demonstrates the behavior you are seeing then I will take a deeper look.

**Comment by ajcvickers** [comment] 2019-11-22 18:52
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-11-22 18:52 UTC

**Comment by mamartel** [comment] 2025-05-15 00:25
I'm using EF6 with an SQL Server Compact database and I seem to have encountered the same bug.

Steps to reproduce the problem:

1. Create a .NET Framework test project
2. Add NuGet package `EntityFramework` version 6.5.1
3. Add NuGet package `EntityFramework.SqlServerCompact` version 6.5.1
4. Add the following class

```c#
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;

namespace EF6_1445
{
    [TestClass]
    public class EF6_1445
    {
        public class MyContext : DbContext
        {
            public MyContext()
                : base("Data Source=|DataDirectory|\\Database.sdf")
            {
                Database.SetInitializer(new DropCreateDatabaseAlways<MyContext>());
            }

            public virtual DbSet<ProductCategory> ProductCategories { get; set; }
            public virtual DbSet<Product> Products { get; set; }
            public virtual DbSet<ProductData> ProductDatas { get; set; }
        }

        public class ProductCategory
        {
            [Key]
            [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
            public int Id { get; set; }

            public virtual List<Product> Products { get; set; }

            public int MyProperty { get; set; } // https://stackoverflow.com/a/28538725

            public ProductCategory()
            {
                Products = new List<Product>();
            }
        }

        public class Product
        {
            [Key]
            [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
            [Column(Order = 0)]
            public int Id { get; set; }

            [Key]
            [ForeignKey(nameof(Category))]
            [Column(Order = 1)]
            public int CategoryId { get; set; }

            [Required]
            public virtual ProductCategory Category { get; set; }

            public virtual List<ProductData> ProductDatas { get; set; }

            public int MyProperty { get; set; } // https://stackoverflow.com/a/28538725

            public Product()
            {
                ProductDatas = new List<ProductData>();
            }
        }

        public class ProductData
        {
            [Key]
            [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
            [Column(Order = 2)]
            public int Id { get; set; }

            [Key]
            [ForeignKey(nameof(Product))]
            [Column(Order = 0)]
            public int ProductId { get; set; }

            [Key]
            [ForeignKey(nameof(Product))]
            [Column(Order = 1)]
            public int CategoryId { get; set; }

            [Required]
            public virtual Product Product { get; set; }

            public int MyProperty { get; set; } // https://stackoverflow.com/a/28538725
        }

        [TestMethod]
        public void Works()
        {
            using (var db = new MyContext())
            {
                var category = new ProductCategory();
                db.ProductCategories.Add(category);

                var product = new Product();
                category.Products.Add(product);

                var productData = new ProductData();
                product.ProductDatas.Add(productData);

                db.SaveChanges();

                Assert.AreEqual(product.ProductDatas.Count, 1); // Ok. No problem when everything is created in one go.
            }
        }

        [TestMethod]
        public void Bug()
        {
            using (var db = new MyContext())
            {
                var category = new ProductCategory();
                db.ProductCategories.Add(category);
                db.SaveChanges();
            }

            using (var db = new MyContext())
            {
                var category = db.ProductCategories.First();

                var product = new Product();
                category.Products.Add(product);

                var productData = new ProductData();
                product.ProductDatas.Add(productData);

                db.SaveChanges();

                Assert.AreEqual(product.ProductDatas.Count, 1); // Fails. The collection is empty.
            }
        }

        [TestMethod]
        public void MoreDetails()
        {
            using (var db = new MyContext())
            {
                var category = new ProductCategory();
                db.ProductCategories.Add(category);
                db.SaveChanges();
            }

            using (var db = new MyContext())
            {
                var category = db.ProductCategories.First();

                var product = new Product();
                category.Products.Add(product);

                var productData = new ProductData();
                product.ProductDatas.Add(productData);

                db.SaveChanges();

                Assert.AreEqual(product.Id, productData.ProductId); // Ok
                Assert.AreEqual(product.CategoryId, productData.CategoryId); // Fails. This property is not updated.
            }
        }

        public class WorkaroundProductData : ProductData
        {
            public override Product Product
            {
                get => base.Product;
                set
                {
                    CategoryId = value.CategoryId; // Fixes the problem.
                    base.Product = value;
                }
            }
        }

        [TestMethod]
        public void Workaround()
        {
            using (var db = new MyContext())
            {
                var category = new ProductCategory();
                db.ProductCategories.Add(category);
                db.SaveChanges();
            }

            using (var db = new MyContext())
            {
                var category = db.ProductCategories.First();

                var product = new Product();
                category.Products.Add(product);

                var productData = new WorkaroundProductData();
                product.ProductDatas.Add(productData);

                db.SaveChanges();

                Assert.AreEqual(product.ProductDatas.Count, 1); // Works now.
            }
        }
    }
}
```
