### ISSUE TITLE
Wrong migration on multiple unique keys on multiple columns

### ISSUE THREAD

**Issue by andreapier** [aspnet/EntityFramework6#1433] opened 2019-10-31 09:25 UTC
Hi,  
I think I hit a bug.  
  
My entity has 2 unique key contraints. Each unique key is composed by 2 columns. 1 of those columns is in common. The other one is of course different.  
I am using Code First and fluent configuration.  
  
When I generate the migration I get a correct unique index and an incorrect one.  
If I flip the index definition in my fluent configuration, the correct and the wrong indexes also flip.  
  
Can you confirm this is a bug?  I can't really see why anyone would want this behaviour...
Please let me know if you need more information.  
  
Thanks  
  
### Steps to reproduce
```c#
public class MyMapping : EntityConfigurationType<MyEntity>
{
    ...
    HasIndex(e => new { e.DocumentId, e.RowNumber }).IsUnique();
    HasIndex(e => new { e.DocumentId, e.RowSort }).IsUnique();
}
```
In Package Manager Console type: `Add-Migration Example`  
Check generated migration:
```c#
public partial class Example : DbMigration
{
    ...
    .Index(t => new { t.DocumentId, t.RowSort }, unique: true)                                // Correct
    .Index(t => t.RowNumber, unique: true, name: "IX_DocumentId_RowNumber") // Wrong
}
```
As you can see 1st defined index lacks column `DocumentId`.  
2nd fedined one is correct.  

If I flip the order of definition of indexes in my mapping I get the opposite result (but still wrong):
```c#
public class MyMapping : EntityConfigurationType<MyEntity>
{
    ...
    HasIndex(e => new { e.DocumentId, e.RowSort }).IsUnique();
    HasIndex(e => new { e.DocumentId, e.RowNumber }).IsUnique();
}

public partial class Example : DbMigration
{
    ...
    .Index(t => new { t.DocumentId, t.RowNumber }, unique: true)             // Correct
    .Index(t => t.RowSort, unique: true, name: "IX_DocumentId_RowSort") // Wrong
}
```

### Further technical details
EF version: 6.2.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10 
IDE: Visual Studio 2019 16.3.7

**Comment by ajcvickers** [comment] 2019-11-01 15:46
Duplicate of #460

**Closed by ajcvickers** 2019-11-01 15:46 UTC
