### ISSUE TITLE
stored procedure mapping with out parameter

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/EntityFramework6#1077] opened 2019-07-25 22:21 UTC
Entity Framework should support Out parameters for stored procedure mapping:

CREATE Procedure [dbo].[sp_productorder_insert] (
	@ONumber varchar(100),
	@OID bigint OUT)
AS
Select @OID = NEXT VALUE FOR seq_product;
INSERT INTO [dbo].[TblProductOrder] (OID, ONumber) VALUES (@OID,@ONumber);

Database work should be in the database, not in the code.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/642259/stored-procedure-mapping-with-out-parameter.html
VSTS ticketId: 945768_
_These are the original issue comments:_

Visual Studio Feedback System on 7/12/2019, 01:47 AM (13 days ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by ajcvickers** [comment] 2019-07-25 23:56
Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing so that we can fully investigate.

**Comment by ajcvickers** [comment] 2019-08-06 18:18
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-08-06 18:18 UTC
