### ISSUE TITLE
Enable-Migrations command does not work with EF 6.3.0

### ISSUE THREAD

**Issue by xantari** [aspnet/EntityFramework6#1348] opened 2019-10-05 23:03 UTC
When running Enable-Migrations with EF 6.3.0 I get the following:

```
PM> Enable-Migrations
Enable-Migrations : Cannot bind argument to parameter 'Path' because it is null.
At line:1 char:1
+ Enable-Migrations
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Enable-Migrations], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Enable-Migrations
```

### Steps to reproduce
Open Package Manager Console in VS 2019 and run Enable-Migrations on a class that has a DbContext with EF 6.3.0

### Further technical details
EF version: 6.3.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: VS 2019 16.3.1

**Comment by xantari** [comment] 2019-10-05 23:06
BTW, this is all full framework .NET 4.7.2 projects. Not .NET Core/Standard.

**Comment by xantari** [comment] 2019-10-05 23:16
Reverting to 6.2.0 fixes this issue.

**Comment by bricelam** [comment] 2019-10-07 19:36
Duplicate of #1290

**Closed** 2019-10-07 19:36 UTC
