### ISSUE TITLE
Opening EDMX in designer causes hang in VS2019

### ISSUE THREAD

**Issue by kimjohnson** [aspnet/EntityFramework6#726] opened 2019-03-15 01:02 UTC
Visual Studio Enterprise 2019 Preview, Version 16.0.0 Preview 4.2
Windows 10 Pro - Version 1803, Build 17134.648

Create a new .NET project (tried console, class library, WPF and web app).  Target .NET 4.7.2 (also tried 4.5, 4.7).  Add new item - data - ADO.NET Entity Data Model - EF Designer from Database - SQL Server - EF 6.x - select only 1 table - finish.  The designer opens but causes VS to hang.

Alternately, open a project with an existing small EDMX file.  Try to open the EDMX in the designer - VS hangs.

Also noticed that the Entity Data Model Browser and EDM Mapping Details windows are not available from View - Other Windows menu.

Tried - Repaired VS install.  Also ensured that EF 6 Tools installed.

**Comment by roblarky** [comment] 2019-06-05 09:25
I have a similar issue. I can open the EDMX and the designer shows, but the Model Browser tab/panel shows, though nothing inside it is rendered. It just shows whatever was in that area as though it's not painting. For example, click Solution Explorer tab then back to Model Browser tab and the Model Browser's contents are still the contents that were shown in the Solution Explorer. Clicking in the Model Browser has no reaction, right or left.

I've repaired, uninstalled and reinstalled EF 6 Tools, still the same problem. It's only on this machine, though; I have two other systems using the same code base and the Model Browser works fine. But the system with the issue is a brand new build, only installed VS 2019. The others are older and have had previous versions of VS installed. The solution in question was created in VS2017, which both of the other systems have installed.

**Comment by corylangston** [comment] 2019-06-11 21:23
If you installed .NET 4.8 on your machine you should check out [this solution](https://github.com/aspnet/EntityFramework6/issues/788#issuecomment-500005530)

**Comment by ajcvickers** [comment] 2019-06-26 19:02
Duplicate of #788

**Closed by ajcvickers** 2019-06-26 19:02 UTC
Labels: closed-duplicate
