### ISSUE TITLE
Lazy loading and added entities

### ISSUE THREAD

**Issue by kev160967** [aspnet/EntityFramework6#254] opened 2017-04-24 15:36 UTC
I assume this is a design decision rather than a real issue, but I'm curious as to the reasoning, and suggestions for handling it. In a DbContext with lazy loading enabled I can fetch an entity, then navigate from that entity to a related entity and the related entity will be loaded for me. If I create a new instance of the first entity, using the Create method to get a proxy, set the related entities foreign key field then add it to the context, the related entity will not be lazy loaded. We're running into this as an issue in a project we're migrating from ObjectContext. The issue is particularly a problem in library routines. For example, just hit one that takes an entity and transforms it, hitting a related entity in the process. When the client calls this with a created entity it fails if they set the related entity by foreign key, as opposed to by assigning the entity

**Comment by ajcvickers** [comment] 2017-04-24 17:36
@kev160967 Can you post a complete code listing or project that reproduces what you are seeing?

**Comment by kev160967** [comment] 2017-04-24 19:27
Not at my desk at the moment, but here is a quick example I have running in Linqpad. If it helps I'll post a sample project when I'm back in the office tomorrow. In this example, Booking entities have a relationship to Content items through the property ContentClass:

```
    Partial Public Class Booking
        Public Property ContentClassID As Integer  // FK property for ContentClass property
        Public Overridable Property ContentClass As Contents
```

This code lazy loads the Contents entity, and allows you to access the IsEmpty property:

```
var booking = BookingSet.First(x=> x.ContentClassID == 1);
(booking.ContentClass?.IsEmpty == null).Dump();
```

This code does not - ContentClass simply returns null:

```
var booking=BookingSet.Create();
BookingSet.Add(booking);
booking.ContentClassID=1;
(booking.ContentClass?.IsEmpty==null).Dump();

```
In the last example calling ChangeTracker.DetectChanges(); before examining the property will load the ContentClass entry. It makes no difference whether you include the BookingSet.Add() call or not

**Comment by kev160967** [comment] 2017-04-25 09:59
I have created a small test project that illustrates the issue. The following SQL script can be used to create the database it requires:

```
CREATE DATABASE Test
GO

USE Test
GO

CREATE TABLE [dbo].[Related](
	[ID] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_Related] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[Parent](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[RequiredRelatedID] [int] NOT NULL,
 CONSTRAINT [PK_Parent] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Parent]  WITH CHECK ADD  CONSTRAINT [FK_Parent_Related1] FOREIGN KEY([RequiredRelatedID])
REFERENCES [dbo].[Related] ([ID])
GO

ALTER TABLE [dbo].[Parent] CHECK CONSTRAINT [FK_Parent_Related1]
GO

```
There are three sections to the code. In the first it creates some test entities. In the second it loads the parent then lazy loads the related entity. In the third it creates a parent, sets the FK property to a related entity, then tries to navigate to the related entity
[LLTest.zip](https://github.com/aspnet/EntityFramework6/files/954628/LLTest.zip)

**Comment by ajcvickers** [comment] 2017-04-26 16:20
@kev160967 Thanks for providing more details. EF6 and all earlier versions of EF do not do lazy loading for entities in the Added state. The main reason for this is that Added entities are tracked differently than other entities and don't have real keys. They also don't fixup in the same way. This means that the general case of lazy loading becomes inconsistent. In your case, where an Added entity is on the dependent end of a relationship and it's FK has been set, then it would be possible to do lazy loading correctly. However, even then, we haven't seen much demand for this, and given that it would make it inconsistent in ways that only make sense if you really understand what is going on under the covers, we decided to just not do lazy loading for Added entities.

If Create is used to create the instance and Attach is used to track it as Unmodified, then lazy loading should work as normal. So the workaround if you really need lazy loading for Added entities is to temporarily put the entity in the Unchanged state while doing the loading, then switch it back to Added.

Closing this because this behavior would be be a breaking change and would not necessarily make the experience better given that lazy loading for Added entities would still not work in many cases.

**Closed by ajcvickers** 2017-04-26 16:20 UTC

**Comment by kev160967** [comment] 2017-05-03 09:58
Understood Arthur. In our case though it does unfortunately mean we have to remain with ObjectContext. Alternatives would be to either make knowledge of the repository available in places where it is currently hidden, or to remove all exposed foreign key fields from the model. Neither of these are an option, so we're stuck.

One final thought - are there any hooks in place for intercepting this behaviour (I assume not), or would such hooks be an option at any point going forward?
