### ISSUE TITLE
Method not found: 'Boolean System.Data.Entity.Core.Common.DbProviderManifest.SupportsParameterOptimizationInSchemaQueries()'

### ISSUE THREAD

**Issue by miromakh** [aspnet/EntityFramework6#539] opened 2018-05-15 12:01 UTC
Hi,

I've recently updated Visual Studio to version 15.7.1

Now, when trying to update model like this ![image](https://user-images.githubusercontent.com/15171734/40055435-9a74b54e-5850-11e8-8be7-8b1d573cf5fb.png), after clicking "Finish" I get this 
![image](https://user-images.githubusercontent.com/15171734/40055471-baae32ae-5850-11e8-9e87-d0eefa6dd469.png)

**The output window has the following:**

Unable to generate the model because of the following exception: 'System.MissingMethodException: Method not found: 'Boolean System.Data.Entity.Core.Common.DbProviderManifest.SupportsParameterOptimizationInSchemaQueries()'.
at Microsoft.Data.Entity.Design.VersioningFacade.ReverseEngineerDb.SchemaDiscovery.EntityStoreSchemaGeneratorDatabaseSchemaLoader.CreateFilteredCommand(String sql, String orderByClause, EntityStoreSchemaFilterObjectTypes queryTypes, List`1 filters, String[] filterAliases)
at Microsoft.Data.Entity.Design.VersioningFacade.ReverseEngineerDb.SchemaDiscovery.EntityStoreSchemaGeneratorDatabaseSchemaLoader.LoadDataTable[T](String sql, Func`2 orderByFunc, DataTable table, EntityStoreSchemaFilterObjectTypes queryTypes, IEnumerable`1 filters, String[] filterAliases)
at Microsoft.Data.Entity.Design.VersioningFacade.ReverseEngineerDb.SchemaDiscovery.EntityStoreSchemaGeneratorDatabaseSchemaLoader.LoadTableDetails(IEnumerable`1 filters)
at Microsoft.Data.Entity.Design.VersioningFacade.ReverseEngineerDb.SchemaDiscovery.EntityStoreSchemaGeneratorDatabaseSchemaLoader.LoadStoreSchemaDetails(IList`1 filters)
at Microsoft.Data.Entity.Design.VisualStudio.ModelWizard.Engine.ModelGenerator.GetStoreSchemaDetails(StoreSchemaConnectionFactory connectionFactory)
at Microsoft.Data.Entity.Design.VisualStudio.ModelWizard.Engine.ModelGenerator.CreateStoreModel()
at Microsoft.Data.Entity.Design.VisualStudio.ModelWizard.Engine.ModelGenerator.GenerateModel(List`1 errors)
at Microsoft.Data.Entity.Design.VisualStudio.ModelWizard.Engine.ModelBuilderEngine.GenerateModels(String storeModelNamespace, ModelBuilderSettings settings, List`1 errors)
at Microsoft.Data.Entity.Design.VisualStudio.ModelWizard.Engine.ModelBuilderEngine.GenerateModel(ModelBuilderSettings settings, IVsUtils vsUtils, ModelBuilderEngineHostContext hostContext)'.

**In this project:**

- Windows 10 version 1803
- The EntityFramework version is 6.2.0
- The .Net version is 4.7.1

**What I've tried:**

- Clean
- Rebuild
- Reinstall EntityFramework (with removing leftover DLLs from the project)
- Change .Net version to earlier and back

Any help would be appreciated.

Thank you in advance.

**Comment by ErikEJ** [comment] 2018-05-15 12:02
Which SQL Server version?

**Comment by miromakh** [comment] 2018-05-15 12:11
Microsoft SQL Server Standard (64-bit) 13.0.1742.0
Microsoft SQL Server Web (64-bit) 13.0.4422.0

**Comment by ajcvickers** [comment] 2018-05-15 17:43
@lajones Can you take a look at this?

**Comment by lajones** [comment] 2018-05-15 21:40
@miromakh It looks like you've got an updated version of the Tooling DLLs while at the same time having an old version of EntityFramework.DLL installed (and probably EntityFramework.SqlServer.DLL as well).

Would you please take a look at a) the copy of EntityFramework.DLL installed under the Common7\IDE directory for your Visual Studio installation, and b) at any instance of EntityFramework.DLL installed in your project. For both of them right-click and select Properties. Then select the "Details" tab and please report the File Versions for both of those.

**Comment by ajcvickers** [comment] 2018-05-15 22:05
@lajones Is it possible that the old version is GAC'ed?

**Comment by lajones** [comment] 2018-05-15 22:16
@ajcvickers It shouldn't be, but I suppose it's worth checking. @miromakh What version of VS did you have before? Also can you report the results of the command `gacutil -l EntityFramework` from an Admin CMD prompt please?

**Comment by srednasoft** [comment] 2018-05-16 08:43
Hi, I have the exact same problem. 
I have not found a solutin to this.
I have VS 15.7.1 and EF 6.2

**Comment by divega** [comment] 2018-05-16 10:51
Another approach that you can use to identify the exact copy of entityframework.dll being used is to attach a debugger to Visual Studio, before this exception happens, for example while showing the "Choose Your Database Objects and Settings" step in the Update Wizard. Here are some steps you can use to do this using another instance of Visual Studio:

1. Once you are in the "Choose Your Database Objects and Settings" step, open a new instance of VS, e.g. by shift-clicking on the VS icon on the task bar. 
2. Go to the Debug menu on the new instance, and select "Attach to Process..."
3. From the list, and double-click on the process with the name "devenv.exe"
4.  On the Debug menu, go to Windows > Modules
5. On the Modules window search for entityframework, locate entityframework.dll, right-click on it and in the context menu select Copy Value > Copy Directory Path.
6. Now you can open that path on Windows Explorer or the command line and examine the assembly properties.

@miromakh to your specific question: If you have confirmed that the EF assemblies are in the GAC, I would normally recommend uninstalling them from the GAC using 'gacutil /u <assembly_display_name>'. EF6 was not designed to run from the GAC and installing it on the GAC can cause issues, like the one you are experiencing now. 

That said, (always assuming that you confirmed they are already in the GAC) unless you remember installing the EF assemblies in the GAC manually, it is possible that some application installer did it. And now there is a chance that such application will not work without it. EF6 is designed to be deployed alongside application binaries, so a workaround would be to copy the right version of the EF6 to the application's directory. 

As a last resort, you could attempt updating the assemblies in the GAC (again, assuming that you confirmed they are already in the GAC) using the 6.2 version, using 'gacutil /i <assembly_path>' from a developer command prompt, but as I said before this is not recommended and it can cause similar problems with other applications in the future.

**Comment by srednasoft** [comment] 2018-05-16 10:54
I have now uinstalled VS 2017 15.7.1 and reinstalled VS 2017 15.0 
EF is working good again.
It must be a problem with the latest VS 2017 version.

**Comment by divega** [comment] 2018-05-16 11:11
@srednasoft this is working fine using Visual Studio 2017 15.7.1 on my machine (besides the fact that we tested this scenario before we released the updated EF Tools in 15.7). 

So the problem is rather specific to your machine setup, and we are trying to find the root cause in case this can help other customers. 

As @lajones [mentioned previously in this issue](https://github.com/aspnet/EntityFramework6/issues/539#issuecomment-389322576) it is likely that for some reason you have an older version of EntityFramework.dll and EntityFramework.SqlServer.dll that for some reason are being preferred over the correct versions when Visual Studio needs to use the EF6 runtime.

I understand that having to uninstall and reinstalling Visual Studio can be a real hassle, but if you install version 15.7.1 again, please try the steps I described [in my previous comment](https://github.com/aspnet/EntityFramework6/issues/539#issuecomment-389477350) to identify the actual copy of the EF6 assemblies that are being loaded by Visual Studio.

For what it is worth, the correct versions of EntityFramework.dll and EntityFramework.SqlServer.dll are normally located on the Visual Studio application directory, under common7\ide\, and the product version should be 6.2.0-61023.

Note that this is the correct version for the EF Tools contained in Visual Studio 2017 15.7.1 regardless of what version of EF your projects are using.

**Comment by srednasoft** [comment] 2018-05-16 11:16
Thanx
I will try to upgrade again later. I have to finish some developement first :-)
The EF is in the GAC and also in the package area for the projects. Could be missmatch there.

**Comment by miromakh** [comment] 2018-05-16 11:55
@divega ,
Hi,
Thank you so much!!! 
**gacutil /u EntityFramework** worked like a charm.
I don't know how it got to the GAC if it shouldn't be there at first place and if there's a program that installed it and it will seize working - so be it. On this machine I only care about being able to use Visual Studio... :-)

**Comment by divega** [comment] 2018-05-16 12:19
Glad to hear @miromakh 

No problem @srednasoft. FYI, the version in the GAC takes precedence of the version in the VS directory. That is why you are seeing this error.

**Comment by GermanSniper** [comment] 2018-05-24 08:15
I got the same error.

If I try to uninstall with gacutil I got:
Unable to uninstall: assembly is required by one or more applications

**Comment by ChrisWaitman** [comment] 2018-06-19 08:17
Hi,
same problem here! Updated yesterday from 15.7.0 to 15.7.3 and now i get the same error... :( 
This is very annoying because i have urgent development work to do!

OS: Windows 10
Version under C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE is 6.1.3 ??!!

![grafik](https://user-images.githubusercontent.com/40383593/41584923-e3a2625c-73a8-11e8-83a4-2c2ef1d965ab.png)

![grafik](https://user-images.githubusercontent.com/40383593/41584984-045bdc44-73a9-11e8-8a4c-e97b60619cb3.png)

I have this thing in the GAC too.. and i'm unable to uninstall..
![grafik](https://user-images.githubusercontent.com/40383593/41585224-bc8368b4-73a9-11e8-9ef5-631f7dd96c9f.png)

Has anybody a solution to this problem? Thanks!

**Comment by ajcvickers** [comment] 2019-03-18 22:59
If EF assemblies are in the GAC, then they must be removed. Beyond this, we have not been able to reproduce with latest VS editions, so closing. If you're still hitting this, then please file a new issue with full steps to reproduce.

**Closed by ajcvickers** 2019-03-18 22:59 UTC

**Comment by jsswp2004** [comment] 2019-04-11 15:08
@ChrisWaitman Deleting the folders worked! Thanks!

**Comment by Prakashp** [comment] 2021-04-20 16:41
I have faced this issue using VS 2017. Below are the steps I have taken to get rid of this issue.

- Go to "C:\Windows\Microsoft.NET\assembly\GAC_MSIL\EntityFramework" folder location
- Cut the "EntityFramework.dll" from the above folder and kept somewhere
- Go to the EF project and update the model without any error

Hope this will helps. Thanks.
