### ISSUE TITLE
Migrations: Better support for scripting raw SQL operations that require a separate batch

### ISSUE THREAD

**Issue by San7hos** [aspnet/EntityFramework6#79] opened 2016-10-06 12:25 UTC
We have disabled automatic migrations. We use Update-Databse to update our local dev databases and migrate.exe to update our dev/test remote database.

However, when deploying for a client, we need to generate a sql script.

When we wanted to generate a complete script from state 0 to current state we used
`Update-Database -SourceMigration:0 -Script`. We use `this.SqlResource` in some of our migrations because we need to `ALTER VIEW` and EF has to use a sql script.

One of the if blocks looks like this (I have extracted the block from a far longer script and also obfuscated the names):

``` sql
DECLARE @CurrentMigration [nvarchar](max)

IF object_id('[dbo].[__MigrationHistory]') IS NOT NULL
    SELECT @CurrentMigration =
        (SELECT TOP (1) 
        [Project1].[MigrationId] AS [MigrationId]
        FROM ( SELECT 
        [Extent1].[MigrationId] AS [MigrationId]
        FROM [dbo].[__MigrationHistory] AS [Extent1]
        WHERE [Extent1].[ContextKey] = N'somecontext'
        )  AS [Project1]
        ORDER BY [Project1].[MigrationId] DESC)

IF @CurrentMigration < '201608081034308_AddPayerIdToViewAView'
BEGIN
    ALTER VIEW [dbo].[ViewAView] -- the problematic ALTER VIEW
        AS SELECT
          sp.[Id]
        , sp.[PayerId]
        , apc.[UserId]
    FROM [dbo].[ATable] sp
        JOIN [dbo].[OtherTable] apc
            ON sp.[CcId] = apc.[CcId]
    UNION
    SELECT
          sp.[Id]
        , sp.[PayerId]
        , u.[Id] UserId
    FROM [dbo].[ATable] sp
        CROSS JOIN [dbo].[User] u
        LEFT JOIN [dbo].[OtherTable] apc
            ON sp.[CcId] = apc.[CcId]
            AND u.[Id] = apc.[UserId] 
    WHERE apc.[UserId] IS NULL

    -- the problem might also be related to the fact that we do ALTER VIEW and INSERT after
    INSERT [dbo].[__MigrationHistory]([MigrationId], [ContextKey], [Model], [ProductVersion])
    VALUES (N'201608081034308_AddPayerIdToViewAView', N'somecontext', <base 64 of the model>, N'6.1.3-40302')
END
```

The up method that generated such a code looks similar to:

``` csharp
public override void Up()
{
    this.SqlResource("Model.Nmspc.Migrations.Sql._201608081034308_AddPayerIdToViewAView_Up");
}
```

**Comment by rowanmiller** [comment] 2016-10-07 18:43
@San7hos can you share the error that you are getting

**Comment by rowanmiller** [comment] 2016-10-12 18:27
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Comment by San7hos** [comment] 2016-10-12 20:35
@rowanmiller sorry, I have been very busy lately because we were in a go-live situation. Let me please provide you with the error tomorrow.

**Comment by San7hos** [comment] 2016-10-13 16:33
So the error is

> Msg 156, Level 15, State 1, Line 51
> Incorrect syntax near the keyword 'VIEW'.
> Msg 156, Level 15, State 1, Line 248
> Incorrect syntax near the keyword 'VIEW'.
> Msg 156, Level 15, State 1, Line 499
> Incorrect syntax near the keyword 'VIEW'.
> Msg 319, Level 15, State 1, Line 500
> Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
> Msg 156, Level 15, State 1, Line 556
> Incorrect syntax near the keyword 'VIEW'.

The first error on line 51 is the error I mention above and points to the line marked with comment "-- the problematic ALTER VIEW".

**Comment by rowanmiller** [comment] 2016-10-17 20:37
As a workaround, can you try wrapping the alter statement in a call to EXECUTE. 

i.e. swap `Model.Nmspc.Migrations.Sql._201608081034308_AddPayerIdToViewAView_Up` to have the following in it:

```SQL
EXECUTE('ALTER VIEW [dbo].[ViewAView] -- the problematic ALTER VIEW
        AS SELECT
          sp.[Id]
        , sp.[PayerId]
        , apc.[UserId]
    FROM [dbo].[ATable] sp
        JOIN [dbo].[OtherTable] apc
            ON sp.[CcId] = apc.[CcId]
    UNION
    SELECT
          sp.[Id]
        , sp.[PayerId]
        , u.[Id] UserId
    FROM [dbo].[ATable] sp
        CROSS JOIN [dbo].[User] u
        LEFT JOIN [dbo].[OtherTable] apc
            ON sp.[CcId] = apc.[CcId]
            AND u.[Id] = apc.[UserId] 
    WHERE apc.[UserId] IS NULL')
```

**Comment by San7hos** [comment] 2016-10-19 05:37
The `EXECUTE` solution works, but if you want to have scripts without it (e.g. because you do not want to write the sql as string to enable proper code highlighting) and automate the process, there are certain steps that has to be taken:

__Scenario 1: multiple files__

Scripts that has to change several views has to be split in multiple files. Those files has to be treated separately: 

```csharp
foreach (var file in this.GetMigrationFiles())
{
    this.Sql($"EXECUTE('{read file and escape apostrophes}')");
}
```

__Sceneraio 2: script with `GO` statements__

If you have a script with multiple statements separated by `GO` statements, you need to split the script by the `GO` statements, sanitize it and then wrap with `EXECUTE`:

```csharp
foreach (string chunk in this.ReadMigrationFile()
                             .EscapeApostrophes()
                             .SplitByGoStatement())
{
    this.Sql($"EXECUTE('{chunk}')");
}
```

We tried some easier approaches but it seems that EF cannot handle those. We had issues where our `EXEC` was wrapper with EF `EXECUTE` and where script wrapped in `EXECUTE` was broken down by `GO` statements resulting in a malformed script.

**Comment by rowanmiller** [comment] 2016-10-24 17:49
We will try and improve this in 6.2.0. One idea is a flag on `SQL(...)` that indicates it needs to be in a separate batch.

**Comment by anpete** [comment] 2017-01-13 18:33
@San7hos While looking at this I noticed that EF will use the EXECUTE pattern anytime the passed SQL ends in '\r\nGO'. Does this approach work for you? 

cc @rowanmiller

**Comment by rowanmiller** [comment] 2017-01-18 20:06
Per last comment from @anpete, we feel we already have a way to handle this.

**Closed by rowanmiller** 2017-01-18 20:06 UTC
Labels: type-enhancement
