### ISSUE TITLE
DbMigrator Update() issue after updating to EF 6.2

### ISSUE THREAD

**Issue by buchajmal** [aspnet/EntityFramework6#391] opened 2017-11-03 18:33 UTC
I have been getting the following issue after updating my project from EF 6.1.3 to 6.2. This is an Asp.Net application where I keep my Code First models and Db context in a separate project.

> Unable to update database to match the current model because there are pending changes and automatic migration is disabled. Either write the pending model changes to a code-based migration or enable automatic migration. Set DbMigrationsConfiguration.AutomaticMigrationsEnabled to true to enable automatic migration.

Following is the code where I get the exception, which is in Startup.Auth.cs file.

`// Entity Framework Db Migration`
`var efMigrationSettings = new Domain.Services.Migrations.Configuration();`
`var efMigrator = new DbMigrator(efMigrationSettings);`
`efMigrator.Update();`

I do not get any error when I tried manually updating the db from the "Package Manager Console" using "update-database" command, and yet when I run the app using F5 I still get this error.

But when I downgraded EF to 6.1.3 everything started working perfectly.

**Comment by ajcvickers** [comment] 2017-11-07 17:29
@buchajmal If you generate a migration (with "add-migration") what does it look like? In other words, what does EF think the differences in the model are?

**Comment by ajcvickers** [comment] 2017-11-17 20:24
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2017-11-17 20:24 UTC

**Comment by dnistreanu** [comment] 2018-05-04 08:57
I can reproduce the issue but at the 'add-migration' step

**Comment by mark-trumed** [comment] 2018-08-08 17:51
I had the exact same issue as @buchajmal above with a WPF app that uses code first migrations. In addition to the upgrade to Entity Framework 6.2, I had also upgraded a number of other NuGet packages at the same time. I reverted all the upgrades and upgraded the packages one at a time. It turns out that the culprit that caused the "Unable to update database" problem was actually Newtonsoft.Json version 11.0.2! The upgrade to Entity Framework 6.2 was fine, as long as Netwonsoft.Json 11.0.2 wasn't installed.

**Comment by Bronzato1** [comment] 2019-08-13 14:48
Many thanks to @mark-trumed for commenting. I was in the exact same situation.

**Comment by shaojun** [comment] 2019-10-16 09:58
I had this problem maybe it's too late to report here, my code:

        var migrator = new DbMigrator(
                    new DbMigrationsConfiguration()
                    {
                        ContextType = typeof(DefaultAppDbContext),
                        MigrationsAssembly = Assembly.GetExecutingAssembly(),
                        AutomaticMigrationsEnabled = false,
                    }
                    );
        logger.Info("PendingMigrations: " + (migrator.GetPendingMigrations()?.Aggregate("", (acc, n) => acc + ", " + n) ?? ""));
        migrator.Update();

the exception say:

> System.Data.Entity.Migrations.Infrastructure.AutomaticMigrationsDisabledException: Unable to update database to match the current model because there are pending changes and automatic migration is disabled. Either write the pending model changes to a code-based migration or enable automatic migration. Set DbMigrationsConfiguration.AutomaticMigrationsEnabled to true to enable automatic migration.
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
   at System.Data.Entity.Migrations.DbMigrator.<>c__DisplayClasse.<Update>b__d()
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.Update()


if I change the `AutomaticMigrationsEnabled` to `true`, the exception say:

> System.Data.Entity.Migrations.Infrastructure.MigrationsException: Automatic migrations that affect the location of the migrations history system table (such as default schema changes) are not supported. Please use code-based migrations for operations that affect the location of the migrations history system table.
   at System.Data.Entity.Migrations.DbMigrator.AutoMigrate(String migrationId, VersionedModel sourceModel, VersionedModel targetModel, Boolean downgrading)
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
   at System.Data.Entity.Migrations.DbMigrator.<>c__DisplayClasse.<Update>b__d()
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.Update()



at last, if I do the `EntityFramework\Add-Migration test` in visual studio 2019 Package Manager Console, it always generate an empty migration record that means the Model and the migration history is aligned.

BTW, the above `Netwonsoft.Json 11.0.2` explain is not my situation, I had its version of 12.
