### ISSUE TITLE
EF migrations - SqlGenerator unable to translate identity changes

### ISSUE THREAD

**Issue by jensg** [aspnet/EntityFramework6#477] opened 2018-02-27 15:13 UTC
The fluent migrator (DSL) correctly determines what changes need to happen, however the SQL migrator is unable to translate these changes. These are the steps the SQL migrator should perform, however they are not translated:

1. Drop all foreign key constraints that point to the primary key we are changing
2. Drop the primary key constraint
3. Rename the existing column (so that we can re-create the foreign key relationships later)
4. Add the new primary key column with the new identity setting
5. Update existing data so that previous foreign key relationships remain 
- If the new column is an identity column, we need to update all foreign key columns with the new values

- If  the new column doesn’t have identity on, we can copy the old values from the previous identity column

6. Drop old primary key column
7. Add primary key constraint
8. Add back foreign key constraints

The problem is described here in detail:
https://romiller.com/2013/04/30/ef6-switching-identity-onoff-with-a-custom-migration-operation/
https://blog.sqlauthority.com/2009/05/03/sql-server-add-or-remove-identity-property-on-column/

**Comment by ajcvickers** [comment] 2018-02-27 16:53
Duplicate of #69

**Closed by ajcvickers** 2018-02-27 16:53 UTC
