### ISSUE TITLE
entity framework update-database script

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/EntityFramework6#1429] opened 2019-10-30 18:24 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/782512/entity-framework-update-database-script.html)._

---
running visual studio 2019 with EF 6.2

in package manage console when i run the command
update-database -script 
VS2019 crashes and restart

In event viewer it says devenv.exe has an unhandled exception

if i do a update-database everything works fine, so my problem is I only want the script not doint the actual update

---
#### Visual Studio Feedback System on 10/18/2019, 01:15 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/18/2019, 02:15 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2019-11-01 15:44
Please post the stack trace of the exception.

**Comment by ajcvickers** [comment] 2019-11-08 16:45
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-11-08 16:45 UTC
