### ISSUE TITLE
Inherit from generic argument class

### ISSUE THREAD

**Issue by zehavibarak** [aspnet/EntityFramework6#63] opened 2016-09-16 05:08 UTC
Hi,

I have the following scenario:

```c#
[Table()] 
abstract class A {
} 
abstract class B <T> {
} 
class C: B<D> {
}
```

Class C inherits from class B with type D as generic argument, which, on it's place, inherits from class A.

Trying to query DbSet<C> yield error saying C is 'not in same class hierarchy' as A.

Also tried to annotate class B as the EF Table() instead of A. That didn't work as well.

Why doesn't this work? I think it should.

Tnx

**Comment by rowanmiller** [comment] 2016-10-12 17:29
Based on the code you shared it is correct that  `C is not in same class hierarchy as A`. C inherits from B, but B does not inherit from A. Also this issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean 😄... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).Based on the code you shared it is correct that  `C is not in same class hierarchy as A`. C inherits from B, but B does not inherit from A.

**Comment by rowanmiller** [comment] 2016-10-19 18:28
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed by rowanmiller** 2016-10-19 18:28 UTC
