### ISSUE TITLE
Can HasIndex only be used for creating one index?

### ISSUE THREAD

**Issue by henrikdahl8240** [aspnet/EntityFramework6#575] opened 2018-07-09 09:35 UTC
Using the HasIndex introduced by version 6.2 I have defined two indexes like this:
`this.HasIndex(t => t.Col1ID).HasName("IX_Col1ID");
this.HasIndex(t => new { t.Col2ID, t.Col3, t.Col1ID }).HasName("IX_Col3Properties").IsUnique();
`
Interestingly only the index IX_Col3Properties is being created, the index IX_Col1ID is not being created.

Before, I defined both indexes using attributes on the Col1ID, Col2ID and Col3 properties of the POCO class. In that case both indexes were being created.

If I swap the two definitions, both of the two definitions will now result in an index in the database.

Is the rules for this "shooting game" documented anywhere, i.e. in which mutual order must multiple HasIndex invocations be done?

It seems quite odd, that it may be necessary to study the concrete indexes made in order to see, if Entity Framework has actually made the indexes defined by HasIndex.

Is it really correct, that HasIndex does not work correct for this typical pattern of usage?

At this moment it reads at https://www.nuget.org/packages/EntityFramework/ that version 6.2.0 was last updated 8 months ago and has 3.106.887 downloads. It should be one of the most downloaded packages. If I am right in what I have observed, wouldn't it be quite reasonable if you corrected your mistake(s) and made a new version available?

**Comment by chrisblock** [comment] 2018-09-07 21:51
I also think this would be resolved by #534.

**Comment by ajcvickers** [comment] 2019-03-18 23:06
Duplicate of #460

**Closed by ajcvickers** 2019-03-18 23:06 UTC
