### ISSUE TITLE
Starting to get "already an open datareader" error after a migration to 6.2

### ISSUE THREAD

**Issue by Benjiiim** [aspnet/EntityFramework6#444] opened 2018-01-14 15:20 UTC
On a ASP.NET Webform project running on .NET Framework 4.6.

I'm starting to get "There is already an open datareader associated with this command which must be closed first." error on a project after migrating to 6.2 (from 6.1.3).
No more error after a rollback to 6.1.3.

I am reusing a single context for every http request thanks to the following code:
```
public static class DbContextPerHttpRequest
{
    public static AlphaModel Context
    {
        get
        {
            string objectContextKey = HttpContext.Current.GetHashCode().ToString("x") + "_ctx";
            if (!HttpContext.Current.Items.Contains(objectContextKey))
            {
                HttpContext.Current.Items.Add(objectContextKey, new AlphaModel());
            }
            return HttpContext.Current.Items[objectContextKey] as AlphaModel;
        }
    }
}
```
Each time I need the model, I'm using DbContextPerHttpRequest.Context

Before I start to investiguate more, does someone know any obvious reason for that?

Thanks a lot

**Comment by dekenless** [comment] 2018-01-15 17:49
I guess it would depend on what you are doing AlphaModel; if you are newing up a DbContext then I would expect problems since you are effectively caching it (if I am reading your code correctly). This does not appear to be thread-safe.

**Comment by ajcvickers** [comment] 2018-01-16 16:56
@Benjiiim As @dekenless says, the context is not thread safe, so generally sharing a single context instance for multiple requests will not be safe. Best practice is to use a short-lived context instance, typically one per unit-of-work. In a web app, that can often translate into one context instance per request, which is the typical pattern that we see the most often.

**Comment by Benjiiim** [comment] 2018-01-21 19:23
Sorry, I have been long to answer.
The context is short-lived, as it is cached for the request only (through HttpContext.Current).
This code has worked as is for the last 5 years at least.
The issue has appeared only after the migration to 6.2. No change in load for example.
It seems that it happens only when the request is done through a referenced class library and not the web app project itself.

**Comment by ajcvickers** [comment] 2018-01-29 19:51
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2018-01-29 19:51 UTC
