### ISSUE TITLE
Database.SqlQuery seems to auto-commit and immediately blow away any transaction started with Database.BeginTransaction

### ISSUE THREAD

**Issue by triynko** [aspnet/EntityFramework6#1424] opened 2019-10-27 03:51 UTC
Database.SqlQuery seems to auto-commit and immediately blow away any transaction started with Database.BeginTransaction.  How can I call a stored procedure that returns data (currently using Database.SqlQuery&lt;T&gt;) within a transaction if the transaction I opened with Database.BeginTransaction is auto-committed and Database.CurrentTransaction is automatically set to null? Even if I save the DbContextTransaction returned by BeginTransaction (and even if I instead call Database.UseTransaction(Connection.BeginTransaction()), this problem still occurs. When committing the transaction I hang on to, I just get an error saying the provider failed on commit, and the "connection" property is null.  This makes no sense.

I'm looking online for other people experiencing this issue, and found the same thing here: https://forums.asp.net/t/2045093.aspx?The+underlying+provider+failed+on+Commit

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7e17e30-4349-3193-01f1-5eb33cb88546
* Version Independent ID: dcb6d719-ffc2-2796-c82c-b9873b74cb76
* Content: [Working with Transactions - EF6](https://docs.microsoft.com/en-us/ef/ef6/saving/transactions#feedback)
* Content Source: [entity-framework/ef6/saving/transactions.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/saving/transactions.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2019-11-08 16:45
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-11-08 16:45 UTC
