### ISSUE TITLE
update-database -script command is adding create  '__MigrationHistory' table script in the generated script despite that table is already exist in the database?

### ISSUE THREAD

**Issue by deepakmhr** [aspnet/EntityFramework6#745] opened 2019-04-02 19:55 UTC
My application has around 300 migrations out of that around 260 are already in the production, now we have to release a new version of the software with those newly added migrations.

Generally, we generate a DB script for deployment and then run that script on the production DB, this time around when I was trying to generate the script using update-database -script command it's adding a script to create the _MigrationHistory table despite that table already exists in the database?

Is there any fix for this problem?

```
CREATE TABLE [dbo].[__MigrationHistory] (
    [MigrationId] [nvarchar](150) NOT NULL,
    [ContextKey] [nvarchar](300) NOT NULL,
    [Model] [varbinary](max) NOT NULL,
    [ProductVersion] [nvarchar](32) NOT NULL,
    CONSTRAINT [PK_dbo.__MigrationHistory] PRIMARY KEY ([MigrationId], [ContextKey])
)
GO
```
Though, if I'm running only  _update-database_ , it works perfectely fine.

What is the problem with _update-database -script_ command? 

### Further technical details
EF version: 6.1.2
Database Provider: System.Data.SqlClient
Operating system: Windows 10
IDE:  Visual Studio 2017 15.9

**Comment by shobhitwalia123** [comment] 2019-04-03 04:49
facing same issue on my local.

**Comment by ajcvickers** [comment] 2019-06-26 19:04
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment] 2019-08-06 18:12
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-08-06 18:12 UTC
