### ISSUE TITLE
During DbDatabaseExist call, the AssociationSet do not have correct details; if Fluent APIs or Data Annotations are used to modify the Table Name participating in the ForeignKey relationship. The AssociationSet still preserves the old name defined in the 

### ISSUE THREAD

**Issue by jrachama** [aspnet/EntityFramework6#270] opened 2017-05-09 09:45 UTC
We are third party EF provider and we are seeing an issue with CreateIfNotExist. With this call our provider generates a query to look for database objects like tables, keys e.t.c for the Context. 
And if in model table name is modified using dataannotations or fluent api we see an issue in foreign key names. 

Foreign Key name is dependent on table name and foreign key columns. In DbDatabaseExists method we generate a query to identify existence of database objects for the context. And inside the same method for ForeignKey names we refer AssociationSet of StoreItemCollection that we receive in DbDatabaseExists. But the problem is we are not receiving AssociationSet with correct details, it shows the table name same as class name instead of name which was specified in data annotation or fluent api. This results in wrong Foreign Key name to be searched. But create database object queries are getting generated correctly. 

And as there is difference in foreign key names that were used while creating and verifying, provider gets mislead that database is not present in backend. And thus, tries to create database objects. And fails with Table or View already exists. 

So, our issue will get resolved if AssociationSet is correctly updated with data annotation or fluent api table names.

**Comment by ajcvickers** [comment] 2017-05-15 17:31
@jrachama Can you use EDMXWriter class to generate the EDMX from your Code First model and post it here with reference to the elements that don't have the data you expect?

**Comment by ajcvickers** [comment] 2017-05-22 18:37
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2017-05-22 18:37 UTC

**Comment by jrachama** [comment] 2017-06-07 12:41
We have generated the EDMX file from the code first application using EDMXWriter class , the model contain the relationship and annotation to change the table name so the generated edmx file should contain the Association name with the new table name but still it referring the old name only. For more detail information please refer below the details and attachment. 

1.Model contain the one to many relationship and annotation to change the table name.

[Table("ActiveChildren")]
public class Student
    {
        public Student() { }

        public int StudentId { get; set; }
        public string StudentName { get; set; }

        public int StandardRefId { get; set; }

        [ForeignKey("StandardRefId")]
        public virtual Standard Standard { get; set; }

    }

    public class Standard
    {
        public Standard()
        {
            StudentsList = new List<Student>();
        }
        public int StandardId { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Student> StudentsList { get; set; }
    }

2.In newly generated EDMX file association name is "Student_Standard" instead of “ActiveChildren_Standard”  




[Model.zip](https://github.com/aspnet/EntityFramework6/files/1057970/Model.zip)
