### ISSUE TITLE
Specified cast is not valid on 3rd Include

### ISSUE THREAD

**Issue by ndenkha** [aspnet/EntityFramework6#119] opened 2016-11-30 23:04 UTC
Not to duplicate work, but I posted my issue on this closed post in case no one will look at a closed issue.

https://github.com/aspnet/EntityFramework/issues/1748

I hope the info I provided is enough to reproduce.

So this is the query that throws the error.
var existingUser =
            Users.Include(x => x.Applications)
                .Include(x => x.Roles)
                .Include(x => x.Markets)
                .FirstOrDefault(x => x.Id == user.Id);

My undesired work around is this by querying twice.
var existingUser =
            Users.Include(x => x.Applications)
                .Include(x => x.Roles)
                .FirstOrDefault(x => x.Id == user.Id);

existingUser =
            Users.Include(x => x.Markets)
                .FirstOrDefault(x => x.Id == user.Id);

And here's the crazy thing, this other work around worked for couple of times and it just started giving me the same error.
var queryableUser = this.Users
                .Where(x => x.Id == user.Id)
                .Include(x => x.Applications)
                .Include(x => x.Roles)
                .Include(x => x.Markets);
var existingUser = queryableUser.FirstOrDefault();

**Comment by ndenkha** [comment] 2016-12-01 05:51
Additional info. This is happening from inside my repository layer only. I have the exact 3 includes in the API layer and never run into this issue. i.e. I have this in one of my API methods.

var appUser = MyRepository.Users
                .Where(x => x.Id == userId)
                .Include(x => x.Applications)
                .Include(x => x.Roles)
                .Include(x => x.Markets)
                .ProjectTo<AppUserView>();

**Comment by smitpatel** [comment] 2016-12-10 01:20
From https://github.com/aspnet/EntityFramework/issues/1748#issuecomment-263751344

Hi guys, I'm having this issue with EF 6.1.3 and it only happens when I include any 3rd Include, i.e. I can get a single or 2 navigation props in any combination fine. I'm running against MySQL 5.7 AWS RDS, and here are my models and tables.

// If I take any one of the includes I get the user object back correctly with only those two navigation props populated, the moment I add any 3rd include I get the error.

Please advise.

```c#
var existingUser =
            Users.Include(x => x.Applications)
                .Include(x => x.Roles)
                .Include(x => x.Markets)
                .FirstOrDefault(x => x.Id == user.Id);

public abstract class Trackable : ITrackable
    {
        public DateTime CreatedOn { get; set; }

        public DateTime UpdatedOn { get; set; }
    }

public interface ITrackable
    {
        DateTime CreatedOn { get; set; }

        DateTime UpdatedOn { get; set; }
    }

public class Auditable : Trackable, IAuditable
    {
        public string CreatedBy { get; set; }

        public string UpdatedBy { get; set; }
    }

public interface IAuditable
    {
        string CreatedBy { get; set; }

        string UpdatedBy { get; set; }
    }

public class AppUser : Auditable
    {
        public int Id { get; set; }

        public string Username { get; set; }    // This can be user's domain ID for internal users and any other ID for external users.

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Email { get; set; }

        public string Title { get; set; }

        public bool IsActive { get; set; }

        public virtual ICollection<Application> Applications { get; set; }

        public virtual ICollection<Role> Roles { get; set; }
        
        public virtual ICollection<Market> Markets { get; set; }

        public AppUser()
        {
            Applications = new List<Application>();
            Roles = new List<Role>();
            Markets = new List<Market>();
        }
    }

public class Application : Auditable
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public bool IsDeleted { get; set; }

        public virtual ICollection<Role> Roles { get; set; }

        public virtual ICollection<AppUser> AppUsers { get; set; }

        public Application()
        {
            Roles = new List<Role>();
            AppUsers = new List<AppUser>();
        }
    }

public class Role : Auditable
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public int ApplicationId { get; set; }

        // NOTE: commented out as it creates duplicate EDM relationship.
        //public virtual Application Application { get; set; }

        public virtual ICollection<AppUser> AppUsers { get; set; }

        public virtual ICollection<Scope> Scopes { get; set; } 


        public Role()
        {
            //Application = new Application();
            AppUsers = new List<AppUser>();
            Scopes = new List<Scope>();
        }
    }

public class Market
    {
        public short Id { get; set; }

        public string Name { get; set; }

        public string State { get; set; }

        public string Region { get; set; }

        public string Timezone { get; set; }

        public byte TimezoneOrder { get; set; }

        public bool IsActive { get; set; }

        public virtual ICollection<AppUser> AppUsers { get; set; }

        public Market()
        {
            AppUsers = new List<AppUser>();
        }
    }

// Here are the mapping files.
public class ApplicationMap : EntityTypeConfiguration<Application>
    {
        public ApplicationMap()
        {
            ToTable("Application");

            HasKey(x => x.Id);
            Property(x => x.Id).HasColumnName("ApplicationId");

            HasMany(x => x.Roles).WithRequired().HasForeignKey(x => x.ApplicationId);
        }
    }

public class AppUserMap : EntityTypeConfiguration<AppUser>
    {
        public AppUserMap()
        {
            ToTable("AppUser");

            HasKey(x => x.Id);
            Property(x => x.Id).HasColumnName("UserId");

            HasMany(x => x.Applications).WithMany(y => y.AppUsers).Map(z =>
            {
                // NOTE: The left table is AppUser, and right table is Application.
                z.MapLeftKey("UserId");
                z.MapRightKey("ApplicationId");
                z.ToTable("UserApplication");
            });

            HasMany(x => x.Roles).WithMany(y => y.AppUsers).Map(z =>
            {
                // NOTE: The left table is AppUser, and right table is Role.
                z.MapLeftKey("UserId");
                z.MapRightKey("RoleId");
                z.ToTable("UserRole");
            });

            HasMany(x => x.Markets).WithMany(y => y.AppUsers).Map(z =>
            {
                // NOTE: The left table is AppUser, and right table is Market.
                z.MapLeftKey("UserId");
                z.MapRightKey("EnterpriseMarketId");
                z.ToTable("UserMarket");
            });

        }
    }

public class RoleMap : EntityTypeConfiguration<Role>
    {
        public RoleMap()
        {
            ToTable("Role");

            HasKey(x => x.Id);
            Property(x => x.Id).HasColumnName("RoleId");

        }
    }

public class MarketMap : EntityTypeConfiguration<Market>
    {
        public MarketMap()
        {
            ToTable("Market");

            HasKey(x => new {x.Id});
            Property(x => x.Id).HasColumnName("EnterpriseMarketId");
        }
    }

public class ScopeMap : EntityTypeConfiguration<Scope>
    {
        public ScopeMap()
        {
            ToTable("Scope");

            HasKey(x => x.Id);
            Property(x => x.Id).HasColumnName("ScopeId");

        }
    }
```
```SQL
// Here are the tables.

create table IF NOT EXISTS Application (
	ApplicationId int not null auto_increment primary key,
	Name varchar(255) not null,
	IsDeleted bool not null default false,
	
	CreatedBy varchar(255) not null,
	CreatedOn Datetime not null,
	UpdatedBy varchar(255) not null,
	UpdatedOn DateTime not null
) ENGINE=INNODB;

create table IF NOT EXISTS AppUser (
	UserId int not null auto_increment primary key,
	Username varchar(255) not null,
	FirstName varchar(255) not null,
	LastName varchar(255) not null,
	Email varchar(255) not null,
	Title varchar(255) null,
	IsActive bool not null default false,
	
	CreatedBy varchar(255) not null,
	CreatedOn Datetime not null,
	UpdatedBy varchar(255) not null,
	UpdatedOn DateTime not null,
	
	UNIQUE KEY unique_record (Username, Email)
	
) ENGINE=INNODB;

create table IF NOT EXISTS Market (
	EnterpriseMarketId smallint not null primary key,
	Name varchar(255) not null,
	State varchar(2) not null,
	Region varchar(255) not null,
	Timezone varchar(25) not null,
	TimezoneOrder tinyint not null,
	IsActive tinyint(1) not null
) ENGINE=INNODB;

create table IF NOT EXISTS Role (
	RoleId int not null auto_increment primary key,
	Name varchar(255) not null,
	ApplicationId int not null,
	
	CreatedBy varchar(255) not null,
	CreatedOn Datetime not null,
	UpdatedBy varchar(255) not null,
	UpdatedOn DateTime not null,
	
	index app_index (ApplicationId),
	foreign key (ApplicationId) references Application(ApplicationId) on delete cascade
) ENGINE=INNODB;

create table IF NOT EXISTS Scope (
	ScopeId int not null auto_increment primary key,
	Name varchar(255) not null,
	RoleId int not null,
	Document JSON,
	
	CreatedBy varchar(255) not null,
	CreatedOn Datetime not null,
	UpdatedBy varchar(255) not null,
	UpdatedOn DateTime not null,
	
	index app_index (RoleId),
	foreign key (RoleId) references Role(RoleId) on delete cascade
) ENGINE=INNODB;

// Association tables

create table IF NOT EXISTS UserApplication (
	ApplicationId int not null,
	UserId int not null,

	index app_index (ApplicationId),
	index user_index (UserId),
	foreign key (ApplicationId) references Application(ApplicationId) on delete cascade,
	foreign key (UserId) references AppUser(UserId) on delete cascade,
	
	primary key (ApplicationId, UserId)
) ENGINE=INNODB;

create table IF NOT EXISTS UserMarket (
	EnterpriseMarketId smallint not null,
	UserId int not null,
	
	index market_index (EnterpriseMarketId),
	index user_index (UserId),
	foreign key (EnterpriseMarketId) references Market(EnterpriseMarketId) on delete cascade,
	foreign key (UserId) references AppUser(UserId) on delete cascade,
	
	primary key (EnterpriseMarketId, UserId)
) ENGINE=INNODB;

create table IF NOT EXISTS UserRole (
	RoleId int not null,
	UserId int not null,
	
	index user_index (UserId),
	index role_index (RoleId),
	foreign key (UserId) references AppUser(UserId) on delete cascade,
	foreign key (RoleId) references Role(RoleId) on delete cascade,
	
	primary key (RoleId, UserId)
) ENGINE=INNODB;

```

**Comment by rowanmiller** [comment] 2017-01-20 23:16
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

Can you also share the full stack trace of the exception.

BTW we're not just doing this to be mean 😄... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by rowanmiller** [comment] 2017-01-27 19:08
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by rowanmiller** 2017-01-27 19:08 UTC
