### ISSUE TITLE
CAST(str as Edm.String)

### ISSUE THREAD

**Issue by linqw86** [aspnet/EntityFramework6#544] opened 2018-05-22 09:16 UTC
I try to write a build in edmfunction map to **CAST(str as CHAR(100))**
`
        public class CustomFunctionConvention : IConceptualModelConvention<EdmModel>
        {
            public void Apply(EdmModel item, DbModel model)
            {
                var t = typeof(FunctionParameter);
                var constructor = t.GetConstructors(System.Reflection.BindingFlags.NonPublic| System.Reflection.BindingFlags.Instance);// (System.Reflection.BindingFlags.NonPublic, null, new Type[] { typeof(string), typeof(TypeUsage), typeof(ParameterMode), null });
                var c1 = constructor[1];
                var param = (FunctionParameter)c1.Invoke(new object[] { "strValue", TypeUsage.CreateStringTypeUsage(PrimitiveType.GetEdmPrimitiveType(PrimitiveTypeKind.String), false, true, 100), ParameterMode.In });

                var resultParam = (FunctionParameter)c1.Invoke(new object[] { "ReturnValue", TypeUsage.CreateStringTypeUsage(PrimitiveType.GetEdmPrimitiveType(PrimitiveTypeKind.String), false, true, 1000), ParameterMode.ReturnValue });

                var toFixedChar = new EdmFunctionPayload()
                {
                    CommandText = String.Format("CAST(strValue AS {0})", PrimitiveType.GetEdmPrimitiveType(PrimitiveTypeKind.String)),
                    Parameters = new[] {
                    param,
                    },
                    ReturnParameters = new[] {
                    resultParam,
                },
                    IsComposable = true
                };

                var function = EdmFunction.Create("ToFixedChar", model.ConceptualModel.EntityTypes.First().NamespaceName, DataSpace.CSpace, toFixedChar, null);
                model.ConceptualModel.AddItem(function);
            }
        }

`
When i calling it,the translated sql is `TO_NCOLB('1')` and throw the
OracleException: ORA-00932: inconsistent datatypes: expected - got NCLOB

I think it take no account into the setting of resultParam.

### Further technical details
EF version: 6.2
Database Provider: Oracle.ManagedDataAccess,Oracle.ManagedDataAccess.EntityFramework
Operating system: Win10
IDE: VS2017 15.7

**Comment by ajcvickers** [comment] 2018-07-06 17:33
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment] 2018-07-27 16:01
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2018-07-27 16:01 UTC
