### ISSUE TITLE
Update Datatbase ore than one migrations configuration type was found in the assembly

### ISSUE THREAD

**Issue by brux88** [aspnet/EntityFramework6#1315] opened 2019-09-28 07:11 UTC
i convert my app from 6.2 to 6.3 entity framework, but now show me an error:
More than one migrations configuration type was found in the assembly 'Sedna.Domain'. Specify the name of the one to use.

despite having entered the vondigurationtypename:
this is my code:
Update-Database -TargetMigration:201909111237066_Migration_4_branch -ConfigurationTypeName Sedna.Domain.Migrations_SednaContext.Configuration

but not work

**Comment by pontusd** [comment] 2019-09-30 11:48
I have the same problem and found that the parameter -ConfigurationTypeName is not passed to the underlying call to ef6.exe.
A workaround is to directly call ef6.exe --migrations-config "configurationtypename"

**Comment by bricelam** [comment] 2019-09-30 18:35
Duplicate of #1296. Fixed in the [daily builds](https://github.com/aspnet/AspNetCore/blob/master/docs/DailyBuilds.md) of 6.4

**Closed by bricelam** 2019-09-30 18:35 UTC
