### ISSUE TITLE
NullReferenceException in RelatedEnd.ExcludeEntity

### ISSUE THREAD

**Issue by DzonnyDZ** [aspnet/EntityFramework6#343] opened 2017-08-25 10:21 UTC
This issue is best described on https://stackoverflow.com/questions/27209807/cloning-entity-with-ef-6-null-reference-exception
The problem is that under some circumstances (cloned entity?) there is `NullReferenceException` with following call stack:

```
CallStack:           at System.Data.Entity.Core.Objects.DataClasses.RelatedEnd.ExcludeEntity(IEntityWrapper wrappedEntity)
   at System.Data.Entity.Core.Objects.DataClasses.EntityCollection`1.Exclude()
   at System.Data.Entity.Core.Objects.DataClasses.RelationshipManager.RemoveRelatedEntitiesFromObjectStateManager(IEntityWrapper wrappedEntity)
   at System.Data.Entity.Core.Objects.DataClasses.RelationshipManager.AddRelatedEntitiesToObjectStateManager(Boolean doAttach)
   at System.Data.Entity.Core.Objects.ObjectContext.AttachTo(String entitySetName, Object entity)
   at System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Attach(Object entity)
   at System.Data.Entity.DbSet.Attach(Object entity)
   at RFERL.EntityFramework.EntityDataAccessLayer.AttachEntities[T](T itemOrCollection) in D:\JenkinsSlave\workspace\PANGEA\common\RFERL.DbCore\EntityFramework\High-level\EntityDataAccessLayer.cs:line 627
   at RFERL.EntityFramework.EntityDataAccessLayer.AttachEntities[T](T itemOrCollection) in D:\JenkinsSlave\workspace\PANGEA\common\RFERL.DbCore\EntityFramework\High-level\EntityDataAccessLayer.cs:line 633
   at RFERL.EntityFramework.EntityDataAccessLayer.<>c__DisplayClass67_0`1.<CacheOperation>b__1() in D:\JenkinsSlave\workspace\PANGEA\common\RFERL.DbCore\EntityFramework\High-level\EntityDataAccessLayer.cs:line 571
   at RFERL.EntityFramework.EntityDataAccessLayer.CacheOperation[T](Func`1 getFromCache, Func`1 getFromDb, Action`1 storeToCache, CacheMode mode) in D:\JenkinsSlave\workspace\PANGEA\common\RFERL.DbCore\EntityFramework\High-level\EntityDataAccessLayer.cs:line 522
   at RFERL.EntityFramework.EntityDataAccessLayer.CacheOperation[T](Func`1 getCacheKey, Func`1 getFromDb, CacheMode mode, Nullable`1 cacheDuration, Func`2 preprocessItemForCache) in D:\JenkinsSlave\workspace\PANGEA\common\RFERL.DbCore\EntityFramework\High-level\EntityDataAccessLayer.cs:line 561
```

**Comment by ajcvickers** [comment] 2018-08-21 00:44
@DzonnyDZ I have not been able to reproduce this--I have tried various permutations of the code posted below. Can you post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing?
```C#
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;

namespace SixTwo
{
    public class Ticket
    {
        public virtual int TicketId { get; set; }

        public virtual ICollection<Line> Lines { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }

    public class Line
    {
        public virtual int Id { get; set; }

        public virtual int? TicketId { get; set; }
        public virtual Ticket Ticket { get; set; }

        public virtual ICollection<Serial> Serials { get; set; }
    }

    public class Payment
    {
        public virtual int Id { get; set; }

        public virtual int? TicketId { get; set; }
        public virtual Ticket Ticket { get; set; }

        public virtual PayCodeInfo PayCodeInfo { get; set; }
    }

    public class Serial
    {
        public virtual int Id { get; set; }

        public virtual int? LineId { get; set; }
        public virtual Line Line { get; set; }
    }

    public class PayCodeInfo
    {
        public virtual int Id { get; set; }

        public virtual Payment Payment { get; set; }
    }

    public class SixTwoContext : DbContext
    {
        static SixTwoContext()
        {
            Database.SetInitializer(new DropCreateDatabaseAlways<SixTwoContext>());
        }

        public SixTwoContext()
            : base(@"Server=(localdb)\mssqllocaldb;Database=SixTwo;ConnectRetryCount=0")
        {
        }

        public DbSet<Ticket> Tickets { get; set; }
        public DbSet<Line> Lines { get; set; }
        public DbSet<Payment> Payments { get; set; }
        public DbSet<Serial> Serials { get; set; }
        public DbSet<PayCodeInfo> PayCodeInfos { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Payment>().HasOptional(e => e.PayCodeInfo).WithRequired(e => e.Payment);
        }
    }

    public class Program
    {
        public static void Main()
        {
            using (var context = new SixTwoContext())
            {
                var ticket = new Ticket();
                context.PayCodeInfos.Add(new PayCodeInfo { Payment = new Payment { Ticket = ticket } });
                context.Serials.Add(new Serial{ Line = new Line { Ticket = ticket}});
                context.SaveChanges();
            }

            using (var context = new SixTwoContext())
            {
                var ticketId = 1;

                var clonedTicket = context.Tickets
                    .AsNoTracking()
                    .Include(o => o.Lines.Select(l => l.Serials))
                    .Include(o => o.Payments.Select(p => p.PayCodeInfo))
                    .SingleOrDefault(o => o.TicketId == ticketId);

                clonedTicket.TicketId = context.Tickets.Max(o => o.TicketId) + 1;

                foreach (var line in clonedTicket.Lines)
                {
                    line.TicketId = clonedTicket.TicketId;
                    foreach (var lineSerial in line.Serials)
                    {
                        lineSerial.LineId = lineSerial.Id;
                    }
                }

                foreach (var payment in clonedTicket.Payments)
                {
                    payment.TicketId = clonedTicket.TicketId;
                }

                context.Tickets.Add(clonedTicket);
                context.SaveChanges();
            }
        }
    }
}
```

**Comment by ajcvickers** [comment] 2019-03-18 22:39
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-03-18 22:39 UTC
Labels: blocked
