### ISSUE TITLE
Relationship constraints with different keys

### ISSUE THREAD

**Issue by DomCotton** [aspnet/EntityFramework6#715] opened 2019-02-20 11:37 UTC
I am trying to create a relationship between two tables in an existing database, using Code First.  The models are as follows:

```
class Order {
  [Key]
  string OrderNumber { get; set; }

  [ForeignKey("OrderNumber")]
  virtual ICollection<OrderLine> OrderLines { get; set; }
}

class OrderLine {
  [Key, Column(Order=0)]
  string OrderNumber { get; set; }
  
  [Key, Column(Order=1)]
  string LineNumber { get; set; }
}
```

I need to be able to create the relationship so that an order contains a collection of all of its corresponding lines, by a single key from a composite.

Exception message:
```
One or more validation errors were detected during model generation:

Order_OrderLines_Source_Order_OrderLines_Target: : The number of properties in the Dependent and Principal Roles in a relationship constraint must be identical.

```
Stack trace:

   at System.Data.Entity.Core.Metadata.Edm.EdmModel.Validate()
   at System.Data.Entity.DbModelBuilder.Build(DbProviderManifest providerManifest, DbProviderInfo providerInfo)
   at System.Data.Entity.DbModelBuilder.Build(DbConnection providerConnection)
   at System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext)
   at System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   at System.Data.Entity.Internal.InternalContext.Initialize()
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   at System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Any[TSource](IQueryable`1 source, Expression`1 predicate)
  

### Further technical details
EF version: 6.2.0
Database Provider: Oracle.ManagedDataAccess.EntityFramework.EFOracleProviderServices
Operating system: Windows 10 
IDE: Visual Studio 2017 15.9.4

**Comment by ajcvickers** [comment] 2019-03-21 20:20
@DomCotton I am not able to reproduce this--my test code is below. The default mapping for this is working for me with the following tables:
```sql
CREATE TABLE [dbo].[Orders] (
    [OrderNumber] [nvarchar](128) NOT NULL,
    CONSTRAINT [PK_dbo.Orders] PRIMARY KEY ([OrderNumber])
)

CREATE TABLE [dbo].[OrderLines] (
    [OrderNumber] [nvarchar](128) NOT NULL,
    [LineNumber] [nvarchar](128) NOT NULL,
    CONSTRAINT [PK_dbo.OrderLines] PRIMARY KEY ([OrderNumber], [LineNumber])
)
```

Code:
```C#
namespace SixTwo
{
    public class Order {
        [Key]
        public string OrderNumber { get; set; }

        [ForeignKey("OrderNumber")]
        public virtual ICollection<OrderLine> OrderLines { get; set; }
    }

    public class OrderLine {
        [Key, Column(Order=0)]
        public string OrderNumber { get; set; }
  
        [Key, Column(Order=1)]
        public string LineNumber { get; set; }
    }

    public class SixTwoContext : DbContext
    {
        static SixTwoContext() => Database.SetInitializer(new DropCreateDatabaseAlways<SixTwoContext>());

        public SixTwoContext()
            : base(@"Server=(localdb)\mssqllocaldb;Database=SixTwo;ConnectRetryCount=0")
        {
        }

        public DbSet<Order> Orders { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
        }
    }

    public class Program
    {
        public static void Main()
        {
            using (var context = new SixTwoContext())
            {
                context.Database.Log = Console.WriteLine;

                context.Orders.Add(new Order
                {
                    OrderNumber = "O1",
                    OrderLines = new List<OrderLine> {new OrderLine {LineNumber = "L1", OrderNumber = "O1" }}
                });

                context.SaveChanges();
            }

            using (var context = new SixTwoContext())
            {
                var order = context.Orders.Include(e => e.OrderLines);
            }
        }

    }
}
```

**Comment by DomCotton** [comment] 2019-03-22 08:18
Hi,
Thanks for your reply.  However there appears to be a difference maybe its the database driver at fault here.  Your example is against SQL Server?  Are you able to work with an Oracle database to replicate the fault?

Thanks

**Comment by ajcvickers** [comment] 2019-03-22 15:56
@DomCotton Unfortunately not. If it's an issue with the Oracle provider, then you'll need to report it to them.

**Comment by ajcvickers** [comment] 2019-06-26 19:00
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-06-26 19:00 UTC
