### ISSUE TITLE
Can Entity Property have different Column Order when it is being use a Key and as a ForeignKey?

### ISSUE THREAD

**Issue by dlipkie** [aspnet/EntityFramework6#113] opened 2016-11-21 16:40 UTC
Thanks
Daniel

**Comment by rowanmiller** [comment] 2016-11-22 20:11
Closing as a dupe of https://github.com/aspnet/EntityFramework6/issues/110 - we will follow up there

**Closed by rowanmiller** 2016-11-22 20:11 UTC

**Comment by dlipkie** [comment] 2016-11-22 20:22
110 and 113 are not dups.

110 concerns the interaction between two different entities.

113 concerns properties within a single entity

**Comment by rowanmiller** [comment] 2016-11-22 20:26
Sorry, I just meant that we'd cover all this as part of the answer to #110.

**Comment by dlipkie** [comment] 2016-11-22 20:28
Thanks for clarification ... look forward to finding out where i missed the boat on understanding this topic.
