### ISSUE TITLE
Support for Microsoft.SqlServer.Types newer versions

### ISSUE THREAD

**Issue by hamjo** [aspnet/EntityFramework6#641] opened 2018-10-04 15:22 UTC
Right now EntityFramework only supports `Microsoft.SqlServer.Types` version 10 and 11. 
When it fails to find any, the output message is 

> Spatial types and functions are not available for this provider because the assembly 'Microsoft.SqlServer.Types' version 10 or higher could not be found. 

Could EF support versions higher than 11 for `Microsoft.SqlServer.Types`?

If you do not intent to support newer versions, could you please update the message so that users don't spend hours figuring out that versions 12 or higher are not officially supported?

**Comment by ajcvickers** [comment] 2018-10-04 16:12
@hamjo Support for later versions has been added and will be included in the next release, which will probably around the middle of next year.

**Closed by ajcvickers** 2018-10-04 16:12 UTC

**Comment by bricelam** [comment] 2019-04-22 22:03
Duplicate of #244
