### ISSUE TITLE
Remove redundant EmbeddedResource configuration

### ISSUE THREAD

**Issue by Varorbc** [aspnet/EntityFramework6#1245] opened 2019-09-09 06:36 UTC
Remove redundant `EmbeddedResource `configuration

*.csproj
```csharp
  <ItemGroup>
    <EmbeddedResource Update="Migrations\****.resx">
      <DependentUpon>***.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>
```

After the migration command is executed, the redundant EmbeddedResource configuration will be added to the project file. In fact, this part is not needed, and the project system will automatically depend on it.

### Further technical details
EF version: 6.3.0-preview9-19423-04
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 16.2.4

**Comment by thomasclaudiushuber** [comment] 2019-09-09 15:07
Great finding, but this is actually only redundant from a .NET Standard or .NET Core only view. 

I think it is important to keep this in the .csproj file, because:

If you mutlitarget .NET Framework and .NET Core with a single project, you will get an error that .NET Framework doesn't find the resx file and the corresponding cs file. Actually just today I did this, and I got this error:

> Error	MSB3041	Unable to create a manifest resource name for "Migrations\201909051018233_InitialSetup.resx". Could not find a part of the path 'D:\WiredBrainCoffee.CustomerApp\WiredBrainCoffee.CustomerApp.DataAccess\Migrations\Migrations\201909051018233_InitialSetup.cs'.	WiredBrainCoffee.CustomerApp.DataAccess	C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.CSharp.CurrentVersion.targets	100		

It looks like EF duplicates the Migrations folder into Migrations\Migrations for .NET Framework when multi-targeting. It compiles if I target only .NET Framework.

This is my .csproj file:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;netstandard2.1</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.3.0-preview9-19423-04" />
  </ItemGroup>
</Project>
```

Adding this to the .csproj file solves the problem:

```
  <ItemGroup>
    <EmbeddedResource Update="Migrations\****.resx">
      <DependentUpon>***.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>
```

That's why I think I would keep it, as targeting .NET Framework and .NET Standard2.1 will be a use case for many developers I know, at least for the upcoming years before they migrated all their apps to .NET Core.

Thomas

**Comment by bricelam** [comment] 2019-09-13 18:40
Duplicate of #1234

**Closed by bricelam** 2019-09-13 18:40 UTC
