### ISSUE TITLE
Entity Framework 6 - Second level Caching Alias name

### ISSUE THREAD

**Issue by abhisheksriv** [aspnet/EntityFramework6#55] opened 2016-08-26 08:09 UTC
Hi, 

I am using Entity Framework 6 and using second level of caching of entities to improve performance. 

One of the problems we are facing is with the Alias names in the query. 

On a high load scenario, the alias name generated for a query are different which is resulting in both the queries being treated as different and it breaks the caching. 

For Eg: 
SELECT Var_251.id from user Var_251 where <<condition1>> 

The same query for the user on a high load is getting generated as 
SELECT Var_252.id from user var_252 where <<Condition1>> 

since both the queries are different, the hash of the query which is used as a key to store the result set becomes different. So data cached in the first query is not reusable in second query by the same user. 

IF we run the application with a single user the query alias name generated is always same, but the moment to move say 5+ user load, the query being generated gets different. 

So just wanted to confirm if there is a way to override this default behaviour so that it uses the same alias everytime for the query or if this is a known issue in the EF 6.

**Comment by ErikEJ** [comment] 2016-08-26 15:40
What "second levelcache" do you use?

**Comment by divega** [comment] 2016-08-26 18:21
@abhisheksriv could you provide the full query? In particular the original EF query and the SQL generated.

**Comment by divega** [comment] 2016-08-26 19:51
@abhisheksriv to add some more information, I don't know of a way you can override this behavior but at the same time I find the two snippets of SQL and the behavior described a bit surprising. Having more information about the queries could help.

**Comment by divega** [comment] 2016-08-31 19:01
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed by divega** 2016-08-31 19:01 UTC
