### ISSUE TITLE
Edmx Designer is taking too much time to load

### ISSUE THREAD

**Issue by dawoodahmad** [aspnet/EntityFramework6#236] opened 2017-03-31 06:55 UTC
EDMX Designer is taking so much time to load. Following are the details

- VS 2013
- Entity Framework 6.1.1
- Windows 7
- Database Oracle

**Comment by ajcvickers** [comment] 2017-03-31 17:08
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by dawoodahmad** [comment] 2017-03-31 17:25
@ajcvickers what other information you need? We have 118 tables all connected. We are using database first approach to generate edmx.

**Comment by ajcvickers** [comment] 2017-03-31 17:33
@dawoodahmad 
* How much time is it taking?
* Which Oracle provider are you using and what version?
* What would we need to do to reproduce this? Are you seeing it for any database with many tables, or is there something else about the database structure that makes it very slow?

**Comment by dawoodahmad** [comment] 2017-03-31 17:53
It takes more then 8 minutes to load.  Following are the oracle provider details.

- Oracle.ManagedDataAccess (4.121.2.0)
- Oracle.ManagedDataAccess.EntityFramework (6.121.2.0).

I think its due to so many tables. almost all tables are connected using foreign keys relationship.

**Comment by lajones** [comment] 2017-03-31 18:13
We had an issue last year where a model with a large number of associations had performance issues. In the end it was found that the TabTip.exe (Touch Keyboard and Handwriting Panel) process was interfering and ending that process in Task Manager solved the problem. Not sure if that is your problem but worth a try.

**Comment by ajcvickers** [comment] 2017-04-07 19:05
@dawoodahmad Did you check the suggestion from @lajones? If that doesn't help then can you send us a model we can use to attempt to reproduce the issue? You can email it to me--I am avickers at Microsoft.

**Comment by taimurahmad971** [comment] 2017-04-10 10:13
@lajones  "Touch Keyboard and Handwriting Panel" is already stopped. @ajcvickers how could we send you  schema of db?

**Comment by taimurahmad971** [comment] 2017-04-10 10:16
@ajcvickers its around 180 tables in oracle db. Please specify what is required?

**Comment by ajcvickers** [comment] 2017-04-14 19:00
@taimurahmad971 Probably we can use just the EDMX file.

**Comment by ajcvickers** [comment] 2017-04-21 18:26
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2017-04-21 18:26 UTC
