### ISSUE TITLE
EF Core commands on Nuget Package Console don't work till I clean in Batch Build

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/EntityFramework6#1218] opened 2019-09-03 17:47 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/715066/ef-core-commands-on-nuget-package-console-dont-wor.html)._

---
What steps will reproduce the problem?
1. Make changes in entities and Build
2. Run EF Core commands like Add-Migration or Update-Database

What is the expected output? What do you see instead?
Migration to have changes and Applying Migrations

Please provide any additional information below.

Only when I go to Build -&gt; Batch build -&gt; Clean all then Rebuild the EF Core commands work correctly.

VS 2019 -&gt; 16.2.3

---
#### Visual Studio Feedback System on 8/28/2019, 03:13 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 8/29/2019, 10:10 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2019-09-07 23:01
Please post a small, runnable project/solution that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-10-07 16:46
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-10-07 16:46 UTC
