### ISSUE TITLE
SET ARITHABORT in Postgres

### ISSUE THREAD

**Issue by Developer-Julian** [aspnet/EntityFramework6#1149] opened 2019-08-16 05:34 UTC
Hi everybody!
We have ASP.NET app running on IIS using EF 6.1.3 and we catched a problem with SET ARITHABORT ON and Postgres EF driver.
We spend too much time to cath this error. It is appeared about 1 time per 30-100 executions.
Error message was: 'ERROR: 42601: syntax error at or near \"ON\"'. We added a query to the log and cathed this: 'SET ARITHABORT ON; SET ARITHABORT ON; SET ARITHABORT ON; SET ARITHABORT ON; SET ARITHABORT ON; SET ARITHABORT ON; SET ARITHABORT ON; SET ARITHABORT ON; SET ARITHABORT ON; SET ARITHABORT ON; SET ARITHABORT ON; SELECT \"Extent1\".\"id\", .......'.

EF added 'SET ARITHABORT ON;' operation to the Postgres's query;
We hadn't time to finding out the reason. We added the Interceptor for the DbContext to delete 'SET ARITHABORT ON;' from query.

**Comment by kblc** [comment] 2019-08-16 05:50
I've got the same problem. And Interceptor is the solution witch we were deserve )

**Comment by divega** [comment] 2019-08-16 06:54
@roji sounds like this could be a problem with the EF6 provider for PostgreSQL. Do you know who could help?

**Comment by roji** [comment] 2019-08-27 09:03
@Developer-Julian apologies for not responding earlier.

ARITHABORT is a SQL Server option that indeed won't work on PostgreSQL. The Npgsql EF6 provider definitely doesn't add it, and AFAIK neither does Entity Framework 6. Are you sure you don't have an interceptor or some other mechanism adding this to your queries?


If not, can you please provide a runnable code sample that shows the issue happening?

**Comment by Developer-Julian** [comment] 2019-08-27 10:18
@roji 

We had no one interceptors before. And we add only one to fix the issue. We use simple mapping of tables and do not use anything else. Therefore, the sample code will not do anything, because there is a default call to DbSet. This bug is not reproduced constantly, it occurs 1 time per 100 requests, and for some reason it occurs on a specific server node. We were able to catch such a bug only because we began to log the scripts that EF generates. And we were very surprised when we discovered ARITHABORT when accessing PostgreSQL.

**Comment by roji** [comment] 2019-08-27 14:58
Do you mean to say that you have the same application running on a different server, and not encountering this issue? That is indeed very strange, and there's not much we can do about it (nobody else has ever complained about this problem). Maybe it's worth checking whether you're not using some kind of patched version of EF6 or the Npgsql provider, or just try updating them to newer versions to deploy new assemblies.

**Comment by ajcvickers** [comment] 2019-09-06 16:57
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-09-06 16:57 UTC
