### ISSUE TITLE
Memory leak with async methods and long lived cancellation tokens

### ISSUE THREAD

**Issue by tstedel** [aspnet/EntityFramework6#582] opened 2018-07-25 01:22 UTC
In this case, until the token has been disposed of, entity framework keeps a CancellationTokenRegistration object open that in turn holds sql ce resources open (I can see many Sql Ce Commands and data readers that are left in memory).

```c#
private async Task RunAsync(CancellationToken token = default)
        {
            for (var i = 0; i < 1000000; i++)
            {
                using (var ctx = new Context())
                {
                    var thing = await ctx.Things.ToListAsync(token);
                    if (thing.Any())
                    {
                        Console.WriteLine("asdfsadf");
                    }
                }
            }
        }
```

### Further technical details
EF version: 6.2
Database Provider: EntityFramework.SqlServerCe
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.5

**Comment by ajcvickers** [comment] 2019-03-18 23:08
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment] 2019-06-26 18:49
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-06-26 18:49 UTC
Labels: blocked

**Comment by tstedel** [comment] 2019-11-27 01:45
I have looked into this further, and it appears that this code, in conjunction with the recommendation that you only open 1 Sql Server Compact Edition connection open for the lifetime of your application (due mostly to the abysmal connection open time for Sql CE) is what causes the memory leak. This still seems, however, like a memory leak?

**Comment by tstedel** [comment] 2019-11-27 02:27
[Uploading EntityFrameworkSqlCeMemoryLeak.zip…]()

This reproduces the issue.

**Comment by tstedel** [comment] 2019-11-27 02:27
[EntityFrameworkSqlCeMemoryLeak.zip](https://github.com/aspnet/EntityFramework6/files/3894829/EntityFrameworkSqlCeMemoryLeak.zip)

This reproduces the issue

**Comment by tstedel** [comment] 2019-11-27 07:58
This issue doesn't happen with Entity Framework + LocalDb, must be a Sql Ce implementation issue
