### ISSUE TITLE
Language pack

### ISSUE THREAD

**Issue by Ghetti** [aspnet/EntityFramework6#1452] opened 2019-11-08 11:26 UTC
I'm not able to update 6.2 to 6.3 because i have installed "EntityFramework.it" https://www.nuget.org/packages/EntityFramework.it/6.2.0 and this is not updated to 6.3
When Language pack for 6.3 will be release?

**Comment by ajcvickers** [comment] 2019-11-08 16:49
Duplicate of #1307

**Closed by ajcvickers** 2019-11-08 16:49 UTC
