### ISSUE TITLE
EF build - target platform .net471

### ISSUE THREAD

**Issue by JBaltika** [aspnet/EntityFramework6#463] opened 2018-02-12 12:33 UTC
Hi guys,
It's  almost 4 month since MS released .NET4.7.1. It would good time to make build &  project changes to build against that framework , not with help of all binding redirects make it run net471 as many project cannot be converted to .dotnet core. 
The .NET4.7.1 is good  & solid framework release since 4.6.1. This would allow other dependent projects also create build with .NET4.7.1 .

**Comment by ajcvickers** [comment] 2018-02-12 17:00
@JBaltika Nothing special should be needed to run against .NET Framework 4.7.1. If you are hitting issues, can you post a runnable project/solution or complete code listing that demonstrates what you are seeing?

**Comment by ajcvickers** [comment] 2018-02-21 20:23
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2018-02-21 20:23 UTC
