### ISSUE TITLE
EF 6.2 + EF 6.2 beta 1 Tools + .net4.7.1 + migration edmx - error DLL System.Data and System.Data.Entity.Core

### ISSUE THREAD

**Issue by avildark** [aspnet/EntityFramework6#442] opened 2018-01-09 09:27 UTC
Hello,
My project before on .net4.6.2, EF 6.1.3 with EF 6.1.3 Tools. I try to migrate the project with nuGet on EF 6.2, Oracle Data Managed access 12.2.1100 and Oracle.ManagedDataAccess.EntityFramework 12.2.1100 in order to have best performance for my WPF application .

I install EF 6.2 beta 1 Tools(https://blogs.msdn.microsoft.com/dotnet/2017/05/23/announcing-ef-6-2-beta-1/) manually  and when i open my project, i have few problems 
 1) EDMX cannot compile with  Run Custom Tools because error CS 0246 on 
 System.Data.EntityClient error edmx want System.Data.Entity.Core.EntityClient
 System.Data.Objects error edmx want System.Data.Entity.Core.Objects
 System.Data.Objects.DataClasses error  edmx want System.Data.Entity.Core.Objects.DataClasses 
System.Data.Metadata error  edmx want System.Data.Entity.Core.Metadata 

 2) If i fix this bug by changing myself the using, it run but i have new error when i try to use executeStoreQuery:
all field EDM.Int16 generated bot OracleProvider.Number was in Error.
The best way to fix is to open EDMX with XML editor and change but when i save changes, edmx customTool run and replace all changes of System.Data.Entity.Core in System.Data.

in MSDN  System.Data.EntityClient is the good class but in 4.7.1 EntityFramework.xml ( on packages\EntityFramework.6.2.0\lib\net45 generated by Nuget, we can see in EntityFramework.xml that System.Data.EntityClient doesnt exist, but System.Data.Entity.Core.EntityClient , and its the same for all over DLL).
Can you help me please?
My Visual Studio is 2015 update 3
Thank you!

**Comment by ajcvickers** [comment] 2018-01-12 21:53
@avildark Can you please post a runnable project/solution or full code listing that will let us reproduce the behavior you are seeing?

**Comment by avildark** [comment] 2018-01-15 11:47
@ajcvickers here you can find few full code .
Galys.edmx generated with EF 6.2 and fixed manually with replace all call "System.Ddata" by "System.Data.Entity.Core" because it didn't work with "System.Data".


[Galys.Designer.cs.txt](https://github.com/aspnet/EntityFramework6/files/1631493/Galys.Designer.cs.txt)
[Galys.edmx.txt](https://github.com/aspnet/EntityFramework6/files/1631494/Galys.edmx.txt)




this bug appears when i start the WPF main windows like this:
[erreur WPF EE 6.2.txt](https://github.com/aspnet/EntityFramework6/files/1631489/erreur.WPF.EE.6.2.txt)

**Comment by ajcvickers** [comment] 2018-01-16 22:58
@avildark Without a project to repro this it will be very hard to give any detailed answer as to what is going on. However, those namespaces should never appear in a 6.1.3 or 6.2 application. If the application was using those namespaces, then it was using a version of EF prior to EF6. Mayeb you had EF 6.1.3. installed but were somehow using the legacy version of EF in the .NET Framework instead?

**Comment by ajcvickers** [comment] 2018-01-26 19:35
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2018-01-26 19:35 UTC
