### ISSUE TITLE
Entities getting sealed when using proxy generation

### ISSUE THREAD

**Issue by Daniel79WI** [aspnet/EntityFramework6#357] opened 2017-09-15 09:10 UTC
Is it necessary for the proxy instance of an entity to be sealed?

I want to create another proxy for an entity. This works fine as long as the ProxyCreationEnabled property is set to false. If this is set to true, I get a sealed proxy object, which can not be wrapped in another proxy.

**Comment by ajcvickers** [comment] 2017-09-15 17:21
@Daniel79WI It's been many years since I worked on the implementation, but at the time they were sealed by design, and I know there were some scenarios where not having exactly the proxy type would cause issues. I suspect all those issues could be fixed with appropriate changes, but I suspect the PR to do this and the testing required would not be easy.

On the other hand, just making them not sealed as an "extend at your own risk" kind of thing might be something we would consider--we will discuss and get back to you. 

(FYI, either way this is something that it is unlikely we would do directly, so it would have to come in as a community PR.)

**Comment by ajcvickers** [comment] 2017-09-15 21:26
@Daniel79WI We discussed this a bit more and we're interested in understanding the end-goal of the new proxies. Would it be something that the ability to extend proxy generation in EF would help?

**Comment by ajcvickers** [comment] 2017-09-22 18:46
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by Daniel79WI** [comment] 2017-09-23 11:05
Hi Arthur,

We are loading an object graph from the dbcontext for displaying the data on a user interface. On that, we what the user to edit some data (always a part of the data) with the possibility of accepting or undoing the changes. For this, we used a change tracking proxy, which is created from the selected part of the data to be edited.

Best regards

Daniel Schröder
Projekt Manager

Willis Towers Watson
Wettinerstraße 3 | 69189 Wiesbaden<x-apple-data-detectors://1/1>

T +49 (0) 611 794-4468<tel:+49%20611%20794-4468>
M +49 (0) 160 989 345 15<tel:+49%20160%20989%20345%2015>
F +49 (0) 611 794-254<tel:+49%20611%20794-254>

daniel.schroeder@willistowerswatson.com<mailto:daniel.schroeder@willistowerswatson.com>
willistowerswatson.com<http://www.willistowerswatson.com/de-de>

Folgen Sie Willis Towers Watson in den sozialen Medien<https://www.willistowerswatson.com/de-DE/social-media>

Am 15.09.2017 um 23:28 schrieb Arthur Vickers <notifications@github.com<mailto:notifications@github.com>>:


@Daniel79WI<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdaniel79wi&data=02%7C01%7Cdaniel.schroeder%40willistowerswatson.com%7C6257c72407e14d035bf108d4fc808208%7C76e3921f489b4b7e95479ea297add9b5%7C0%7C0%7C636411076244915560&sdata=%2F1OM9cQoDbU3Q9PfSxi0EXXNMS3pcnL4JP3F2My5hiQ%3D&reserved=0> We discussed this a bit more and we're interested in understanding the end-goal of the new proxies. Would it be something that the ability to extend proxy generation in EF would help?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faspnet%2FEntityFramework6%2Fissues%2F357%23issuecomment-329908214&data=02%7C01%7Cdaniel.schroeder%40willistowerswatson.com%7C6257c72407e14d035bf108d4fc808208%7C76e3921f489b4b7e95479ea297add9b5%7C0%7C0%7C636411076244915560&sdata=9Obx9MwWGzDBFnSpTZfE%2B9u752TpLJKjfpHY5n6Qm8I%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWQGrxubgHOwYhQ1rdjSGfeyE1uRfKFOks5siuulgaJpZM4PYsZO&data=02%7C01%7Cdaniel.schroeder%40willistowerswatson.com%7C6257c72407e14d035bf108d4fc808208%7C76e3921f489b4b7e95479ea297add9b5%7C0%7C0%7C636411076244915560&sdata=Tq%2By0pPAOPuok2Zx9t8Y1H6g%2Fvc6QJFfJ2LeHpMepFQ%3D&reserved=0>.
Towers Watson GmbH
Sitz: Frankfurt am Main
Registergericht: Amtsgericht Frankfurt, HRB 87927
Vorsitzender des Aufsichtsrats: Paul Morris
Geschäftsführer: Dr. Reiner Schwinger (Vorsitzender), Dr. Thomas Jasper, Michael Klüttgens, Dr. Michael Paulweber, Helmut L. Uder

Vertraulichkeitshinweis
Diese Nachricht enthält vertrauliche Informationen. Aufgrund der Vereinbarung mit dem Empfänger ist sie für die alleinige und ausschließliche Nutzung des genannten Empfängers bestimmt. Wenn Sie nicht der genannte Empfänger dieser Nachricht sind (oder nicht vom Empfänger autorisiert sind, diese zu empfangen), dann löschen Sie bitte diese Nachricht auf Ihrem System. Die Inhalte dieser Nachricht dürfen nicht verteilt, vervielfältigt oder sonst veröffentlicht werden.

Notice of Confidentiality
This email contains confidential material prepared for the intended addressees only and it may contain intellectual property of Towers Watson, its affiliates or a third party. This material may not be suitable for, and we accept no responsibility for, use in any context or for any purpose other than for the intended context and purpose. If you are not the intended recipient or if we did not authorize your receipt of this material, any use, distribution or copying of this material is strictly prohibited and may be unlawful. If you have received this communication in error, please return it to the original sender with the subject heading "Received in error," then delete any copies.

**Comment by ajcvickers** [comment] 2017-09-25 20:52
@Daniel79WI We discussed this again and it seems to us that:
* An extension point in EF6 to allow customization of the proxies created is reasonable and we would consider a well-written community PR for this, but it is not something the EF team has plans to implement.
* Unsealing the proxies we create would require testing and changes to the code for places where we currently rely on proxies being sealed. We might also consider a PR for this, but we think it would be more work both to implement and test fully, so the extension point seems a better way to go.

**Closed by ajcvickers** 2017-09-25 20:52 UTC
Labels: closed-question
