### ISSUE TITLE
Date data type always on encryption and stored procedures.

### ISSUE THREAD

**Issue by shapemetrics** [aspnet/EntityFramework6#1363] opened 2019-10-08 19:01 UTC
There is an error with "date" data type using stored procedures and entity framework. It does not utilize reflection to find the column's underlying SQL data type correctly with always-on encryption.

```
Exception message: SqlException
Stack trace: Operand type clash: datetime2(7) encrypted with (encryption_type = 'DETERMINISTIC', encryption_algorithm_name = 'AEAD_AES_256_CBC_HMAC_SHA_256', column_encryption_key_name = 'KeyName', column_encryption_key_database_name = 'DBName') is incompatible with date encrypted with (encryption_type = 'DETERMINISTIC', encryption_algorithm_name = 'AEAD_AES_256_CBC_HMAC_SHA_256', column_encryption_key_name = 'KeyName', column_encryption_key_database_name = 'DBName')  Incorrect parameter encryption metadata was received from the client. The error occurred during the invocation of the batch and therefore the client can refresh the parameter encryption metadata by calling sp_describe_parameter_encryption and retry.


```

### Steps to reproduce

On Model binding, setup individual entity for stored procedures. 

A field on the entity contains the following:

[Column("DateOfBirth", TypeName = "date")]
 public DateTime? DOB { get; set; }

stored procedures are correct, however, when entity framework creates the prepared to hand off to SQL with always-on encryption for the field there is an error.  As it creates the parameter as datetime2 rather than date SQL type.

```c#

```

### Further technical details
EF version: 6.3.0
Database Provider:  EntityFramework.SqlServer
Operating system: windows 10, windows 2016
IDE: vs 2017 pro

**Comment by ajcvickers** [comment] 2019-10-14 23:28
This is essentially a duplicate of #578--that is, the root cause is the same, and the workarounds are the same.

**Closed by ajcvickers** 2019-10-14 23:28 UTC
