### ISSUE TITLE
Edmx file not gererating related cs codes

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework6#760] opened 2019-04-09 21:08 UTC
From VS Feedback:

after updating the model from database and saving. the related changes are not reflecting in the file. Even if i delete the physical file its not getting generated.

Also tried through custom tool, but no luck.

awaiting for the fix soon.

**Comment by ajcvickers** [comment] 2019-04-09 21:08
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by RicardoNoerr** [comment] 2019-05-02 13:03
I'm having the same problem. I reported on https://developercommunity.visualstudio.com/content/problem/553964/entity-framework-dont-generate-code-for-new-entity.html

Seems Visual Studio 2019 don't run the template when saving the model

**Comment by lajones** [comment] 2019-05-03 19:32
Closing as dupe of #705.

**Closed by lajones** 2019-05-03 19:32 UTC
