### ISSUE TITLE
Pass decimal less than 0.1 from C# to SQL

### ISSUE THREAD

**Issue by alijamal14** [aspnet/EntityFramework6#1185] opened 2019-08-23 10:39 UTC
I can not pass decimal value less than `0.1` properly from C# to SQL
when I pass value from C# for example decimal value `0.0033M` I get `33` in SQL

``` lang-c#
db.Insert(0.0033M);//SP Called from EDMX context `db` C#
```
When I check In **SQL Profiler** I get
``` lang-sql
exec [dbo].[Insert] @Value=33 --Shouldn't it be 0.0033
```

But when I pass any value more than equal to `0.1` the value is passed properly

How to pass decimal value properly from C# to decimal of stored procedure?

---

Here is our SP it doesn't matter it is just to make things more clear actual value is what we received in Profiler that I mentioned earlier
### Steps to reproduce
``` lang-sql
CREATE PROCEDURE [dbo].[Insert]  
 @Value[decimal](18, 6) NULL
AS            
BEGIN            
        Select @Value  -- this would give `33` when passed `0.0033M` From C#      
END
```

### Further technical details
EF version: (6.0.0.0)
Database Provider: (Microsoft.EntityFramework.SqlServer)
Operating system: Windows 10
IDE: (Visual Studio 2019 16.2.3)

**Comment by ajcvickers** [comment] 2019-08-23 14:46
@alijamal14 Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-09-06 16:58
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-09-06 16:58 UTC
