### ISSUE TITLE
No documentation on ef6.exe

### ISSUE THREAD

**Issue by PatrickBig** [aspnet/EntityFramework6#1365] opened 2019-10-09 11:55 UTC
After updating to EF6.3 our build process broke for migrations due to migrate.exe being replaced with ef6.exe

I am unable to locate documentation for ef6.exe on how to apply migrations

### Further technical details
EF version: 6.3.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows Server 2014
IDE: Visual Studio 2019 15.6

**Comment by bricelam** [comment] 2019-10-09 15:59
Duplicate of https://github.com/aspnet/EntityFramework.Docs/issues/1740

If you execute `Update-Database -Verbose` inside Package Manager Console, it will show you the call it uses to `ef.exe` to apply migrations.

**Comment by ajcvickers** [comment] 2019-10-09 19:53
@bricelam Does `migrate.exe` still exist for net40/net45 targets?

**Comment by bricelam** [comment] 2019-10-09 20:52
No, but you might be able to use the 6.2 version of migrate.exe with assemblies compiled against EF 6.3

**Comment by bricelam** [comment] 2019-10-09 20:54
Also worth noting that ef6.exe also has decent `--help` built in.

**Closed** 2019-10-11 21:52 UTC
Labels: closed-duplicate

**Comment by arfmach** [comment] 2020-06-19 20:53
@bricelam
> 
> 
> Also worth noting that ef6.exe also has decent `--help` built in.

Do you consider this a decent help?
```
--data-dir <PATH>                The data directory.
```

**Comment by bricelam** [comment] 2020-06-22 16:04
@arfmach Some providers uses that value to expand the `|DataDirectory|` substitution string in connection strings. Some providers use it as the root directory for relative paths. Some providers don't use it at all.
