### ISSUE TITLE
cannot change foreignkey value of added items, before call save method

### ISSUE THREAD

**Issue by ehsangfl** [aspnet/EntityFramework6#587] opened 2018-08-04 11:02 UTC
Hi dear
I constructed some entities. each item have a foreignkey that it setted on constructor of entity and then add it to context.
after some process and before savechanges call, foreignkey of some entities changed to another value.
pay attention that current entity state is added.
then I call savechanges method.
in debug mode, entity saved by new foreignkey value. but on publish, foreignkey saved by original value!!!!
I write some code on setter of foreignkey property for logging purpose by StackTrace class.
entity framework return foreignkey value back to originalValues (or constructed values) and stack trace of rollback is :
1- foreignkey property setter
2- SnapshotChangeTrackingStrategy.SetCurrentValue
3- EntityReference.UpdateForeignKeyValues
4- EntityEntry.FixupForeignKeysByReference
5- EntityEntry.FixupForeignKeysByReference
6- ObjectStateManager.FixupKey
7- EntityEntry.AcceptChanges
.........
it happens on IIS, this means that I test it on wpf project and every thing is ok. 
I emphasize, it happens on IIS, when it is not on debugging mode.

Now, I had to remove entity from context, and add it again to protect new foreignkey value

**Comment by ajcvickers** [comment] 2018-08-05 22:01
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment] 2018-08-16 15:43
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2018-08-16 15:43 UTC
