### ISSUE TITLE
Configuring a Required-to-Optional Relationship (One-to–Zero-or-One)

### ISSUE THREAD

**Issue by NeeleshkumarB** [aspnet/EntityFramework6#857] opened 2019-05-20 08:48 UTC
Describe what is not working as expected.

```C@
// Map one-to-zero or one relationship
modelBuilder.Entity<OfficeAssignment>()
    .HasRequired(t => t.Instructor)
    .WithOptional(t => t.OfficeAssignment);
```
In the above code snippet, Instructor Type doesn't have a reference to OfficeAssignment Type. It is ambiguous. 

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF version: (found in project.csproj or packages.config)
Database Provider: (e.g. EntityFramework.SqlServer)
Operating system: (e.g. Windows 10) 
IDE: (e.g. Visual Studio 2017 15.6)

**Comment by NeeleshkumarB** [comment] 2019-05-20 08:55
Model used generated by Database script given in https://docs.microsoft.com/en-us/ef/ef6/resources/school-database doesn't contain the definition. My mistake.

**Comment by NeeleshkumarB** [comment] 2019-05-20 09:00
Model Instructor Type doesn't have a reference to OfficeAssignment Type

**Comment by NeeleshkumarB** [comment] 2019-05-20 09:00
Model Instructor Type doesn't have a reference to OfficeAssignment Type

**Comment by ajcvickers** [comment] 2019-06-26 15:30
Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-08-06 18:14
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-08-06 18:14 UTC
