### ISSUE TITLE
Internal .NET Framework Data Provider error 1004, 0, CQT VarRef could not be resolved in the variable scope stack.

### ISSUE THREAD

**Issue by springy76** [aspnet/EntityFramework6#118] opened 2016-11-30 11:59 UTC
I have a standalone server application which uses one code-first EF model against multiple databases (=different connection strings).

On startup the server connects to all databases multithreaded in parallel and executes multiple initialization queries. Most of the time everything works without exceptions, but sometimes one or more (or all) connections throw this 1004 exception (see subject and below). It may affect any random query and the callstack is always the same. If I re-execute the the very same method at a later time within the very same process then it will succeed.

It is always the same:
Outer exception [System.Data.Entity.Core.EntityCommandCompilationException]:
"An error occurred while preparing the command definition. See the inner exception for details."
Inner exception [System.InvalidOperationException]:
"Internal .NET Framework Data Provider error 1004, 0, CQT VarRef could not be resolved in the variable scope stack."

Callstack of the outer exception:
```
   bei System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition..ctor(DbProviderFactory storeProviderFactory, DbCommandTree commandTree, DbInterceptionContext interceptionContext, IDbDependencyResolver resolver, BridgeDataReaderFactory bridgeDataReaderFactory, ColumnMapFactory columnMapFactory)
   bei System.Data.Entity.Core.EntityClient.Internal.EntityProviderServices.CreateDbCommandDefinition(DbProviderManifest providerManifest, DbCommandTree commandTree, DbInterceptionContext interceptionContext)
   bei System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.CreateCommandDefinition(ObjectContext context, DbQueryCommandTree tree)
   bei System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.Prepare(ObjectContext context, DbQueryCommandTree tree, Type elementType, MergeOption mergeOption, Boolean streaming, Span span, IEnumerable`1 compiledQueryParameters, AliasGenerator aliasGenerator)
   bei System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   bei System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
   bei System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   bei System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   bei System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   bei System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   bei System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

Callstack of the inner exception:
```
   bei System.Data.Entity.Core.Query.PlanCompiler.ITreeGenerator.ResolveScope(DbVariableReferenceExpression e)
   bei System.Data.Entity.Core.Query.PlanCompiler.ITreeGenerator.Visit(DbVariableReferenceExpression e)
   bei System.Data.Entity.Core.Query.PlanCompiler.ITreeGenerator.Visit(DbPropertyExpression e)
   bei System.Data.Entity.Core.Query.PlanCompiler.ITreeGenerator.Visit(DbNewInstanceExpression e)
   bei System.Data.Entity.Core.Query.PlanCompiler.ITreeGenerator.VisitExprAsScalar(DbExpression expr)
   bei System.Data.Entity.Core.Query.PlanCompiler.ITreeGenerator.Visit(DbRefExpression e)
   bei System.Data.Entity.Core.Query.PlanCompiler.ITreeGenerator.GenerateDiscriminatedProject(DbProjectExpression e)
   bei System.Data.Entity.Core.Query.PlanCompiler.ITreeGenerator..ctor(DbQueryCommandTree ctree, DiscriminatorMap discriminatorMap)
   bei System.Data.Entity.Core.Mapping.ViewGeneration.GeneratedView.GetInternalTree(Command targetIqtCommand)
   bei System.Data.Entity.Core.Query.PlanCompiler.PreProcessor.ExpandView(ScanTableOp scanTableOp, IsOfOp& typeFilter)
   bei System.Data.Entity.Core.Query.PlanCompiler.PreProcessor.ProcessScanTable(Node scanTableNode, ScanTableOp scanTableOp, IsOfOp& typeFilter)
   bei System.Data.Entity.Core.Query.PlanCompiler.PreProcessor.Visit(ScanTableOp op, Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.SubqueryTrackingVisitor.VisitChildren(Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.SubqueryTrackingVisitor.VisitRelOpDefault(RelOp op, Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.PreProcessor.Visit(FilterOp op, Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.SubqueryTrackingVisitor.VisitChildren(Node n)
   bei System.Data.Entity.Core.Query.InternalTrees.BasicOpVisitorOfNode.VisitDefault(Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.SubqueryTrackingVisitor.VisitChildren(Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.PreProcessor.VisitScalarOpDefault(ScalarOp op, Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.PreProcessor.VisitNavPropertyOp(PropertyOp op, Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.PreProcessor.Visit(PropertyOp op, Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.SubqueryTrackingVisitor.VisitChildren(Node n)
   bei System.Data.Entity.Core.Query.InternalTrees.BasicOpVisitorOfNode.VisitDefault(Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.SubqueryTrackingVisitor.VisitChildren(Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.SubqueryTrackingVisitor.Visit(UnnestOp op, Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.SubqueryTrackingVisitor.VisitChildren(Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.SubqueryTrackingVisitor.VisitRelOpDefault(RelOp op, Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.PreProcessor.Visit(ProjectOp op, Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.SubqueryTrackingVisitor.VisitChildren(Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.PreProcessor.VisitScalarOpDefault(ScalarOp op, Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.PreProcessor.Visit(ExistsOp op, Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.SubqueryTrackingVisitor.VisitChildren(Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.PreProcessor.VisitScalarOpDefault(ScalarOp op, Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.PreProcessor.Visit(ConditionalOp op, Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.SubqueryTrackingVisitor.VisitChildren(Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.PreProcessor.VisitScalarOpDefault(ScalarOp op, Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.PreProcessor.Visit(ConditionalOp op, Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.SubqueryTrackingVisitor.VisitChildren(Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.PreProcessor.VisitScalarOpDefault(ScalarOp op, Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.PreProcessor.Visit(ConditionalOp op, Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.SubqueryTrackingVisitor.VisitChildren(Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.PreProcessor.VisitScalarOpDefault(ScalarOp op, Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.PreProcessor.Visit(ConditionalOp op, Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.SubqueryTrackingVisitor.VisitChildren(Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.PreProcessor.VisitScalarOpDefault(ScalarOp op, Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.PreProcessor.Visit(ConditionalOp op, Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.SubqueryTrackingVisitor.VisitChildren(Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.SubqueryTrackingVisitor.VisitRelOpDefault(RelOp op, Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.PreProcessor.Visit(FilterOp op, Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.SubqueryTrackingVisitor.VisitChildren(Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.SubqueryTrackingVisitor.VisitRelOpDefault(RelOp op, Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.PreProcessor.Visit(ProjectOp op, Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.SubqueryTrackingVisitor.VisitChildren(Node n)
   bei System.Data.Entity.Core.Query.InternalTrees.BasicOpVisitorOfNode.VisitDefault(Node n)
   bei System.Data.Entity.Core.Query.PlanCompiler.PreProcessor.Process(Dictionary`2& tvfResultKeys)
   bei System.Data.Entity.Core.Query.PlanCompiler.PreProcessor.Process(PlanCompiler planCompilerState, StructuredTypeInfo& typeInfo, Dictionary`2& tvfResultKeys)
   bei System.Data.Entity.Core.Query.PlanCompiler.PlanCompiler.Compile(List`1& providerCommands, ColumnMap& resultColumnMap, Int32& columnCount, Set`1& entitySets)
   bei System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition..ctor(DbProviderFactory storeProviderFactory, DbCommandTree commandTree, DbInterceptionContext interceptionContext, IDbDependencyResolver resolver, BridgeDataReaderFactory bridgeDataReaderFactory, ColumnMapFactory columnMapFactory)
```

Provider is System.Data.SQLite (in different versions because I'm seeing this error for many months now).

**Comment by rowanmiller** [comment] 2016-12-07 17:39
We just want to double check that you are using a different context instance on each thread? From your description, it sounds like you are, but just wanted to rule that out as the issue (since that is not a supported scenario).

Could you share the initialization code? We suspect this may be a threading/locking issue in the query cache.

**Comment by springy76** [comment] 2016-12-08 08:33
Thanx for catching up!

All context instances are created as short living units of work and disposed as soon as possible. Even the connections are not shared between contexts.
In fact no piece of code is allowed to create new connections but every DB operation uses a global method which always performs these steps:

1. await `connectionPool.DequeueAsync` [Nito.AsyncEx.AsyncProducerConsumerQueue]
2. create context instance using connection retrieved from pool
3. one time "initialize" if not successful yet (updating schema if needed, building dictionaries, performing integrity tests, retrieving statistics)
4. execute lambda (Func<MyDbContext, T>) / await lambda (Func<MyDbContext, Task<T>>)
5. dispose context instace
6. give back connection to pool
7. return T

The native EF db initializer does nothing since SQLite does not support migrations etc. The custom initializer in step 3 is a (variable) lengthy mix of `context.DbSet<T>` queries and `context.Database.ExecuteSql` calls which cannot be posted here.

I have seen the 1004 exception in both step 3 and 4; repeating the failed call (triggered by a REST call) at a later time always seems to work.

**Comment by springy76** [comment] 2016-12-09 08:58
Yesterday I got the error while debugger was attached so I was able to dump the callstacks of all threads which contained EF.DLL, attached below.


[EF Data Provider error 1004, 0, CQT VarRef could not be resolved in the variable scope stack.txt](https://github.com/aspnet/EntityFramework6/files/641626/EF.Data.Provider.error.1004.0.CQT.VarRef.could.not.be.resolved.in.the.variable.scope.stack.txt)

**Comment by springy76** [comment] 2016-12-22 11:16
and even more randomly (for the exactly same startup sequence): "Process is terminated due to StackOverflowException" in a deep System.Data.Entity.Core.Query.InternalTrees / System.Data.Entity.Core.Query.PlanCompiler flip-flop.

**Comment by springy76** [comment] 2016-12-22 11:18
I could again attach a multi-thread-callstack-snapshot; but I have the feeling no one cares=reads.

**Comment by rowanmiller** [comment] 2017-01-20 23:15
We're going to dig into this more in the 6.3.0 release. We suspect it is a threading issue around a new query being added to the query cache. To that end, one workaround may be to run the initialization logic on one of the databases first, and then do the rest in parallel.

**Comment by ajcvickers** [comment] 2018-08-17 18:59
@springy76 Sorry for the extended delay on this. I have been attempting to reproduce this, but so far have been unsuccessful. I suspect that it may be dependent on the model/query that is being executed. Would it be possible to create a simplified runnable/project solution that demonstrates the behavior you are seeing?

**Comment by ajcvickers** [comment] 2019-03-18 22:19
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-03-18 22:19 UTC
Labels: blocked
