### ISSUE TITLE
EF 6.2 tooling in VS 15.7 breaks SQLite EDMX generation

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework6#535] opened 2018-05-11 07:21 UTC
2 of my users have seen issues with 15.7 - am I correct that the 15.7 release finally contains the EF 6.2 tooling?

See detailed repro steps here: https://github.com/ErikEJ/SqlCeToolbox/issues/710

### Further technical details
EF version: EF 6
Database Provider: SQLite
IDE: Visual Studio 2017 15.7

**Comment by divega** [comment] 2018-05-11 11:48
Yes @ErickEJ, that is correct.

**Comment by divega** [comment] 2018-05-11 12:06
@lajones, @ajcvickers it seems that the call to [GetProviderInvarianName](https://github.com/aspnet/EntityFramework6/blame/master/src/EFTools/EntityDesignerVersioningFacade/ReverseEngineerDb/SchemaDiscovery/EntityStoreSchemaGeneratorDatabaseSchemaLoader.cs#L44) we introduced as one of the improvements throws for SQL CE, at least in some cases. Perhaps this is due to the provider being configured for the application but not for VS?

**Comment by ErikEJ** [comment] 2018-05-11 12:11
It is for SQLite, have not tested with SQL CE, but I will

**Comment by divega** [comment] 2018-05-11 12:31
Thanks for clarifying. My brain’s lookup tables contain some stale entries :smile:

Perhaps the connection.GetProviderInvarianName() extension method operates on EF configuration. I think we have another version of the method on DbPrividerFactoy. Not sure if it has the same issue.

**Comment by ErikEJ** [comment] 2018-05-11 12:55
Just tested with SQLCE, and it is working

**Comment by ajcvickers** [comment] 2018-05-11 16:43
Assigning this to @lajones. I think we can be more defensive in calling `connection.GetProviderInvarianName()` and if it throws, then assume that it's not SQL Server. We may want to do a 6.2.1 patch for this.

**Comment by ErikEJ** [comment] 2018-05-11 16:47
Any suggestions for workarounds?

**Comment by lajones** [comment] 2018-05-11 17:48
Agreed on the defensive calling. But for now it looks as though it's having problems with reading the something in the `<system.data><DbProviderFactories>` section of the `app.config`. Or maybe it's setting up it's cache incorrectly. Are the `<remove>` entries necessary? Can they be removed, or moved so that all `<remove>` entries are before all the `<add>` ones? I wonder if somehow removing `System.Data.SQLite` is affecting `System.Data.SQLite.EF6` as well?

**Comment by ajcvickers** [comment] 2018-05-11 19:30
Diego pointed out that this is in the designer code, which isn't in 6.2, so changing the milestone to reflect that. Once we have a fix we should ask Barry which VS branch to target with it.

@lajones Those are some valid questions, but given that we are only using this to detect SQL Server, then I think we can just swallow any exceptions since we know that SQL Server, when configured correctly, will work and anything else doesn't really matter.

**Comment by lajones** [comment] 2018-05-11 20:39
@ajcvickers Agreed. My suggestions are just for what customers can try to workaround this problem before we get a fix out to swallow the exceptions. Note: I don't know if the suggestions above will work but it's worth a try.

**Comment by divega** [comment] 2018-05-11 21:19
I agree that the minimal solution would be to catch and ignore the exception, because we are only trying to detect SQL Server, which is usually registered in machine.config.

I my suspicion is correct, this is happening because the SQLite provider is registered in the application's config and not available to the designer code that is running inside the VS process. Then a possible workaround would be to put the registration of the provider in machine.config or in devenv.exe.config.

**Comment by ErikEJ** [comment] 2018-05-12 10:59
I tested and documented the workaround here: I have described the workaround using 15.7 on the WIKI page here: https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider

**Comment by Chris-Dickerson** [comment] 2018-05-13 13:37
Erik - tried the workaround, now I cannot get past the first step of the "Entity Data Model Wizard" (click Next it just vanishes).

Attaching the error I was receiving before the workaround.
[ef-sqlite-exception.txt](https://github.com/aspnet/EntityFramework6/files/1998498/ef-sqlite-exception.txt)

**Comment by ErikEJ** [comment] 2018-05-13 14:28
Sounds like you did something wrong with your machine.config modification - did you double check all the wiki instructions? Or share your machine.config file...

**Comment by Chris-Dickerson** [comment] 2018-05-13 16:09
I copied machine.config.default to machine.config and the wizard still vanishes... and yes, I double-checked everything. I tested the default machine.config with and without the DbProviderFactories section... wizard still crashes. Does this dialog report crashes anywhere?

**Comment by ErikEJ** [comment] 2018-05-13 17:05
The SQLite provider is not properly installed, check if the SQLite provider is in GAC, as described in the wiki article

**Comment by Chris-Dickerson** [comment] 2018-05-13 17:41
You are correct, I looked at your about and it says it's not in the GAC... not sure how that happened, but I reinstalled and it's there now.

Although, when I add your suggested workaround into the machine.config, it blows Visual Studio up. If I click past this error, the theme never loads (Dark) and Visual Studio thinks it's not registered... but, if copy the default machine.config back and then run Visual Studio... everything is fine.

The error:
---------------------------
Microsoft Visual Studio
---------------------------
The 'CreateLayoutWizardPackage' package did not load correctly.

The problem may have been caused by a configuration change or by the installation of another extension. You can get more information by examining the file 'C:\Users\chris.dickerson\AppData\Roaming\Microsoft\VisualStudio\15.0_22f7eb32\ActivityLog.xml'.
Restarting Visual Studio could help resolve this issue.

Continue to show this error message?

**Comment by ErikEJ** [comment] 2018-05-13 17:46
If you do not share your modified machine.config, it  is impossible for me to give you any advice

**Comment by Chris-Dickerson** [comment] 2018-05-13 17:54
[machine.config.txt](https://github.com/aspnet/EntityFramework6/files/1998760/machine.config.txt)

**Comment by ErikEJ** [comment] 2018-05-13 18:17
@Chris-Dickerson Did you read the wiki article? " You can **add** the following entry" - meaning both sqlite machine.config entries must be present, the first one will be added by the SQLite Tools installation? Did you install them?

**Comment by ErikEJ** [comment] 2018-05-13 18:26
Then something went wrong during install, or you gave me the wrong machine.config file

**Comment by Chris-Dickerson** [comment] 2018-05-13 18:29
I have everything as described by your page, I can generate the framework.  The app.config configuration on your instruction page doesn't work for me, I receive an error. But If I put it back to the way I had it previously, it works.

What makes it work is adding back:

provider:
<provider invariantName="System.Data.SQLite" type="System.Data.SQLite.EF6.SQLiteProviderServices, System.Data.SQLite.EF6" />

And to the factories:
<add name="SQLite Data Provider" invariant="System.Data.SQLite" description=".NET Framework Data Provider for SQLite" type="System.Data.SQLite.SQLiteFactory, System.Data.SQLite" />

**Comment by ErikEJ** [comment] 2018-05-13 18:37
Feel free to share an app.config file that works for you, and I will try it out

**Comment by Chris-Dickerson** [comment] 2018-05-13 18:39
[App.config.txt](https://github.com/aspnet/EntityFramework6/files/1998783/App.config.txt)

**Comment by epigramx** [comment] 2018-05-14 11:53
Workaround doesn't work here either; and it's a regular installation of VS updated to latest stable.

**Comment by epigramx** [comment] 2018-05-14 12:10
There is indeed some peculiar uninstallation of the provider out of nowhere (I had installed it minutes before and I had confirmed on the help window that it was installed so there was no way it was not installed). 

In my case I can't seem to be able to install it successfully (again) after simply following the wiki again..

**Comment by ErikEJ** [comment] 2018-05-14 19:29
@ajcvickers You are welcome, I brought it on myself by adding the DDEX provider to VS 2017 😢

**Comment by ErikEJ** [comment] 2018-06-07 13:31
If you can share a project and your machine.config, I can have a look

**Comment by dcppat** [comment] 2018-06-07 14:08
Erik,

Please, find attached a basic WPF project containing the specific package references and as well the machine.config file
[WpfApp2017324.zip](https://github.com/aspnet/EntityFramework6/files/2080749/WpfApp2017324.zip)


Thank you in advance

**Comment by lajones** [comment] 2018-06-08 21:07
Fix will appear in internal VS builds tonight. Will be publicly available in 15.8 Preview 4.

**Comment by ErikEJ** [comment] 2018-06-09 08:07
@dcppat I am also not able to make your project work, you will have to wait for VS 2017 15.8 preview 4 or generate the code in VS 2015

**Comment by dcppat** [comment] 2018-06-11 12:46
@lajones and @ErikEJ,

Thank you for your help. Tell me, please, do we know what would be the official release date?

**Comment by lajones** [comment] 2018-06-11 18:21
@dcppat Sorry, we aren't able to publicly announce the date. But I'll post back here when it's available.

**Comment by lajones** [comment] 2018-07-11 16:01
@dcppat 15.8 Preview 4 is now publicly available.

**Comment by krunalc** [comment] 2018-07-27 17:39
@ErikEJ Have you (or any one else) have tried 15.8 preview 4 version and verify that this issue has finally been resolved?

**Comment by bgvsan** [comment] 2018-07-30 10:36
i have installed the 15.8.5 preview, still not able to produce an edmx

**Comment by rserit** [comment] 2018-07-30 11:18
@bgvsan I'm using Dapper with SQLite. It took a lot of time with EF.

**Comment by ErikEJ** [comment] 2018-07-30 11:31
@bgvsan What error do you get?

**Comment by bgvsan** [comment] 2018-07-30 11:37
<img width="412" alt="schermata 2018-07-30 alle 13 34 17" src="https://user-images.githubusercontent.com/4590043/43395268-c24c5d68-93fd-11e8-954e-7e81c7e9bc3a.png">

**Comment by ErikEJ** [comment] 2018-07-30 11:40
@lajones Are you able to verify the fix?

**Comment by divega** [comment] 2018-07-30 22:54
@bgvsan can you please describe the exact repro steps to get this dialog? We suspect we could be looking at a different bug, or even some side effect of the workaround.

In the original bug report there was a different messages and a stack trace in the output window. Can you please compare what you are seeing with https://github.com/ErikEJ/SqlCeToolbox/issues/710#issue-322025452?

**Comment by bgvsan** [comment] 2018-08-01 07:33
ok I created a new project and seems edmx working with vs 15.8.5 preview, probably there is something into my old project I have to figure out.

**Comment by bruceburge** [comment] 2018-08-01 21:05
Is there an ETA on when the this code fix present in 15.8.5 will be rolled out as a stable update?

**Comment by ErikEJ** [comment] 2018-08-01 21:07
Around .NET Conf maybe?

**Closed** 2018-08-16 15:47 UTC
Labels: closed-fixed, type-bug

**Comment by dalabe** [comment] 2018-09-11 22:30
@ErikEJ I receive an old project in EF 5.0 and I am using VS 15.8.2; I try to upgrade the EF but fails, and I keep failing, any suggestion?

**Comment by ErikEJ** [comment] 2018-09-12 06:30
@dalabe Please post an issue with actionable repro steps and error messages / stack dumps
