### ISSUE TITLE
Code First migration creates table and throws already exists

### ISSUE THREAD

**Issue by amythn04** [aspnet/EntityFramework6#699] opened 2019-01-22 19:26 UTC
We've made changes to code first context strategy with Azure Mobile Server API to work with multiple database instances each acting as a tenant. You can read below what we've done to context and configuration.cs hoping we'll achieve it but the problem is that when an endpoint on the api's `TableController` is accessed and the migrations are run at run time, we see an exception that says the migration we're applying already exists which in fact was created and then it throws exception describing it already exists.

```
Exception message: Column names in each table must be unique. Column name 'LeadType' in table 'dbo.Customers' is specified more than once.
Stack trace:   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<NonQuery>b__0(DbCommand t, DbCommandInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteNonQuery()
   at System.Data.Entity.Migrations.DbMigrator.ExecuteSql(MigrationStatement migrationStatement, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinTransaction(IEnumerable`1 migrationStatements, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinNewTransaction(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection)
   at System.Data.Entity.Migrations.DbMigrator.<>c__DisplayClass30.<ExecuteStatements>b__2e()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute(Action operation)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatements(IEnumerable`1 migrationStatements, DbTransaction existingTransaction)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatements(IEnumerable`1 migrationStatements)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteOperations(String migrationId, VersionedModel targetModel, IEnumerable`1 operations, IEnumerable`1 systemOperations, Boolean downgrading, Boolean auto)
   at System.Data.Entity.Migrations.DbMigrator.AutoMigrate(String migrationId, VersionedModel sourceModel, VersionedModel targetModel, Boolean downgrading)
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
   at System.Data.Entity.Migrations.DbMigrator.<>c__DisplayClassc.<Update>b__b()
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   at System.Data.Entity.MigrateDatabaseToLatestVersion`2.InitializeDatabase(TContext context)
   at System.Data.Entity.Internal.InternalContext.<>c__DisplayClassf`1.<CreateInitializationAction>b__e()
   at System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   at System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
   at System.Data.Entity.Internal.LazyInternalContext.<InitializeDatabase>b__4(InternalContext c)
   at System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabase()
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   at System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
   at AuthController.saveUserToken(Int32 userId, String accessToken, TenantDataCtx _dbContext) in C:\Users\Administrator\Source\Repos\app-api\Mobile.Api\Controllers\AuthController.cs:line 100
```

### Tried to reproduce by
I have created a "AzureMobileApi" from template and made the same changes as our main API. The template comes with a "ToDoItem" entity data object. I've then made these changes to achieve multi tenancy:

```c#
In ToDoItemController:

		protected override void Initialize(HttpControllerContext controllerContext)
		{
			base.Initialize(controllerContext);
			var connectionStringBuilder = new System.Data.SqlClient.SqlConnectionStringBuilder();
			connectionStringBuilder.DataSource = "Server";
			connectionStringBuilder.InitialCatalog = "T1";
			connectionStringBuilder.UserID = "user id";
			connectionStringBuilder.Password = "password";
			var connectionString = connectionStringBuilder.ToString();

			var context = new MobileServiceContext(connectionString);
			DomainManager = new EntityDomainManager<TodoItem>(context, Request);
		}
               
               //Used for migrations using Add-Migration only
		public MobileServiceContext() : base("MS_TableConnectionString")
		{
		}

		public MobileServiceContext(string connectionString) : base(connectionString)
		{
			var migrationConfiguration = new Configuration();
			Database.SetInitializer(new MigrateDatabaseToLatestVersion<MobileServiceContext, Configuration>(true, migrationConfiguration));
		}

Testing this in a unit test by calling contextObject.ToDoItems.ToList();

```
Created the DB, Table and added migrations to the history table. The same doesn't work on the actual project and fails after creating the db from scratch, adding all the migrations up to date and then throws exception as mentioned above.

### Further technical details
EF version: 6
Database Provider: (EntityFramework.SqlServer)
Operating system: (e.g. Windows 10) 
IDE: (e.g. Visual Studio 2017 15.6)

**Comment by ajcvickers** [comment] 2019-03-21 19:57
@amythn04 The exception looks like the same database might be being migrated concurrently. How do you ensure that only one machine/process/thread is attempting to migrate any given database?

**Comment by amythn04** [comment] 2019-03-22 04:38
@ajcvickers would you please shed some light on how you figured there's more than one `machine/process/thread` attempting to migrate the db?

To answer your question: How do you ensure that only one machine/process/thread is attempting to migrate any given database?
We currently don't because we didn't consider that would be something we have to ensure. We'll come up with a strategy to do this which shouldn't be too difficult in our scenario. This, however, may not be the current problem source because we've only recently released to production and this was happening in UAT where there aren't those many users to truly have a concurrent db update on a single tenant.

With regards to the actual problem itself [when it occurred], we have fixed the issue in that specific case by deleting the migration entry for that specific change and dropped the columns that were causing the issue. When we ran again, we were able to get the migrations applied and the api was fine. Although the multi-tenant strategy we have implemented using EF6 code first provides a lot of operational ease, the fact that this may happen when we have large number of users does haunt us.

I would really love to find out what it actually causing this issue.

**Comment by ajcvickers** [comment] 2019-03-22 15:55
@amythn04 It's not that I figured that out. But attempting to create the same column twice is something that could happen if this was the case, and migrating from code on first use is a very common way to get into this situation, which is why its not recommended for most situations.

Beyond this, I don't know what might be causing this. We're likely going to need to be able to reproduce what you are seeing to be able to investigate fully.

**Comment by ajcvickers** [comment] 2019-06-26 19:00
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-06-26 19:00 UTC
