### ISSUE TITLE
DbContext with Async queries

### ISSUE THREAD

**Issue by romil-zealous** [aspnet/EntityFramework6#303] opened 2017-06-20 08:26 UTC
Hello,

EF: 6.1.3

When I use any async methods such as .ToListAsync(), .FirstOrDefaultAsync() etc, my query execution freezes and it never returns anything. If I use synchronous methods such ash .ToList() on same DbContext, then I get the results which is expected.
I am not able to understand what is the issue with async methods. Please help.

Regards,
Romil

**Comment by sjh37** [comment] 2017-06-20 09:27
Are you using the **await** keyword?

```c#
var engineers = await _db.Engineers
    .Where(x => x.Forename == forename && x.Surname == surname)
    .ToListAsync();
```

**Comment by romil-zealous** [comment] 2017-06-20 11:27
Yes ! I am using async and await both the keywords. But not sure why the execution stuck while calling .ToListAsync() method. 

I am using Unit Of Work + Repository Pattern where my dbContext is shared to all repositories from UoW.

**Comment by sjh37** [comment] 2017-06-20 14:45
Is there a LOT of data to come back?
i.e. how long do you think it should take?
Is there a missing index on the database which would speed up the query?

Try adding .Take(1), to see if it returns 1 row of data quickly.

**Comment by sjh37** [comment] 2017-06-20 15:05
Is your project using .Net Framework 4.5 or later?
Async was only introduced in 4.5 onwards.

**Comment by jnm2** [comment] 2017-06-20 20:39
@romil-zealous does yout execution get stuck the same way if you replace the awaiting statement with this?

```c#
await Task.Delay(3000);
```

**Comment by romil-zealous** [comment] 2017-06-21 04:12
@sjh37 I am using .NET Framework 4.6.2

**Comment by ajcvickers** [comment] 2017-06-21 16:15
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by CADbloke** [comment] 2017-06-25 10:53
@romil-zealous does this help?: https://stackoverflow.com/a/22017717/492

**Comment by ajcvickers** [comment] 2017-06-30 16:14
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2017-06-30 16:14 UTC

**Comment by westfin** [comment] 2020-08-05 11:22
Hi, I have same issue with .net framework 4.5.0. I use mysql provider. ToListAsync query blocked caller thread in console app.
Then I replaced ToListAsync task to Task.Delay and it's didn't block caller.

MySql EF 8.0.12

**Comment by westfin** [comment] 2020-08-05 13:58
Hi, I have the same issue with I use mysql provider. ToListAsync query blocked caller thread in console app.
Then I replaced ToListAsync task to Task.Delay and it's didn't block caller.

MySql EF 8.0.12
EF 6.2.0
.Net Framework 4.5.2
Console Application
