### ISSUE TITLE
Commit time outs in Entity Framework.

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework6#298] opened 2017-06-07 06:35 UTC
_From @nagarjunacspeaks on June 7, 2017 4:38_

Question was posted in Stackoverflow but suggestions were not much of help.

https://stackoverflow.com/questions/44170804/commit-failure-error

Please go thru the above and I am just pasting my comment from there.

Please don't provide band aid fixes like increasing default timeout etc. as would like to know root cause of the problem.

It is code first. Also, it does not seem index issue as it not taking any time to query and should be pretty fast in term of sql performance for queries. Seems to be Entity framework and hence C# code issue. There is this below link in the error and hence seems to be drop from EF framework. [link] (go.microsoft.com/fwlink/?LinkId=313468). But, suggestions present at the link seems to be band-aid fixes. Any suggestions related to Entity framework would be appreciated as I am new to this.

_Copied from original issue: aspnet/EntityFramework#8760_

**Comment by ajcvickers** [comment] 2018-08-20 22:18
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment] 2019-03-18 22:27
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-03-18 22:27 UTC
Labels: blocked
