### ISSUE TITLE
EF DBContext SaveChanges Error

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/EntityFramework6#1364] opened 2019-10-08 21:49 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/758391/ef-dbcontext-savechanges-error.html)._

---
Microsoft documentation [https://docs.microsoft.com/en-us/ef/ef6/saving/change-tracking/entity-state] states:

&gt;Modified entities are updated in the database and then become Unchanged when SaveChanges returns.

But when I do a SaveChanges on a DBContext, items that were in the Modified state before then are still in a Modified state after the call.

In fact when I try to manually change the items' state to Unchanged in the following loop, they are changed back to Modified at the end of each loop iteration:

```
foreach(DbEntityEntry Item in Context.ChangeTracker.Entries())
    Item.State = EntityState.Unchanged;
```

Is this a bug or is there something I'm missing here?

---
#### Visual Studio Feedback System on 10/3/2019, 03:20 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2019-10-14 23:28
Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-10-21 16:37
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-10-21 16:37 UTC
