### ISSUE TITLE
Syntax Error in example

### ISSUE THREAD

**Issue by Ahmadzia307** [aspnet/EntityFramework6#725] opened 2019-03-11 13:48 UTC
context.Posts.Where(p => p.Tags.Contains("entity-framework").Load();  
As there is starting  where square bracket and not closing.

**Comment by ajcvickers** [comment] 2019-03-21 20:50
@Ahmadzia307 Where?

**Comment by ajcvickers** [comment] 2019-06-26 19:01
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-06-26 19:01 UTC
