### ISSUE TITLE
EF 6.3 FINALLY FIXES: Object ... has been disconnected or does not exist at the server?

### ISSUE THREAD

**Issue by henrikdahl8240** [aspnet/EntityFramework6#873] opened 2019-05-22 19:30 UTC
For a range of years, there has been countless complaints, that EF throws: "Object ... has been disconnected or does not exist at the server." when you run various migration commands.

It appears in many of these e-mails that the reason is, that there has been no willingness to salary a developer for the few minutes it would take to remove the timeout when marshalling to another AppDomain, which the migration commands are claimed to do.

As a consequence, to a lot of us, Entity Framework effectively does not support migrations.

Is it correct, that version 6.3 will finally, after all these years, solve these issues and we will se NO MORE timeouts when running migrations? If not, perhaps Microsoft should change from stating, that EF is the recommended platform for data ... to something like EF is the recommended platform for tiny laboratory exercises in the field of data ... You could also make it clear in the appraisal of EF, that you force users into a honey pot/vendor lock-in after they have invested in substantial development, as you force the migrations to fail. It would tell the truth, because it's actually what you do and this can also justify, why you so persistently do not want to solve this problem after so many versions since the first complaints.

**Comment by tomRedox** [comment] 2019-06-03 10:31
I think this is probably related [https://github.com/aspnet/EntityFramework6/issues/96](https://github.com/aspnet/EntityFramework6/issues/96)?

**Comment by ajcvickers** [comment] 2019-06-26 16:15
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-06-26 16:15 UTC
