### ISSUE TITLE
Can't Enable-Migrations targeting netcoreapp3.0

### ISSUE THREAD

**Issue by centreboard** [aspnet/EntityFramework6#1356] opened 2019-10-07 09:01 UTC
### Steps to reproduce
With a brand new class library I can't enable migrations when targeting `netcoreapp3.0` . It works if I change to `net48` or dual target `net48;netcoreapp3.0`

```
PM> Enable-Migrations
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'C:\Users\majohnson\.nuget\packages\entityframework\6.3.0\tools\netcoreapp3.0\any\ef6.dll'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'C:\Users\majohnson\.nuget\packages\entityframework\6.3.0\tools\netcoreapp3.0\any\ef6.dll'
```

``` xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.3.0" />
  </ItemGroup>

</Project>
```

``` c#
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace Ef6 {
    
    public class MyContextFactory : IDbContextFactory<MyContext> {
        public MyContext Create() {
            return new MyContext(
                "Server=(localdb)\\mssqllocaldb;Database=MyContext;Trusted_Connection=True;MultipleActiveResultSets=true");
        }
    }
    
    public class MyContext : DbContext {
        public MyContext(string connectionString) : base(connectionString) { }
        
        public DbSet<MyTable> MyTables { get; set; }
    }
    
    public class MyTable {
        public int Id { get; set; }
    }
}
```

### Further technical details
EF version: 6.3
Database Provider: (e.g. EntityFramework.SqlServer)
Operating system: (e.g. Windows 10) Windows 10
IDE: (e.g. Visual Studio 2017 15.6) VS 2019 16.4 Preview 1

dotnet --version 3.0.100

**Comment by ajcvickers** [comment] 2019-10-14 23:25
@centreboard I am not able to reproduce this using the exact code from above. Can you post the actual VS solution that you used to test?

**Comment by centreboard** [comment] 2019-10-15 07:49
@ajcvickers Here's the folder. I get the same error trying to run `Add-Migration Name`
[Ef6.zip](https://github.com/aspnet/EntityFramework6/files/3727935/Ef6.zip)

**Comment by ajcvickers** [comment] 2019-10-15 16:14
@bricelam This repros for me when I download the solution provided, which doesn't seem to be any different from the one I created manually that works.

**Comment by ajcvickers** [comment] 2019-10-15 16:30
@centreboard @bricelam I _think_ this only happens when the project/solution is called "Ef6". I renamed it all to "NotSix" and it started working.

**Comment by bricelam** [comment] 2019-10-16 19:07
Yep. Bug https://github.com/aspnet/EntityFrameworkCore/issues/8035 came along with the new architecture for migrations commands

**Comment by ajcvickers** [comment] 2019-10-16 19:29
Thanks Brice. Closing this as won'y fix, since the workaround is easy.

**Closed** 2019-10-16 19:28 UTC
