### ISSUE TITLE
add-migration throws an error message

### ISSUE THREAD

**Issue by dnistreanu** [aspnet/EntityFramework6#529] opened 2018-05-04 09:11 UTC
When I try to add a new migration via `add-migration` I get following error. Setting `DbMigrationsConfiguration.AutomaticMigrationsEnabled` to true doesn't change anything. I deleted old migration manually.

Error message:
`Unable to update database to match the current model because there are pending changes and automatic migration is disabled. Either write the pending model changes to a code-based migration or enable automatic migration. Set DbMigrationsConfiguration.AutomaticMigrationsEnabled to true to enable automatic migration.`

### Steps to reproduce
- I just deleted a foreign key to a table in one of my Code First Models and now I can't add new migration.

### Further technical details
EF version: 6.2 (In properties 6.0)
Database Provider: In properties 6.0
Operating system: Windows 10
IDE: Visual Studio community 2017 15.6.5

**Comment by bladedeyna** [comment] 2018-06-05 14:30
You may have a migration that hasn't yet been run blocking you from adding a new one.

Check your applied migrations in the _MigrationHistory database table. Check if these match what you have in the code first models. If some are missing then run the command `update-database` which will apply these pending migrations. You should now be able to run the `add-migration` command for your new migration.

**Comment by ajcvickers** [comment] 2018-07-06 17:20
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment] 2018-07-27 16:00
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2018-07-27 16:00 UTC
