### ISSUE TITLE
Wrong SQL translation of left join ... group by ... count()

### ISSUE THREAD

**Issue by xumix** [aspnet/EntityFramework6#135] opened 2016-12-09 19:44 UTC
This is some simple code for user polls. I'm trying to count poll votes:

```C#
public class PollAnswer : EntityBase
    {
        public PollAnswer()
        {
            PollUserAnswers = new HashSet<PollUserAnswer>();
        }

        public int PollTypeId { get; set; }
        public string Name { get; set; }
        public byte Order { get; set; }
        public virtual PollType PollType { get; set; }
        public virtual ICollection<PollUserAnswer> PollUserAnswers { get; set; }
    }
public class PollUserAnswer : EntityBase
    {
        public int AnswerId { get; set; }
        public int UserId { get; set; }
        public string IPAdress { get; set; }
        public virtual PollAnswer PollAnswer { get; set; }
    }

var res = from a in UnitOfWork.GetSet<PollAnswer>()
                      where a.PollTypeId == id
                      from ua in a.PollUserAnswers.DefaultIfEmpty()
                      group ua by new { a.Name, a.Order }
                          into gr
                          orderby gr.Key.Order
                          select new { Answer = gr.Key.Name, Count = gr.Count() };
```
The sql:
```sql
SELECT  [Project1].[C2] AS [C1] ,
        [Project1].[Name] AS [Name] ,
        [Project1].[C1] AS [C2]
FROM    ( SELECT    [GroupBy1].[A1] AS [C1] ,
                    [GroupBy1].[K1] AS [Name] ,
                    [GroupBy1].[K2] AS [Order] ,
                    1 AS [C2]
          FROM      ( SELECT    [Extent1].[Name] AS [K1] ,
                                [Extent1].[Order] AS [K2] ,
                                COUNT(1) AS [A1]
                      FROM      [dbo].[PollAnswer] AS [Extent1]
                                LEFT OUTER JOIN [dbo].[PollUserAnswer] AS [Extent2] ON [Extent1].[Id] = [Extent2].[AnswerId]
                      WHERE     [Extent1].[PollTypeId] = @p__linq__0
                      GROUP BY  [Extent1].[Name] ,
                                [Extent1].[Order]
                    ) AS [GroupBy1]
        ) AS [Project1]
ORDER BY [Project1].[Order] ASC;
```
This query will give **wrong results** if just 1 vote exists, it will show that EVERY answer has 1 vote.

The error here is ```COUNT(1) AS [A1]``` which actually must be ```COUNT([Extent2].[AnswerId]) AS [A1]```

I've even tried this:
```C#
var res = from a in UnitOfWork.GetSet<Models.PollAnswer>()
                      where a.PollTypeId == id
                      from ua in a.PollUserAnswers.DefaultIfEmpty()
                      group ua by new { a.Name, a.Order }
                          into gr
                          orderby gr.Key.Order
                          select new { Answer = gr.Key.Name, Count = gr.Select(s => s.Id).Count() };
var res = from a in UnitOfWork.GetSet<Models.PollAnswer>()
                      join ua in UnitOfWork.GetSet<Models.PollUserAnswer>() on a.Id equals ua.AnswerId into j
                      from r in j.DefaultIfEmpty()
                      where a.PollTypeId == id
                      group r by new { a.Name, a.Order }
                          into gr
                          orderby gr.Key.Order
                          select new { Answer = gr.Key.Name, Count = gr.Count() };
```
 But the result is still the same.

I've managed to workaround this issue with this kind of query:
```C#
var res = from a in UnitOfWork.GetSet<Models.PollAnswer>()
                      where a.PollTypeId == id
                      from ua in a.PollUserAnswers.DefaultIfEmpty()
                      group ua by new { a.Name, a.Order }
                          into gr
                          orderby gr.Key.Order
                          select new { Answer = gr.Key.Name, Count = gr.Count(s => s.AnswerId != null) };
```
 which gives some UGLY sql
```sql
SELECT 
    [Project4].[Id] AS [Id], 
    [Project4].[Name] AS [Name], 
    [Project4].[C1] AS [C1]
    FROM ( SELECT 
        [Project3].[Id] AS [Id], 
        [Project3].[Name] AS [Name], 
        [Project3].[Order] AS [Order], 
        [Project3].[C1] AS [C1]
        FROM ( SELECT 
            [Project2].[Id] AS [Id], 
            [Project2].[Name] AS [Name], 
            [Project2].[Order] AS [Order], 
            (SELECT 
                COUNT(1) AS [A1]
                FROM  [dbo].[PollAnswer] AS [Extent3]
                INNER JOIN [dbo].[PollUserAnswer] AS [Extent4] ON [Extent3].[Id] = [Extent4].[AnswerId]
                WHERE ([Extent3].[PollTypeId] = @p__linq__0) AND ([Project2].[Id] = [Extent3].[Id])) AS [C1]
            FROM ( SELECT 
                [Distinct1].[Id] AS [Id], 
                [Distinct1].[Name] AS [Name], 
                [Distinct1].[Order] AS [Order]
                FROM ( SELECT DISTINCT 
                    [Extent1].[Id] AS [Id], 
                    [Extent1].[PollTypeId] AS [PollTypeId], 
                    [Extent1].[Name] AS [Name], 
                    [Extent1].[Order] AS [Order]
                    FROM  [dbo].[PollAnswer] AS [Extent1]
                    LEFT OUTER JOIN [dbo].[PollUserAnswer] AS [Extent2] ON [Extent1].[Id] = [Extent2].[AnswerId]
                    WHERE [Extent1].[PollTypeId] = @p__linq__0
                )  AS [Distinct1]
            )  AS [Project2]
        )  AS [Project3]
    )  AS [Project4]
    ORDER BY [Project4].[Order] ASC;
```

**Comment by ajcvickers** [comment] 2018-08-31 19:45
@xumix I tested this with multiple different sets of data and the results seem correct in that they both match the semantic meaning of the query and they also match the results from LINQ-to-Objects for the same data. Can you please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

**Comment by xumix** [comment] 2018-09-05 13:52
I'll try to reproduce the bug and send you the results

**Comment by ajcvickers** [comment] 2019-03-18 22:19
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-03-18 22:19 UTC
Labels: blocked, type-bug
