### ISSUE TITLE
EF generate wrong sql  ， BUG？

### ISSUE THREAD

**Issue by SevenPlus** [aspnet/EntityFramework6#253] opened 2017-04-22 15:53 UTC
my development environment is "MYSQL+EF6.1.3"

here is my c# code

> _dbContext.Ad.Select(o => new { o.Id, o.Title, o.ImageUrl })
 .OrderByDescending(o=> DbFunctions.CustomFun(o.Title,"TEST"));

the generated sql below

> SELECT
_**`Project1`.`C2` AS `C1`,**_ 
`Project1`.`id`, 
`Project1`.`title`, 
`Project1`.`imageurl`
FROM (SELECT
**_`CustomFun`(`Extent1`.`title`, @gp1) AS `C1`_,** 
`Extent1`.`id`, 
`Extent1`.`title`, 
`Extent1`.`imageurl`, 
**_1 AS `C2`_**
FROM `ad` AS `Extent1`) AS `Project1`
 ORDER BY 
`Project1`.`C1` DESC

Why the field C2 into a C1,?
and is there a way to remove "1 AS `C2`"?

**Comment by ajcvickers** [comment] 2017-04-24 19:10
@SevenPlus Is this producing incorrect results for you? If so, could you provide a complete code listing or project that reproduces the issue? You also might want to file an issue with the MySQL provider, since the bug may be there.

Beyond any functional issue, this kind of SQL change is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Comment by ajcvickers** [comment] 2017-05-01 18:32
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2017-05-01 18:32 UTC
