### ISSUE TITLE
Entity Framework Code First Foreign keys

### ISSUE THREAD

**Issue by wstaelens** [aspnet/EntityFramework6#93] opened 2016-10-24 14:27 UTC
When deleting a foreign key property in an entity class, the new migration doesn't delete the foreign key in the database.

Have to manually remove the old Key in Microsoft SQL Server Management Studio for each Table --> Key --> select and delete it 

`The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_dbo.Foo_dbo.User_CreatedBy_ID". The conflict occurred in database "MyDB", table "dbo.User", column 'ID'.
The statement has been terminated.`

**Comment by rowanmiller** [comment] 2016-10-24 18:51
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean 😄... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).

**Comment by rowanmiller** [comment] 2016-10-31 18:17
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed by rowanmiller** 2016-10-31 18:17 UTC
