### ISSUE TITLE
EF's exception handling isn't correct

### ISSUE THREAD

**Issue by stevenxi** [aspnet/EntityFramework6#239] opened 2017-04-03 10:07 UTC
It's a bit complicated problem:

We found 2 'impossible' errors in our code:
a. An 'Select' query should always returns value, returns 0 result.
b. An 'Count' query, throws no element exception.

We did investigation, the reason for those errors are because EF executed a data reader, has no result. But for that query, there MUST be result in it.

We tried to add log to trap the problem. The logger uses DatabaseLogFormatter, overwrite LogResult(command, interceptionContext) The log shows very strange result.
a. A count query (attached below) returns no result, interceptionContext.Exception is null. But meanwhile outter calling method gets SQL's dead lock exception.
b. Same query, no result returns, interceptionContext.Exception is null. The outter calling method does not get dead lock or another other SQL's exception. But because the IQueryable.Count gets result by .Single(), it throws no element exception.

This issue happens occasionally, so far cannot find a way to garentee reproduce it.

In Summary:
Suspect some time EF does not throw, or even catch the underlying SQL exception.

Since it only happens to the production environment, we cannot always turn the SQL profiler on and trap the query from SQL Server side.

===================================================
EF Query:
context.FileRecords.Count(f => openStatus.Contains(f.FileStatusId) && f.UserId == userId)

EF generated SQL query:

SELECT
[GroupBy1].[A1] AS [C1]
FROM ( SELECT
COUNT(1) AS [A1]
FROM [dbo].[FileRecords] AS [Extent1]
WHERE ([Extent1].[FileStatusId] IN (1000, 2000, 5000)) AND ([Extent1].[UserId] = @p__linq__0)
) AS [GroupBy1]

====================================================
Dead lock (lock timeout) exception (when available):

System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while reading from the store provider's data reader. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Transaction (Process ID 70) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows) at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more) at System.Data.SqlClient.SqlDataReader.Read() at System.Data.Entity.Core.Common.Internal.Materialization.Shaper1.StoreRead()
--- End of inner exception stack trace ---
at System.Data.Entity.Core.Common.Internal.Materialization.Shaper1.HandleReaderException(Exception e) at System.Data.Entity.Core.Common.Internal.Materialization.Shaper1.StoreRead()
at System.Data.Entity.Core.Common.Internal.Materialization.Shaper1.SimpleEnumerator.MoveNext() at System.Linq.Enumerable.Single[TSource](IEnumerable1 source)
at Koala.Web.Controllers.UserMessageAndEvent.UserMessageAndEventController.<>c__DisplayClass14_0.b__0(Int32 userId) in C:\BuildAgent\work\50dd892818aa2a5a\src\Giove\Koala\Koala.Web\Controllers\UserMessageAndEvent\UserEvent.cs:line 134
at Avocado.Common.Cache.WeakReferenceMemoryCache2.GetValue(Func2 loadData, TKey key) in C:\BuildAgent\work\50dd892818aa2a5a\src\Giove\Avocado\Avocado.Common\Cache\WeakReferenceMemoryCache.cs:line 107
at Koala.Web.Controllers.UserMessageAndEvent.UserMessageAndEventController.RefreshEvent() in C:\BuildAgent\work\50dd892818aa2a5a\src\Giove\Koala\Koala.Web\Controllers\UserMessageAndEvent\UserEvent.cs:line 116
at lambda_method(Closure , ControllerBase , Object[] )
at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary2 parameters) at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary2 parameters)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.b__3d()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.b__3f()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.b__3f()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.b__3f()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.b__3f()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.b__3f()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.b__1c()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.b__1e(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)

====================================================
Count exception (when no sql exception):

System.InvalidOperationException: Sequence contains no elements
at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)

=====================

EF is latest release version: 6.1.40302
MS SQL is Sql 2016, Azure VM image.

**Comment by ajcvickers** [comment] 2019-03-18 22:25
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by stevenxi** [comment] 2019-03-18 22:33
;) as you can see from the description, we haven't even made to reproduce it in our dev environment. 
I would be able to debug the EF source code if I can guarantee reproducing it.  It's quite like a timing issue.

**Comment by ajcvickers** [comment] 2019-06-26 18:36
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-06-26 18:36 UTC
Labels: blocked
