### ISSUE TITLE
No annotations being generated when a AttributeToTableAnnotationConvention is defined on a Complex type

### ISSUE THREAD

**Issue by WouterVanmulken** [aspnet/EntityFramework6#305] opened 2017-06-23 11:34 UTC
I made a custom Attribute and made a mapping to give it a annotation in the migrations. When the attribute is set on a class that is in the Dbcontext, it works. 

But when it's a child of a object in dbcontext, the fields of the child completely ignore the attribute and get added individually as fields in the parent. This means that the attribute gets lost.

Example : 

```
 public class Foo
    {
        public int Id { get; set; }

        public Test TestViewObj { get; set; }
    }

    [RemoveView]
    public class Test
    {
        public int testfield { get; set; }
    }

```
Will generate

```
 public partial class test : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Foos", "TestViewObj_testfield", c => c.Int(nullable: false));
        }
        
        public override void Down()
        {
            DropColumn("dbo.Foos", "TestViewObj_testfield");
        }
    }

```
I'm using the following for the attribute and convention. 
```
   [AttributeUsage(AttributeTargets.Class | AttributeTargets.Property)]
    public class RemoveViewAttribute : Attribute
    {
    }
```

```
 modelBuilder.Conventions.Add(
                new AttributeToTableAnnotationConvention<RemoveViewAttribute, string>(
                    "RemoveViewAnnotation",
                    (property, attributes) => "test"));
```
Is this desired behaviour since this will completely ignore the AttributeToTableAnnotationConvention and if so, is there a workaround for it ?

**Comment by ajcvickers** [comment] 2017-06-23 18:38
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by CZEMacLeod** [comment] 2017-06-23 20:16
Just my 2p but your Class Test is _not_ a Table, but a Complex Type so the annotation would not be on the table, but on a 'group' of fields.
You could just as easily have 
```
 public class Foo
    {
        public int Id { get; set; }

        public Test TestViewObj1 { get; set; }
        public Test TestViewObj2 { get; set; }
    }
```
which would result in 2 testfields. And if you have multiple fields in the Test class, where would it put your annotations?

**Comment by WouterVanmulken** [comment] 2017-06-23 21:29
I made a project to reproduce the issue, [here](https://github.com/WouterVanmulken/Example-project-Ef-annotations) .

To reproduce : 

-  Remove the "migrations/201706232042423_test.cs" class. (this is a example of what happens)
- Change the connectionString in the App,config to your prefered database.
- Run "update-database"
- Run "add-migration test"

This will result in the following migration :

The following code gets generated.
```
public partial class test : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Foos", "TestViewObj_testfield",
                c => c.Int(nullable: false));
        }

        public override void Down()
        {
            DropColumn("dbo.Foos", "TestViewObj_testfield");
        }
    }

```

```
public partial class test : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Foos", "TestViewObj_testfield",
                c => c.Int(nullable: false
                // What i think should also be generated
                                ,annotations: new Dictionary<string, AnnotationValues>    
                                {
                                    {
                                        "RemoveViewAttribute",
                                        new AnnotationValues(oldValue: null, newValue: "")
                                    },
                                }
               //end
                ));
        }

        public override void Down()
        {
            DropColumn("dbo.Foos", "TestViewObj_testfield");
        }
    }

```
What i would like to happen although i do admit it's kinda overkill is to annotate each value, that way no information is lost.

This problem could indead be solved by adding a `[Table]` annotation which would make it a table instead of a complex type, but i personally think that would kind of defeat the point of the `AttributeToTableAnnotationConvention`.






The reason i need to have the annotation is that as far as i've found the migrations work in the following order (please correct me if i'm wrong):

Code -> Migration -> Sqlgenerator

But i'm trying to change the sqlgenerator logic depending on if it has an  attribute. Since i see no other way of getting back to the original code and checking, i need the annotation for my logic.



I'm also rather new at this, so feel free to give feedback.

**Comment by WouterVanmulken** [comment] 2017-06-26 15:47
Another option would be to make a `AttributeToComplexTypeAnnotationConvention` which would result in adding a annotations to all fields. That way the normal AttributeToTableAnnotationConvention doesn't have to be changed and there would still be the option for thos who want it to keep the attributedata.

**Comment by ajcvickers** [comment] 2018-08-20 23:02
@WouterVanmulken Since the complex type does not exist in the database--it is a purely a concept of the conceptual/object model--there isn't really an `AttributeTo...` that makes sense for it. Instead, `AttributeToColumnAnnotationConvention` could be used on the properties of the complex type, since those properties do map to something that exists in the database--namely, columns.

It would likely be possible to update `AttributeToTableAnnotationConvention` to aggregate all attributes from complex type classes into an annotation on the table. but I'm not convinced that would be a great experience. 

For now, I'm closing this as by-design. However, if someone wanted to design an experience around this scenario, we would likely consider it as a PR.

**Closed by ajcvickers** 2018-08-20 23:02 UTC
