### ISSUE TITLE
Entity Framework : an existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by RaoHammas** [aspnet/EntityFramework6#876] opened 2019-05-26 15:10 UTC
I am using Entity Framework 6.2.0 with my WCF service hosted in IIS. I am getting this error when trying to eager load related table data. I have two tables `Product` and `Category` joined by `CategoryID`.  

Trying to fetch products data and their related `category Name` but getting that error (I have tried almost every solution on web from last 24 hours).  

    public List<Product> GetAllProducts(int start, int end)
    {
        return _context.Products.Include(x=>x.Category).ToList();
    }  

I have also set following properties to **false**.  

    public Intelliventory_DBEntities()
        : base("name=Intelliventory_DBEntities")
    {
        this.Configuration.ProxyCreationEnabled = false;
        this.Configuration.LazyLoadingEnabled = false;
    }  

**App.config**  

    <configuration>
        <system.serviceModel>
            <bindings>
                <basicHttpBinding>
                    <binding name="BasicHttpBinding_IIntelliventoryService" 
                             closeTimeout="10:01:00" openTimeout="10:01:00" 
                             receiveTimeout="10:10:00" sendTimeout="10:01:00" 
                             allowCookies="false" bypassProxyOnLocal="false" 
                             maxBufferPoolSize="2147483647" 
                             maxReceivedMessageSize="2147483647"
                             useDefaultWebProxy="true">
                        <readerQuotas maxDepth="2147483647" 
                                      maxStringContentLength="2147483647"
                                      maxArrayLength="2147483647"    
                                      maxBytesPerRead="2147483647"
                                      maxNameTableCharCount="2147483647" />
                    </binding>
                </basicHttpBinding>
            </bindings>
            <behaviors>
                <endpointBehaviors>
                    <behavior name="ServiceBehavior">
                         <dataContractSerializer maxItemsInObjectGraph="2147483647"/>
                    </behavior>
                </endpointBehaviors>
            </behaviors>
            <client>
                <endpoint name="BasicHttpBinding_IIntelliventoryService" 
                    address="http://localhost:5050/IntelliventoryService.svc"
                    behaviorConfiguration="ServiceBehavior"  
                    binding="basicHttpBinding" 
                    bindingConfiguration="BasicHttpBinding_IIntelliventoryService"
                    contract="IntelliventoryService.IIntelliventoryService" />
            </client>
        </system.serviceModel>
    </configuration>  

**Web.Config**  

    <configuration>
        <configSections>
            <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
        </configSections>
        <appSettings>
            <add key="aspnet:UseTaskFriendlySynchronizationContext" value="true" />
        </appSettings>
        <system.web>
            <compilation debug="true" targetFramework="4.8" />
            <httpRuntime targetFramework="4.8" />
        </system.web>
        <system.serviceModel>
            <bindings>
                <basicHttpBinding>
                    <binding name="BasicHttpBinding_IIntelliventoryService" 
                             closeTimeout="10:01:00" openTimeout="10:01:00" 
                             receiveTimeout="10:10:00" sendTimeout="10:01:00" 
                             allowCookies="false" bypassProxyOnLocal="false" 
                             maxBufferPoolSize="2147483647" 
                             maxReceivedMessageSize="2147483647"
                             useDefaultWebProxy="true">
                        <readerQuotas maxDepth="2147483647" 
                                      maxStringContentLength="2147483647"
                                      maxArrayLength="2147483647" 
                                      maxBytesPerRead="2147483647"
                                      maxNameTableCharCount="2147483647" />
                    </binding>
                </basicHttpBinding>
            </bindings>
            <behaviors>
                <serviceBehaviors>
                    <behavior>
                        <dataContractSerializer maxItemsInObjectGraph ="2147483647"/>
                        <serviceThrottling maxConcurrentCalls="16" maxConcurrentInstances="26" maxConcurrentSessions="10" />
                        <serviceMetadata httpGetEnabled="true" httpsGetEnabled="true" />
                        <serviceDebug includeExceptionDetailInFaults="true" />
                    </behavior>
                </serviceBehaviors>
            </behaviors>
            <protocolMapping>
                <add binding="basicHttpsBinding" scheme="https" />
            </protocolMapping>
            <serviceHostingEnvironment aspNetCompatibilityEnabled="true" multipleSiteBindingsEnabled="true" />
            </system.serviceModel>
        <system.webServer>
        <modules runAllManagedModulesForAllRequests="true" />
        <directoryBrowse enabled="true" />
      </system.webServer>
      <entityFramework>
        <defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
          <parameters>
            <parameter value="mssqllocaldb" />
          </parameters>
        </defaultConnectionFactory>
        <providers>
          <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
        </providers>
      </entityFramework>
    <connectionStrings>
      <add name="Intelliventory_DBEntities" 
                            connectionString="metadata=res://*/ADOModel.csdl|res://*/ADOModel.ssdl|res://*/ADOModel.msl;provider=System.Data.SqlClient;
                            provider connection string=&quot;data source=RAO-HAMMAS-PC;initial catalog=Intelliventory_DB;persist security info=True;
                            user id=admin;password=admin;MultipleActiveResultSets=True;App=EntityFramework&quot;" 
                            providerName="System.Data.EntityClient" />
    </connectionStrings></configuration>  

I don't get this error when i don't eager load category table.  

Also if I try to load just specific column, I get this error.  

    _context.Products.Include(x=>x.Category.CategoryName).ToList();

> A specified Include path is not valid. The EntityType 'Intelliventory_DBModel.Category' does not declare a navigation  

**Category Table from Db Context**  

    public int CategoryID { get; set; }
    public string CategoryName { get; set; } 

 **Product Table from Db Context**

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Purchases = new HashSet<Purchase>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public int CategoryID { get; set; }
        public System.DateTime Date { get; set; }
        public double Quantity { get; set; }
        public string Model { get; set; }
        public string Details { get; set; }
        public double SellPrice { get; set; }
        public double PurchasePrice { get; set; }
        public int SupplierID { get; set; }
        public Nullable<double> PaidAmount { get; set; }
        public Nullable<int> NoOfSales { get; set; }
        public Nullable<double> DueAmountToPay { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
    }  

**Did i do something wrong ?**  

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/UfB5a.jpg

**Comment by ajcvickers** [comment] 2019-06-26 16:19
@RaoHammas I don't see anything obviously wrong here. I think we will need a small, runnable project/solution in order to fully reproduce what you are seeing.

**Comment by ajcvickers** [comment] 2019-08-06 18:15
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-08-06 18:15 UTC
