### ISSUE TITLE
Lazy loading fails because of not closed connection

### ISSUE THREAD

**Issue by mkonars** [aspnet/EntityFramework6#796] opened 2019-04-25 11:54 UTC
Hi, I have the following code which was working in 6.1.3
```c#
foreach(Job job in container.Jobs) // First query
{
  if (job.QueuedJob != null) // Second query
	job.QueuedJob.Priority = 1;
}
```
In 6.2.0 the following exception is thrown: 

> There is already an open DataReader associated with this Command which must be closed first

If I add ToList() in the first line, it does work. I understand that when using IQueryable the underlying connection is not disposed. 
Is it a bug or that's how it will be from 6.2.0 and I have to update my code?

### Further technical details
EF version: 6.2.61023.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.6

**Comment by ajcvickers** [comment] 2019-04-25 16:04
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by mkonars** [comment] 2019-04-27 05:46
Hi,
It occured that the connection string in my project was missing MultipleActiveResultSets=True. Without it, it is failing in 6.2.0, but not in 6.1.3.

I tried to recreate this issue using this sample [https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/data/entity-framework-6/sample](url), but I could not do it. It is working in both 6.1.3 and 6.2.0. 

I don't know why it is failing in my project but not in this sample. Maybe because my project is using .NET 4.5 whereas this sample is made with .NET Core. I don't have any other clue. 

If you know the cause of the problem, I would like to hear it from you. If not, then please close the issue.

**Comment by ajcvickers** [comment] 2019-06-26 19:11
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-06-26 19:11 UTC
