### ISSUE TITLE
ManyToMany Orphan Removal Master Data Remove Problem

### ISSUE THREAD

**Issue by ergatech** [aspnet/EntityFramework6#533] opened 2018-05-07 21:25 UTC
Dear All;

My DataStructure is Followed Codes. 

```c#

public class Category : IEntity
    {
        [Key]
        public long ID { get; set; }
        public string Name { get; set; }
    }
public class CategoryMap : EntityTypeConfiguration<Category>
    {
        public CategoryMap()
        {
            ToTable("TEST_TB_CATEGORY");
            HasKey(x => x.ID);
            Property(x => x.ID).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name);
        }
    }
```
```c#

public class Post : IEntity
    {
        [Key]
        public long ID { get; set; }
        public string Name { get; set; }
        public IList<Tag> Tags { get; set; }
        [AutoInclude]
        public IList<Category> Categories { get; set; }
    }

 public class PostMap : EntityTypeConfiguration<Post>
    {
        public PostMap()
        {
            ToTable("TEST_TB_POST");
            HasKey(x => x.ID);
            Property(x => x.ID).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name);
            HasMany(x => x.Tags)
                .WithMany()
                .Map(x => x.ToTable("TEST_TB_POSTTAGS").MapLeftKey("PostID").MapRightKey("TagID"));
            HasMany(x => x.Categories)
                .WithMany()
                .Map(x => {
                    x.ToTable("TEST_TB_POSTCATEGORY").MapLeftKey("PostID").MapRightKey("CategoryID");
                    
                });
            
        }
    }
```
Case Using Example
```c#

var category1 = ctx.Categories.Find(1);
var category2 = ctx.Categories.Find(2);
var category3 = ctx.Categories.Find(3);

var post = new Post();
post.Name = "Deneme";
post.Categories.Add(category1);
post.Categories.Add(category2);
ctx.Posts.Add(post);

ctx.SaveChanges();

```

```c#

var category3 = ctx.Categories.Find(3);

var post = ctx.Posts.Include(x=>x.Categories).Find(1);
post.Name = "Deneme";
post.Categories.RemoveAt(0);
post.Categories.RemoveAt(1);
post.Categories.Add(category3);


ctx.SaveChanges();

```
I changed ForeginKey Cascade Delete Operation is NoAction but 
EntityFramework Delete TEST_TB_CATEGORY table data with orphan. I dont want delete master data. I want only delete orphan on TEST_TB_POSTCATEGORY table.

Please help me. I need help immediately.

### Further technical details
EF version: 6.2.0
Database Provider:  EntityFramework.SqlServer
Operating system: Windows 10
IDE:  Visual Studio 2017 15.6

**Comment by ergatech** [comment] 2018-06-06 20:41
Dear All;

I waiting a answer since 8 May. Please help. I can't continue my projects this bug!

**Comment by ajcvickers** [comment] 2018-07-06 17:31
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment] 2018-07-27 16:00
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2018-07-27 16:00 UTC
