### ISSUE TITLE
EF Tools 6.1.3 Update Model Issue

### ISSUE THREAD

**Issue by stephanebo21** [aspnet/EntityFramework6#109] opened 2016-11-17 13:48 UTC
Hi, 

I am working with EF 6 and oracle and since the 6.1.3 I have an issue which I suppose no solution. 

With Oracle, I you make a view with an UNION, no matter primary contraints, all fields used by the primary key are considered nullable. This situation was already present before 6.1.3, but the difference is that the entity is no longer added to the model (the old solution was to modify xml after the entity was added). 

In fact the issue is that we cannot anymore upgrade Visual Studio and EF. With the same version of EF that does not work anymore on VS 2015 (work on VS 2012).

Here's the reference of this issue on your previous bugtracker where you mentioned a solution but nothing was done these last months : http://entityframework.codeplex.com/workitem/2888

Thanks
Stephane

**Comment by rowanmiller** [comment] 2016-11-22 19:55
@lajones can you look at the history and see if we made a change that caused this issue. If we did, we can look at reverting it in 6.2.

**Comment by lajones** [comment] 2016-12-13 22:14
I think what's being talked about here is what happens with e.g. the `Quarterly Orders` view in the `Northwind` database. It has no key and no key can be inferred, so we would output to the SSDL within the EDMX something like the following:

```
        <!--Errors Found During Generation:
warning 6013: The table/view 'C:\WORK\TEST\TEST161213_NOKEYENTITIES_01\TEST161213_NOKEYENTITIES_01\NORTHWND.MDF.dbo.Quarterly Orders' does not have a primary key defined and no valid primary key could be inferred. This table/view has been excluded. To use the entity, you will need to review your schema, add the correct keys, and uncomment it.
        <EntityType Name="Quarterly Orders">
          <Property Name="CustomerID" Type="nchar" MaxLength="5" />
          <Property Name="CompanyName" Type="nvarchar" MaxLength="40" />
          <Property Name="City" Type="nvarchar" MaxLength="15" />
          <Property Name="Country" Type="nvarchar" MaxLength="15" />
        </EntityType>-->
```

(You would also see an error in the Error List window with the same warning).

You could then edit the XML, uncomment that block, define the key yourself and then use the entity as you planned.

The relevant pieces of code are: [StoreModelBuilder.CreateEntityTypeWtihoutDefinedKeys()](https://github.com/aspnet/EntityFramework6/blob/master/src/EFTools/EntityDesignerVersioningFacade/ReverseEngineerDb/StoreModelBuilder.cs#L337) and [EdmSerializationVisitor.VisitEdmEntityType()](https://github.com/aspnet/EntityFramework6/blob/master/src/EntityFramework/Core/Metadata/Edm/EdmSerializationVisitor.cs#L185) but I can't find any evidence that those have changed in years. And on VS2015 everything still works as expected for me for the `Quarterly Orders` view I.e. I see the warning and the XML comment is there in the SSDL.

We need more info to track this down. @stephanebo21 can you check whether you see the above with `Quarterly Orders` in `Northwind`. If not then we need all the version info of your VS.

If you do then for your Oracle view:

a) check that you are definitely selecting the view which does not finally appear when you go through the wizard to create the EDMX
b) check that you are looking at the SSDL section of the EDMX and not the CSDL section when you open the EDMX file in the XML editor - they are easily confused and the comment will only appear in the SSDL

If none of that works then we'd need to get access to a test database somehow to track this down.

**Comment by lajones** [comment] 2017-01-17 21:44
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by lajones** 2017-01-17 21:44 UTC
Labels: blocked, type-investigation

**Comment by stephanebo21** [comment] 2017-01-18 15:52
Sorry for my late answer, but I needed time to install a new clean machine to reproduce this case.
I have reproduced the issue and can give you details.
Before when the solution worked, after updating my EF Model I could encounter this kind of warning:

This issue was resolved by the development of a custom tool which modify xml model after the update and everything worked fine.

Now, since I am trying to work with Visual Studio 2015, EF 6.1.3, when I try to add the same view I have this error:
Error 13101: Key part ‘JOB_NAME’ for type ‘JOBS’ is not valid. All parts of the key must be non-nullable.
There is no way to modify xml because my view is not added to the Model Store.
I am pretty sure at 100% that this problem is specific to users which use EF and Oracle. All references I found on the internet are from people who have the same development context.

This is a critical risk for us because we have no way to upgrade our application to new versions…

Regards
Stéphane

**Comment by stephanebo21** [comment] 2017-01-18 15:56
Sorry a part of my message was not included.

Re-post:

Sorry for my late answer, but I needed time to install a new clean machine to reproduce this case.
I have reproduced the issue and can give you details.
Before when the solution worked, after updating my EF Model I could encounter this kind of warning:
Errors Found During Generation:
      warning 6002: The table/view 'myView' does not have a primary key defined. The key has been inferred and the definition was created as a read-only table/view.
      
This issue was resolved by the development of a custom tool which modify xml model after the update and everything worked fine.

Now, since I am trying to work with Visual Studio 2015, EF 6.1.3, when I try to add the same view I have this error:
Error 13101: Key part ‘JOB_NAME’ for type ‘JOBS’ is not valid. All parts of the key must be non-nullable.
There is no way to modify xml because my view is not added to the Model Store.
I am pretty sure at 100% that this problem is specific to users which use EF and Oracle. All references I found on the internet are from people who have the same development context.

This is a critical risk for us because we have no way to upgrade our application to new versions…

Regards
Stéphane

**Comment by stephanebo21** [comment] 2017-01-18 16:11
Seems like mySQL users have some issues similar from exactly the same version of Visual Studio and Entity Framework:
https://social.msdn.microsoft.com/Forums/es-ES/544bfe56-b6e3-478e-993e-b549f9cce712/error-13101-key-part-nombre-for-type-recursos-is-not-valid-all-parts-of-the-key-must-be?forum=aspnetmvces

**Comment by divega** [comment] 2017-05-15 20:41
Dupe of #243.
