### ISSUE TITLE
I cannot install 6.3.0 on  vs 2015 , dotnet 4.6.2

### ISSUE THREAD

**Issue by rajesh-smartwebtech** [aspnet/EntityFramework6#1454] opened 2019-11-09 12:44 UTC
i install EF6.3.0 
it is not installing successfully 
VS 2015 Community
4.6.2

Error
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\dotNet_Project\vs2015\Smart_Scrapper\packages\EntityFramework.6.3.0\build\EntityFramework.props			0	

```

Please help for installation

**Comment by ajcvickers** [comment] 2019-11-11 17:49
@rajesh-smartwebtech Please post the complete steps you are using to do this install.

**Comment by rajesh-smartwebtech** [comment] 2019-11-12 04:44
System Configuration 
OS Win 10
Visual Studio 2015 Community
---------------------------------------

i have created project in vs 2015 with dot net 4.6.2 framework version
i need for  EntityFramework 6.3.0  
This package need EntityFramework 6.3.0 so i trying to install following command
Install-Package EntityFramework -Version 6.3.0

There are error after execute `Install-Package EntityFramework -Version 6.3.0` command 

> PM> Install-Package EntityFramework -Version 6.3.0
Attempting to gather dependency information for package 'EntityFramework.6.3.0' with respect to project 'cef_seleni_demo', targeting '.NETFramework,Version=v4.6.2'
Attempting to resolve dependencies for package 'EntityFramework.6.3.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'EntityFramework.6.3.0'
Resolved actions to install package 'EntityFramework.6.3.0'
Adding package 'EntityFramework.6.3.0' to folder 'D:\dotNet_Project\vs2015\cef_seleni_demo\packages'
Added package 'EntityFramework.6.3.0' to folder 'D:\dotNet_Project\vs2015\cef_seleni_demo\packages'
Install failed. Rolling back...
Package 'EntityFramework.6.3.0' does not exist in project 'cef_seleni_demo'
Removing package 'EntityFramework.6.3.0' from folder 'D:\dotNet_Project\vs2015\cef_seleni_demo\packages'
Removed package 'EntityFramework.6.3.0' from folder 'D:\dotNet_Project\vs2015\cef_seleni_demo\packages'
Install-Package : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the 
<Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\dotNet_Project\vs2015\cef_seleni_demo\packages\EntityFramework.6.3.0\build\EntityFramework.props
At line:1 char:1
+ Install-Package EntityFramework -Version 6.3.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by rajesh-smartwebtech** [comment] 2019-11-12 04:45
This is my VS version 

![image](https://user-images.githubusercontent.com/35251001/68642795-4824d380-0535-11ea-9416-153d39819997.png)

**Comment by ajcvickers** [comment] 2019-11-14 20:58
@rajesh-smartwebtech Please post the full stack trace of the exception. Also, is there any reason for using an old version of VS?

**Comment by manzyun** [comment] 2019-11-15 09:16
I thought I had encountered the same error, but while trying to install with the Visual Studio 2015 package manager console many times to reproduce the error, it behaves as if it installed successfully .

@rajesh-smartwebtech 
However, it was possible to install when installing for a project that outputs a class library in the package manager console. At least as of 2019-11-15T16:45+9:00.

My suggestion, why not delete the data in the `packages` folder and try installing again?

@ajcvickers 
> Also, is there any reason for using an old version of VS?

You might think it's a joke, but we Japanese developers often don't get the latest Visual Studio from the company.

However, what is mysterious is that although the installation is completed in the package manager console, the same error is output to the error list of Visual Studio `The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.` . The following is the contents of the corresponding `EntityFramworks.props` :

``` EntityFrameworks.props
<Project>
  <ItemGroup Condition="'$(EnableDefaultItems)' == 'True' And '$(EnableDefaultEntityDeployItems)' == 'True'">
    <EntityDeploy Include="**/*.edmx" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
    <None Remove="**/*.edmx" Condition="'$(EnableDefaultNoneItems)' == 'True'" />
  </ItemGroup>
</Project>
```

I tried it for about an hour to reproduce this issue, but I can only provide this information. I'm sorry.
I seem to be confused.

Thank you for reading to the end despite almost all machine translations in English.

**Comment by ajcvickers** [comment] 2019-12-09 19:15
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-12-09 19:15 UTC
Labels: closed-could-not-reproduce
