### ISSUE TITLE
Migration commands crash when running against an SDK-based csproj

### ISSUE THREAD

**Issue by HellBrick** [aspnet/EntityFramework6#230] opened 2017-03-24 06:50 UTC
I've encountered this problem when trying to convert a project to the new SDK-based csproj. It had worked fine until I tried to add a new migration, which crashed with the following error:
```
Exception calling "SetData" with "2" argument(s): "Type 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject' in assembly 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation, Version=15.0.0.0, Culture=neutral, Publ
icKeyToken=b03f5f7f11d50a3a' is not marked as serializable."
At C:\Users\HellBrick\.nuget\packages\entityframework\6.1.3\tools\EntityFramework.psm1:720 char:5
+     $domain.SetData('startUpProject', $startUpProject)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SerializationException
 
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Data.Entity.Migrations.Extensions.ProjectExtensions.GetPropertyValue[T](Project project, String propertyName)
   at System.Data.Entity.Migrations.MigrationsDomainCommand.GetFacade(String configurationTypeName, Boolean useContextWorkingDirectory)
   at System.Data.Entity.Migrations.EnableMigrationsCommand.FindContextToEnable(String contextTypeName)
   at System.Data.Entity.Migrations.EnableMigrationsCommand.<>c__DisplayClass2.<.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
Object reference not set to an instance of an object.
```

You can easily reproduce this with a new project:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.1.3" />
  </ItemGroup>
</Project>
```
```csharp
using System.Data.Entity;
namespace EntityFrameworkNewCsprojTest
{
	public class SomeEntity
	{
		public int ID { get; set; }
		public int Name { get; set; }
	}

	public class TestContext : DbContext
	{
		public DbSet<SomeEntity> SomeEntities { get; set; }
	}

	internal class Program
	{
		static void Main( string[] args ) {}
	}
}
```

Running `Enable-Migrations` against it will cause the same error.

This is a very unpleasant blocker for us, is there any way to at least work around this problem?

**Comment by ErikEJ** [comment] 2017-03-24 07:18
Use a standard "Classic" class library?

**Comment by HellBrick** [comment] 2017-03-24 07:26
That's what we're doing today =) The old csproj format obviously works, but the whole point of this issue is to figure out how to migrate to the new csproj format while keep using EF 6.

**Comment by ErikEJ** [comment] 2017-03-24 07:27
You will be entering a world of pain, suggest you wait for a new EF version (ie 6.3) with support for new project format https://github.com/NuGet/Home/issues/4876

**Comment by ErikEJ** [comment] 2017-03-24 07:29
I have logged https://github.com/aspnet/EntityFramework6/issues/231

**Comment by HellBrick** [comment] 2017-03-24 07:56
"World of pain" is a relative term, the old csproj isn't that pleasant to deal with either ;) If this can't be done without some substantial engineering work in the EF codebase, then there's no other choice but to wait for the update. However, if it's possible to make migrations work via some manual adjustments to project file/app.config/migration script/whatever, then it might just be worth it.

**Comment by ajcvickers** [comment] 2017-03-27 20:00
Closing this as a dupe of #231, which we are investigating.

**Comment by ErikEJ** [comment] 2017-03-29 17:59
@ajcvickers Think you forgot to actually close?

**Comment by ajcvickers** [comment] 2017-03-29 18:46
@ErikEJ Thanks. You are our process bot. 😉

**Closed by ajcvickers** 2017-03-29 18:46 UTC
Labels: closed-duplicate

**Comment by ajcvickers** [comment] 2017-03-29 20:27
@ErikEJ Don't apologize. It is much appreciated. 😸

**Comment by DeshmukhParag** [comment] 2017-07-11 10:48
![migrationcore](https://user-images.githubusercontent.com/16464539/28065001-6a45b8b2-6654-11e7-8c1f-f39620d75613.png)
EntityFrameworkCore\Enable-Migrations
EntityFrameworkCore\Add-Migration sdd
EntityFrameworkCore\Update-Database

**Comment by divega** [comment] 2017-07-11 14:54
@DeshmukhParag could you please explain the intent of your previous comment? Is there something not working according to your expectations?

**Comment by smitpatel** [comment] 2017-07-11 17:55
@bricelam - In above image, `EFCore\Enable-Migrations` says to use `EF\Update-Database` for EF6. which would be incorrect. Can you verify, we are doing correct thing?

**Comment by bricelam** [comment] 2017-07-11 19:00
Ha, nice. It's a bug. https://github.com/aspnet/EntityFramework/blob/rel/2.0.0/src/EFCore.Tools/tools/EntityFrameworkCore.psm1#L144
