### ISSUE TITLE
VS 2017 ASP.DefaultEntityTemplate is missing in latest Nuget package

### ISSUE THREAD

**Issue by DocGitHub** [aspnet/EntityFramework6#678] opened 2018-12-18 16:07 UTC
Trying to upgrade Dynamic Data Website to EF 6 i get an error:

...\DynamicData\EntityTemplates\Default.ascx(1): Build (web): Could not load type 'ASP.DefaultEntityTemplate'.

Same issue as described here, but in Visual Studio 2017 15.8.8., using latest nuget packages
[Supposedly Fixed Issue](https://developercommunity.visualstudio.com/content/problem/124270/vs2017-aspdefaultentitytemplate-is-missing.html)

### Steps to reproduce
1. Have no Web Application Project,  as described here:
[Getting started steps](https://www.c-sharpcorner.com/UploadFile/4b0136/getting-started-with-preview-of-dynamic-data-and-entity-data/)
or here:
[Getting started 2](https://blogs.msdn.microsoft.com/webdev/2014/01/30/announcing-preview-of-dynamic-data-provider-and-entitydatasource-control-for-entity-framework-6/)
so can only choose:
![image](https://user-images.githubusercontent.com/34685270/50166036-73338280-02e6-11e9-866d-116f8984860c.png)

EF 5 version was working....

### Further technical details
EF version: v6.2.0
EF Provider version: v6.0
EntityDataSource version: v6.0
Database Provider: System.Data.SqlClient
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.8 and 15.9.4

**Comment by ajcvickers** [comment] 2019-03-19 20:41
@DocGitHub So, is the issue you are hitting here that there is no "ASP.NET Dynamic Data Entities Web Application" template in Visual Studio 2017?

**Comment by DocGitHub** [comment] 2019-03-20 20:07
it's been a while, but the error occurs when consolidating / updating my EF versions to match to 6

The DynamicData uses EF 5, when i consolidate /upgrade it to EF 6 (nuget) then the error occurs.

...\DynamicData\EntityTemplates\Default.ascx(1): Build (web): Could not load type 'ASP.DefaultEntityTemplate'.

Same issue as described here, but in Visual Studio 2017 15.8.8., using latest nuget packages
[Supposedly Fixed Issue](https://developercommunity.visualstudio.com/content/problem/124270/vs2017-aspdefaultentitytemplate-is-missing.html).

**Comment by ajcvickers** [comment] 2019-03-20 21:00
@DocGitHub Can you create a small project/solution that demonstrates that error?

**Comment by ajcvickers** [comment] 2019-06-26 18:57
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-06-26 18:57 UTC
