### ISSUE TITLE
Suspend Execution Strategy doesn't port to .NET Core 3.0 since Remoting isn't supported

### ISSUE THREAD

**Issue by marchy** [aspnet/EntityFramework6#1227] opened 2019-09-05 21:07 UTC
Cannot port the execution strategy mentioned in EF docs '[Workaround: Suspend Execution Strategy](https://docs.microsoft.com/en-ca/ef/ef6/fundamentals/connection-resiliency/retry-logic#workaround-suspend-execution-strategy)' section, since Remoting is not supported in .NET Core 3.0.

Here is our implementation:
```
// REFERENCE: https://docs.microsoft.com/en-ca/ef/ef6/fundamentals/connection-resiliency/retry-logic#workaround-suspend-execution-strategy
internal class EF6DatabaseConfig : DbConfiguration {

	/// <summary>
	/// Used to support user-initiated transactions in cloud scenarios (ie: when using a retry strategy)
	/// </summary>
	internal static bool SuspendSqlAzureExecutionStrategy {
		// NOTE: Using CallContext allows this data to flow across the execution path (ie: async) even across thread switches (ie: resumptions). Nifty!
		get => (bool?)CallContext.LogicalGetData( nameof(SuspendSqlAzureExecutionStrategy) ) ?? false;
		set => CallContext.LogicalSetData( nameof(SuspendSqlAzureExecutionStrategy), value );
	}


	protected internal EF6DatabaseConfig() {
		SetProviderServices( "System.Data.SqlClient", SqlProviderServices.Instance );
		SetDatabaseInitializer( new CreateDatabaseIfNotExists<EF6DatabaseContext>() );
//		SetContextFactory( () => new EF6MigrationsDatabaseContextFactory().Create() );

		// NOTE: This is used for cloud scenarios (see https://msdn.microsoft.com/en-us/data/dn307226 and https://msdn.microsoft.com/en-us/library/dn456835(v=vs.113).aspx)
		SetExecutionStrategy( "System.Data.SqlClient", () => (SuspendSqlAzureExecutionStrategy) ?
			(IDbExecutionStrategy)new DefaultExecutionStrategy() 
			: new EnhancedSqlAzureExecutionStrategy() );
	}
}
```

Compilation error:
```
  EF6DatabaseContext.cs(13, 22): [CS0234] The type or namespace name 'Remoting' does not exist in the namespace 'System.Runtime' (are you missing an assembly reference?)
```

What's the alternative solution to use on .NET Core 3.0?

PS: The docs will need to be updating accordingly for the 3.0 release as well.

### Further technical details
EF version: 6.3.0-preview9-19423-04
Database Provider: System.Data.SqlClient (4.7.0-preview9.19421.4)
Operating system: Windows 10
IDE: Rider 2019.2.2

**Comment by divega** [comment] 2019-09-07 01:49
Closing as duplicate of https://github.com/aspnet/EntityFramework.Docs/issues/1691, assuming the actionable item is to update the documentation.

**Closed by divega** 2019-09-07 01:49 UTC
