### ISSUE TITLE
Add-Migration : Cannot bind argument to parameter 'Path' because it is null.

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/EntityFramework6#1412] opened 2019-10-22 18:31 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/777862/add-migration-cannot-bind-argument-to-parameter-pa-1.html)._

---
[regression]
1) create  an empty new Asp.Net Web Application[. NetFramework] project
2)install EntityFrameWork form NugetPackages.
3) Add connectionstrings in web.config
4) Now add model and Context class in Model folders
5)Now goto PackageConsole write this Add-migrations InitialCreate and press enter

got this error
Add-Migration : Cannot bind argument to parameter 'Path' because it is null.
At line:1 char:1
+ Add-Migration IntitialCreate
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Add-Migration], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Add-Migration

After updated to latest version of Vs2019 this problem came.

---
#### Visual Studio Feedback System on 10/15/2019, 10:38 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/16/2019, 11:02 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2019-10-25 21:31
Duplicate of #1290

**Closed by ajcvickers** 2019-10-25 21:31 UTC
