### ISSUE TITLE
6.2 code first issues

### ISSUE THREAD

**Issue by iozcelik** [aspnet/EntityFramework6#431] opened 2017-12-29 14:20 UTC
I have some issues with Entity framework 6.2. I change ef version and now I have a lot bug..

1. `NotMapped` why not working any more with inheritance? My example class:
```
public class BaseClass{
     public string MappedProp {get;set;}
     public virtual string NotBeMappedProp {get;set;}
}

public class Test : BaseClass{
     public string MappedProp {get;set;}
     [NotMapped]
     public override string NotBeMappedProp {get;set;}
}
```

2. `add-migration` not found entity framework on project. But I installed it already. Besides, I deleted all packages folder. However still continue same exception.

3. I open clean project but suprise... I have a new proplem. My foreign keys thrown an exception. 

> Unable to determine the principal end of an association between the types x1 and x2. The principal end of this association must be explicitly configured using either the relationship fluent API or data annotations.

My code part looking like that:
```
public class Student{
     .....
     public string Name {get;set;}
     public long? LocationId {get;set;}
     [ForeingKey("LocationId")]
     public Location Address {get;set;}
     ......
}
public class Location{
     public long Id {get;set;}
     ........
}
```
It is working with previous version.

4. I have no migration, I updated my database, check table but entity framework still said, there is an migration. 

> the model backing the context has changed since the database was created

**Comment by ajcvickers** [comment] 2018-01-05 20:58
@iozcelik There is not enough information here for us to be able to reproduce the problems you are seeing. Can you please post a runnable project/solution or code listing that demonstrates the issues? Also, what version were you using before the update to 6.2 and which database provider are you using?

**Comment by ajcvickers** [comment] 2018-01-12 19:48
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2018-01-12 19:48 UTC
