### ISSUE TITLE
-ConfigurationTypeName no longer working

### ISSUE THREAD

**Issue by joshdean2000** [aspnet/EntityFramework6#1359] opened 2019-10-07 14:24 UTC
After upgrading to EntityFramework 6.3 from 6.2 I can no longer generate SQL Scripts

### Steps to reproduce
Update-Database -ConfigurationTypeName Finivation.Concert.Configuration.EntityFramework.Migrations.Configuration -Script -SourceMigration: $InitialDatabase

Always returns "More than one migrations configuration type was found in the assembly 'Finivation.Concert.Configuration.EntityFramework'. Specify the name of the one to use."

**Comment by bricelam** [comment] 2019-10-07 19:38
Duplicate of #1296

**Closed by bricelam** 2019-10-07 19:38 UTC
