### ISSUE TITLE
6.3.0 Update-Database ignores the -ConfigurationTypeName parameter

### ISSUE THREAD

**Issue by sha0skywalker** [aspnet/EntityFramework6#1320] opened 2019-09-30 21:21 UTC
When using Update-Database to update the database, providing the -ConfigurationTypeName parameter doesn't do anything. 

If you have multiple contexts in a project, it will fail complaining that there are multiple configurations. Works fine if you only have a single context defined in the project. I reverted back to 6.2.0 and the Update-Database worked correctly when providing the -ConfigurationTypeName parameter.

### Further technical details
EF version: (found in project.csproj or packages.config)
Database Provider: (e.g. EntityFramework.SqlServer)
Operating system: (e.g. Windows 10) 
IDE: (e.g. Visual Studio 2017 15.6)

**Comment by bricelam** [comment] 2019-10-02 17:27
Duplicate of #1296

**Closed by bricelam** 2019-10-02 17:27 UTC
