### ISSUE TITLE
JsonIgnoreAttribute and ForeignKeyAttribute are mutually exclusive?

### ISSUE THREAD

**Issue by Pxtl** [aspnet/EntityFramework6#89] opened 2016-10-18 15:01 UTC
I'm using EntityFramework 6 to store objects, and Newtonsoft.Json to send them over the wire. 

I have an entity with a foreign key column where the column name does not match the table name, so I must use a ForeignKeyAttribute to point it out.  This entity also gets serialized using Newtonsoft.Json, and I'm using JsonIgnoreAttribute to suppress serialization of navigational properties.

Somehow, applying the Json and FK attributes fight.

On my entity I have 

```
    public int? StatusLookupID { get; set; }

    [ForeignKey(nameof(StatusLookupID))]
    public virtual Lookup Lookup { get; set; }
```

which works fine until I want to serialize it.

But then if I turn that into

```
    public int? StatusLookupID { get; set; }

    [JsonIgnore]
    [ForeignKey(nameof(StatusLookupID))]
    public virtual Lookup Lookup { get; set; }
```

then the error 

`System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while executing the command definition. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Invalid column name 'Lookup_LookupID'.`

appears when I attempt to load an instance of my object from the database.  Somehow Entity Framework 6 is fighting with the JsonIgnore attribute.  I remove the attribute and it correctly undersatnds that the navigational property is linked to StatusLookupID.  I put the JsonIgnoreAttribute on and it fails to see the ForeignKeyAttribute and instead infers the name "Lookup_LookupID".

**Comment by rowanmiller** [comment] 2016-10-25 17:26
Hey,

I wasn't able to reproduce this. Here is my attempt, I'm getting EF to spit out a script for what it expects the database to look like. As you can see, it's correctly picking up the foreign key property. Can you adjust the code (or post your own) to reproduce the issue.

> Console Application
.NET 4.6.1
EntityFramework 6.1.3
Newtonsoft.Json 9.0.1

```c#
using Newtonsoft.Json;
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace ConsoleApplication12
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var db = new BloggingContext())
            {
                Console.WriteLine(((IObjectContextAdapter)db).ObjectContext.CreateDatabaseScript());
            }
        }
    }

    public class BloggingContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Lookup> Lookups { get; set; }
    }

    public class Blog
    {
        public int BlogId { get; set; }

        public int? StatusLookupID { get; set; }

        [JsonIgnore]
        [ForeignKey(nameof(StatusLookupID))]
        public virtual Lookup Lookup { get; set; }
    }

    public class Lookup
    {
        public int LookupId { get; set; }

        public string Name { get; set; }
    }
}
```

Output:

```sql
create table [dbo].[Blogs] (
    [BlogId] [int] not null identity,
    [StatusLookupID] [int] null,
    primary key ([BlogId])
);
create table [dbo].[Lookups] (
    [LookupId] [int] not null identity,
    [Name] [nvarchar](max) null,
    primary key ([LookupId])
);
alter table [dbo].[Blogs] add constraint [Blog_Lookup] foreign key ([StatusLookupID]) references [dbo].[Lookups]([LookupId]);
```

**Comment by rowanmiller** [comment] 2016-10-31 18:17
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed by rowanmiller** 2016-10-31 18:17 UTC

**Comment by Pxtl** [comment] 2016-11-05 23:16
Sorry for throwing this issue over the wall and not following up, I'm getting slammed right now and I found a workaround (putting the attribute on the value property, not the navigational one).  When I have the time to produce a complete example and more environment information I'll send it along.

**Comment by WillemdeKok** [comment] 2017-05-04 07:40
I also encountered this issue, as soon as i add the JsonIgnore annotation my ForeignKey annotation is ignored. I added the JsonIgnore tag on the model that the foreign key belongs to, that provided a workaround. 

```C#
[ForeignKey("ClusterRefId")]
public virtual Cluster Cluster { get; set; }
```

```C#
[JsonIgnore]
[IgnoreDataMember]
public virtual ICollection<Customer> Customer { get; set; }
```
