### ISSUE TITLE
Random ERROR: The '"' character, hexadecimal value 0x22, cannot be included in a name - EF 6 Code First migrations.

### ISSUE THREAD

**Issue by EtharAlali** [aspnet/EntityFramework6#414] opened 2017-11-28 13:53 UTC
I've got a number of migration scripts on a DB. Whether running the update-database or through migrate.exe, one of them falls over with a totally random error and subsequent EF migrations fail to work (chronologically, they fail in the order of creation - which stands to reason):

```ERROR: The '"' character, hexadecimal value 0x22, cannot be included in a name. Line 71, position 16.```

None of the names of columns have the double quote '"' character in them. 

All migration scripts in the Designer.cs files are attributed:

```[GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]```

and the resx files are all seemingly correct. The script to migrate fails to add a column, which is interesting. We have an initial create (runs correctly) a number of intermediate scripts (which also run correctly) and this failing migration. 

The migration has little to it (namespaces removed for sensitivity).

```
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddSubsidyPaymentStatus : DbMigration
    {
        public override void Up()
        {
            AddColumn("Accounting.Account", "Status", subsidy => subsidy.Int(nullable: true, name: "PaymentStatus"));
        }
        
        public override void Down()
        {
            DropColumn("Accounting.Account", "Status");
        }
    }
```

The Designer code is:

```
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddSubsidyPaymentStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSubsidyPaymentStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201709251040106_AddSubsidyPaymentStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
```

And the .resx contains a perfectly reasonable, seemingly well formed XML doc when opened in VS.

It's not at all clear what causes this. The stack trace is:

```
Applying explicit migration: 201709211033245_InitialCreate.
Applying explicit migration: 201709251040106_AddSubsidyPaymentStatus.
System.Xml.XmlException: The '"' character, hexadecimal value 0x22, cannot be included in a name. Line 71, position 16.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.Throw(Int32 pos, String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
   at System.Data.Entity.Migrations.Edm.ModelCompressor.Decompress(Byte[] bytes)
   at System.Data.Entity.Migrations.DbMigration.GetModel(Func`2 modelAccessor)
   at System.Data.Entity.Migrations.DbMigration.GetTargetModel()
   at System.Data.Entity.Migrations.DbMigrator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.ApplyMigration(DbMigration migration, DbMigration lastMigration)
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.Infrastructure.MigratorScriptingDecorator.ScriptUpdate(String sourceMigration, String targetMigration)
   at System.Data.Entity.Migrations.Design.ToolingFacade.ScriptUpdateRunner.Run()
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Run(BaseRunner runner)
   at System.Data.Entity.Migrations.Design.ToolingFacade.ScriptUpdate(String sourceMigration, String targetMigration, Boolean force)
   at System.Data.Entity.Migrations.UpdateDatabaseCommand.<>c__DisplayClass2.<.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
The '"' character, hexadecimal value 0x22, cannot be included in a name. Line 71, position 16.
```

**Comment by ajcvickers** [comment] 2017-12-04 21:22
@EtharAlali Can you please post a runnable project/solution that reproduces what you are seeing?

**Comment by ajcvickers** [comment] 2017-12-18 19:39
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2017-12-18 19:39 UTC
