### ISSUE TITLE
Visual studio 2019 Professional and EntityFramework 6.1.3 throws errors when Generating script for code first migrations

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/EntityFramework6#944] opened 2019-06-25 23:50 UTC
I have a solution in Visual Studio 2019 Professional that runs on .NET Framework 4.5.2, MVC and EntityFramework 6.1.3

When i try generating database script with command below

```
Update-Database -Script -SourceMigration $InitialDatabase -ConfigurationTypeName Configuration
```

i get the following error

**Either the parameter @objname is ambiguous or the claimed @objtype (COLUMN) is wrong.**

This works like charm when running above script in Visual Studio 2017.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/574277/visual-studio-2019-professional-and-entityframewor.html
VSTS ticketId: 895725_
_These are the original issue comments:_

Visual Studio Feedback System on 5/20/2019, 02:47 AM (36 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 5/21/2019, 01:29 AM (35 days ago): <p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at:  https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq . In case you need answers to common questions or need assisted support, be sure to use  https://visualstudio.microsoft.com/vs/support/ . We'll keep you posted on any updates to this feedback.</p>

Sinan Altaii on 5/23/2019, 07:57 AM (33 days ago): <p>Do we have status for this? I cannot use VS 2019 professional :(</p>

_These are the original issue solutions:_
(no solutions)

**Comment by sinanaltaii** [comment] 2019-06-26 06:51
Would be really nice to have a fix for this, as for now i can only use VS2017 :(

**Comment by ajcvickers** [comment] 2019-06-26 18:17
Can you post a small, ruunable project/solution or complete code listing that demonstrates this behavior?

/cc @bricelam

**Comment by ajcvickers** [comment] 2019-08-06 18:16
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-08-06 18:16 UTC
