### ISSUE TITLE
Test Plan for EF6 on VS2017

### ISSUE THREAD

**Issue by lajones** [aspnet/EntityFramework6#156] opened 2016-12-16 00:55 UTC
Create a test plan for testing EF6 on VS2017 on each release. Test dimensions might include:

- Check that both EF5 and EF6 models can be created
- Check that both database-first and code-first models can be created
- Check that models work under Console App, WebApp and Website projects
- Check that models work under .NET Framework and .NET Core
- Create and run a simple end-to-end app that checks queries and updates against a simple DB e,g. Northwind
- Check UI windows: Designer, Toolbox, Model Browser, Mapping Window. Note that each of these need to be tested against different elements in the model: EntityTypes, Associations, Properties... 
- Check UI Dialogs E.g. to create Enums, Complex Types, Function Imports and Referential Integrity.
- Check model-wide UI features: e.g. Update Model from Database and Create Database from Model
- Setup testing: in particular check that upgrade from older releases works as expected.
- Localization - check that on non-English OS's you see the localized resources

**Comment by lincolnzocateli** [comment] 2017-04-13 03:30
![image](https://cloud.githubusercontent.com/assets/16601706/24980844/6270673a-1fb0-11e7-994f-2e1151edaa18.png)

I migrated a VS2015 application with EF6.1.3 to VS2017 (net461), but I am not able to do migrations and update-database

![image](https://cloud.githubusercontent.com/assets/16601706/24980893/9825ed6e-1fb0-11e7-8f25-b0cf56e2075b.png)

**Comment by lincolnzocateli** [comment] 2017-04-18 23:58
Yes, you can close this issue. 
I solved the problem by creating in the "Data" project an app.config file with the necessary data of EntityFramework 6.1.3
When I need to do migrations, just make this project a startup.

![image](https://cloud.githubusercontent.com/assets/16601706/25157765/a7b1f700-2479-11e7-810f-9bde487cf534.png)

**Comment by weitzhandler** [comment] 2017-05-11 01:46
YEAH me too.
Please ensure migrations work on VS 2017 for standalone WebAPI projects!

**Comment by Fryhard** [comment] 2017-06-15 14:12
To the issue that @lincolnzocateli reported, the problem seems to related to the lack of a StartupProject. 

In VS 2015 you were able to specify the Default Project on the Package Manager Console and VS would default to that project after showing a warning. 

It seems that this is broken in VS 2017 and the user will receive an error with message:
Exception calling "SetData" with "2" argument(s): "Type 'Microsoft.VisualStudio.Data.Tools.Package.Internal.OAProject' in assembly 'Microsoft.VisualStudio.Data.Tools.Package, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable."
At C:\Workspace\Projects\XXXX\main\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:720 char:5

Looking at EntityFramework.psm1 line 720 it relates to setting the startup project
    $domain.SetData('startUpProject', $startUpProject)

Based on this it looks like you have to pass the -StartupProject information to the update-database command.

e.g  update-database -script -StartupProject "XXXXX"

**Comment by weitzhandler** [comment] 2017-06-17 17:57
I can't understand why it has to be dependent in a start up proj

**Comment by LuckyURE** [comment] 2017-10-24 01:30
I just wanted to report that I'm having the same problem and am unable to resolve it.  Here are the steps I did to reproduce the problem:

Software Versions:
  - Visual Studio Community Edition 2017 15.4.1
  - .NET Framework v4.6.1

1) File | New Project | Visual C# | Cloud | Azure Functions
2) NuGet Install EntityFramework v6.1.3 & System.Data.Common v4.3.0
3) In Package Manager Console run:  Enable-Migrations
4) Receive the same error as above posts.
5) Tried Enable-Migrations -StartupProject MyProjectName & a bunch of other options
6) Still receive all the same errors.  Nothing works!

Any updates on how to get this working?  NOTE:  I did tried to install the beta version of EF v6.2.x but same problem so far.

**Comment by divega** [comment] 2018-05-09 03:55
Clearing up milestone because I am not sure there is any reason to leave this open left. @lajones if this is done, feel free to close it and mark it as fixed for 15.7.

If the purpose is to have a checklist for testing for every release, we should probably copy the contents to the wiki.

**Comment by ajcvickers** [comment] 2018-06-28 23:37
Putting in 6.3 to move content to wiki/docs.

**Closed** 2018-08-16 17:56 UTC
Labels: area-test, area-tools
