### ISSUE TITLE
Unable to use migrations

### ISSUE THREAD

**Issue by weitzhandler** [aspnet/EntityFramework6#317] opened 2017-07-14 03:08 UTC
Hi,

I have an ASP.NET Core project using EF 6.1.3, using VS 2017.

When I'm running `Enable-Migrations -Verbose`, I get the following error:

    Using StartUp project 'ConsoleApp1'.
    Using NuGet project 'WebApi'.
    Exception calling "SetData" with "2" argument(s): "Type 
    'Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject' in assembly 
    'Microsoft.VisualStudio.ProjectSystem.VS.Implementation, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked
    as serializable."
    At C:\Users\Shimmy\Documents\Visual Studio 2017\Projects\MyProject\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:718 char:5
    +     $domain.SetData('project', $project)
    +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
        + FullyQualifiedErrorId : SerializationException

    Exception calling "SetData" with "2" argument(s): "Type 
    'Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject' in assembly 
    'Microsoft.VisualStudio.ProjectSystem.VS.Implementation, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked
    as serializable."
    At C:\Users\Shimmy\Documents\Visual Studio 2017\Projects\MyProject\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:719 char:5
    +     $domain.SetData('contextProject', $contextProject)
    +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
        + FullyQualifiedErrorId : SerializationException

    System.NullReferenceException: Object reference not set to an instance of an object.
        at System.Data.Entity.Migrations.Extensions.ProjectExtensions.GetPropertyValue[T](Project project, String propertyName)
        at System.Data.Entity.Migrations.MigrationsDomainCommand.GetFacade(String configurationTypeName, Boolean useContextWorkingDirectory)
        at System.Data.Entity.Migrations.EnableMigrationsCommand.FindContextToEnable(String contextTypeName)
        at System.Data.Entity.Migrations.EnableMigrationsCommand.<>c__DisplayClass2.<.ctor>b__0()
        at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
    Object reference not set to an instance of an object.

- Is there any workaround for that?
- If migrations is not gonna happen, any recommendations on what to do when an update to the database is required?
- Any other things to consider while in this trap?
- Any ways to manually use [`DbMigrationsConfiguration<TContext>`](https://msdn.microsoft.com/en-us/library/hh829093) without automatic migrations?
- This is really outrageous, you're introducing a new technology (EF7) which is incomplete (Complex Types, TPT), then stop supporting the previous versions before it's even shipped!

**Comment by ajcvickers** [comment] 2017-07-17 19:48
@weitzhandler This is a duplicate of #231. EF6 should work fine with ASP.NET Core running on .NET Framework when using the traditional project system.

**Closed by ajcvickers** 2017-07-17 19:48 UTC

**Comment by weitzhandler** [comment] 2017-07-17 21:07
@ajcvickers it doesn't. Am I getting anything wrong? I'm using csproj files in VS 15.2.
I posted another comment [here](https://github.com/dotnet/project-system/issues/934#issuecomment-315884479).

**Comment by bricelam** [comment] 2017-07-17 21:35
*csproj files* is not the same as *the traditional project system*. (i.e. The file extension has little to do with the VS project type.) Ensure you're using this project type:
![image](https://user-images.githubusercontent.com/1226749/28290908-28b8a92e-6afd-11e7-8211-b028a4fe9617.png)

**Comment by weitzhandler** [comment] 2017-07-17 22:40
What can I do to migrate and existing csproj file to what's needed?

**Comment by bricelam** [comment] 2017-07-17 23:00
I would create a new one and copy your files into it. Anything else is probably more trouble than it's worth.

**Comment by weitzhandler** [comment] 2017-07-17 23:04
OMG
I have a lot of files, some of which are shared with other projects, what a mess.
But I still didn't figure what's the difference between the project files, aren't all project files *csproj*s?
Besides, you suggested creating a dll, while my project is a kestrel website.

**Comment by bricelam** [comment] 2017-07-18 03:46
> you suggested creating a dll, while my project is a kestrel website.

In order to use EF6 with ASP.NET Core, you'll need to move your DbContext and entity types to a classic class library. (aspnet/EntityFramework6#146)

**Comment by bricelam** [comment] 2017-07-18 03:54
> aren't all project files csprojs

Some *csproj* files are loaded using the old Visual Studio project system, and some are loaded using the [new project system](https://github.com/dotnet/project-system). All contain MSBuild-compatible XML.

**Comment by bricelam** [comment] 2017-07-18 03:59
Oh, I just remembered: You might be interested in the [mrahhal/Migrator.EF6](https://github.com/mrahhal/Migrator.EF6) project which allows you to manage EF6 Migrations using `dotnet ef` like on EF Core.

**Comment by weitzhandler** [comment] 2017-07-18 11:55
I think I'll extract the files into a class library, hope I'm gonna survive...

**Comment by iroshanAV** [comment] 2018-07-01 07:02
best solution is here :) 

https://developercommunity.visualstudio.com/content/problem/69983/enabling-ef-migrations-fails-with-error.html

**Comment by Oluyide** [comment] 2019-07-09 09:48
> I would create a new one and copy your files into it. Anything else is probably more trouble than it's worth.

This works for me

**Comment by Oluyide** [comment] 2019-07-09 09:48
> _csproj files_ is not the same as _the traditional project system_. (i.e. The file extension has little to do with the VS project type.) Ensure you're using this project type:
> 
> ![image](https://user-images.githubusercontent.com/1226749/28290908-28b8a92e-6afd-11e7-8211-b028a4fe9617.png)
Thank you for this.
