### ISSUE TITLE
Massive performance drop between EF 6.1.3 and 6.2.0, and x86 vs x64

### ISSUE THREAD

**Issue by Venemo** [aspnet/EntityFramework6#472] opened 2018-02-21 13:57 UTC
Hi,

I'm investigating some possibilities on (very) slow EF query compilation times. To isolate the problem, I created an empty console application and added an edmx with our model. (A rather complicated database with lots of tables and relationships.) I then wrote some code to measure the first query performance. (NOTE: I know that subsequent queries will be much faster, but my task was to investigate the performance of the first query.)

The code looks like this. (Table names are altered to hide corporate secrets of course, but you get the idea.)

```
using (var ctx = new MyEntities())
{
    var sw = new Stopwatch();
    sw.Start();

    var q = ctx.MyTable
        .Where(x => x.MyTableId.Contains("justanotherid"));

    var l = q.ToList();
    Console.WriteLine("Found {0} results.", l.Count);

    Console.WriteLine("First execution took {0} ms", sw.Elapsed.TotalMilliseconds.ToString());
    sw.Stop();
}
```

I experienced the following:

|Version| Debug x86 | Debug x64 |
|-----|-----|-----|
| EF 6.1.2 | 1600 ms | 2250 ms |
| EF 6.1.3 | 480 ms | 2200 ms |
| EF 6.2.0 | 1650 ms | 2250 ms |
| EF 6.2.0 (with pre-compiled views) | 1380 ms | 1840 ms |

Conclusions:

* There is a *~35%* performance drop between x86 and x64.
* There was a significant performance increase in 6.1.3 which was lost in 6.2.0
* Using pre-compiled views will give some, but not too much improvement

Can you guys please help find out what might be going wrong here?

**Comment by ajcvickers** [comment] 2018-03-06 02:21
@Venemo Thanks for reporting this. When you ask, "what might be going wrong here?" can you be more specific about what is going wrong? For example, are you asking about the what is wrong with x64 perf?

With regard to the specific perf improvement and subsequent change back to what it was before, my best guess would be that we broke something in 6.1.3, making it faster, that was then fixed in 6.2. However, to investigate this more we would need more information about the scenario you are running. Could you post a runnable project/solution that demonstrates the behavior so that we can investigate the root cause? Also, have you done any perf profiling? That might give an idea where to look.

**Comment by Venemo** [comment] 2018-03-13 11:26
@ajcvickers Unfortunately I don't work at that employer anymore (investigating the EF performance was my last task there), so I don't have a running project for you. However, all I did was created a model with the VS EF designer, and then ran the code that I posted above.

> Can you be more specific about what is going wrong?

We experienced that the first time query compilation was very slow in EF. In fact it turns out that this is a huge bottleneck for us. The question is whether or not there is anything we can do to improve it.

> Are you asking about the what is wrong with x64 perf?

That would be interesting to know (if you can tell), because we built all our projects for x64 and thus the bottleneck was even worse.

> Also, have you done any perf profiling?

Yes, but unfortunately I don't have the results anymore. All I remember is there was a recursive method in the query generator and that took most of the time.

Sorry I could not be more helpful, I'll ping one of my former collegaues to follow up with this issue.

**Comment by ajcvickers** [comment] 2018-06-28 23:41
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2018-06-28 23:41 UTC

**Comment by maxwell60701** [comment] 2020-01-15 08:22
Hi,I also have this problem the same as that guy  even if I use the version of 6.3 or 6.4,Can you guys please help me to  find out ?

**Comment by maxwell60701** [comment] 2020-01-15 08:23
Hi,I also have this problem the same as that guy  even if I use the version of 6.3 or 6.4,Can you guys please help me to  find out @ajcvickers
