### ISSUE TITLE
New-MigrationsRunner allows exceptions to cross AppDomain boundaries that are not serializable

### ISSUE THREAD

**Issue by WillSullivan** [aspnet/EntityFramework6#287] opened 2017-05-26 18:20 UTC
If the database seed method throws an exception when calling `update-database`, that exception is allowed to pass through the AppDomain to be caught and written to the host, [as can be seen here](https://github.com/aspnet/EntityFramework6/blob/527ae18fe23f7649712e9461de0c90ed67c3dca9/src/NuGet/EntityFramework/tools/EntityFramework.psm1#L598).

The problem is that sometimes these exceptions aren't serializable (and cannot be made so), which means the exception that gets reported is a SerializationException, which only reports the full name of the exception that was thrown, without any of the stuff you need to fix the problem.

I can't find the implementation of New-MigrationsRunner anywhere in this repository, so I cannot tell if this can be done, but, I'd suggest that the process in the second AppDomain catch any exception about to cross the border, check to see if it's [Serializable], and if not, call ToString() on it and pack that in an exception that is serializable for the trip back.

**Comment by ajcvickers** [comment] 2017-05-26 18:56
@WillSullivan We believe this is fixed in the 6.2 beta that was just released to NuGet. Can you try with that package and see if the issue is fixed for you?

**Comment by WillSullivan** [comment] 2017-05-26 18:59
Unfortunately, not in a timely manner, no.  It would be quicker to throw together a repro than get the codebase I'm working on updated with the beta.  I'll report back if I do try it out.

**Closed** 2017-06-05 18:51 UTC
Labels: type-investigation
