### ISSUE TITLE
Exception is NOT thrown when view is NOT found.

### ISSUE THREAD

**Issue by AdamHess** [aspnet/EntityFramework6#77] opened 2016-10-05 13:59 UTC
I defined a view that is defined on one of my databases and not on one of my other. 

I spend nearly an hour trying to figure out why the result set was returning zero items. 

After looking closer at my connection string I realized i was pointing at my staging and not development database where the view doesn't exist.

**Comment by rowanmiller** [comment] 2016-10-12 17:41
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean 😄... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).

**Comment by rowanmiller** [comment] 2016-10-19 18:28
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed by rowanmiller** 2016-10-19 18:28 UTC
