### ISSUE TITLE
EF 6 CodeFirst Migrations Detecting changes that don't exist

### ISSUE THREAD

**Issue by meywd** [aspnet/EntityFramework6#50] opened 2016-08-21 08:13 UTC
I have been using EF Migrations for a while in my current project and all was working great, that is until today, the situation is as follows:

 1. I made a small change of adding a string property
 2. I called an API method and got an error that there are changes in the model
 3. I ran the command "Add-Migration MigrationXYZ"
 4. A new migration is created with extra changes that didn't happen

I ran the "Add-Migration MigrationXYZ -Force" to make sure its not a one thing issue, I dropped the DB, restarted VS(2015) but all the same

Another issue is that even if I apply the migration as done by the scaffolder, an error still returns saying "Unable to update database to match the current model because there are pending changes..."

After looking at these changes, they all but one are about having a string property with the [Required] attribute and the scaffolder need to make it nullable, below is a sample.

    public partial class MigrationXYZ: DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Foos", "NewProperty", c => c.String());//<-- Expected Change
            AlterColumn("dbo.Bars", "Name", c => c.String());//<-- Unexpected Change
        }
        
        public override void Down()
        {
            AlterColumn("dbo.Bars", "Name", c => c.String(nullable: false));//<-- Unexpected Change
            DropColumn("dbo.Foos", "NewProperty");//<-- Expected Change
        }
    }

    public class Bar
    {
        //This was not touched in ages, some even before adding the first migration
        [Required]
        public string Name { get; set; }
    }

And now I am stuck and don't know how to fix this...Corruption in the Migration state

**Edit**

I have been trying to debug the `Add-Migration` command to understand why does EF see the model is different than it really is, but using EF source is not possible when you have dependencies like Identity which needs signed DLLs to work.

However additional research lead me to the [answer here][1] which leads to [this blog post][2] By @trailmax and the code to decipher the migrations hash, and with a little search in the EF source I made a small app to extract both the current model and the last migration model to compare side to side.

**The code to get the current model representation in XML**

    //Extracted from EF Source Code
    public static class DbContextExtensions
    {
        public static XDocument GetModel(this DbContext context)
        {
            return GetModel(w => EdmxWriter.WriteEdmx(context, w));
        }
        
        public static XDocument GetModel(Action<XmlWriter> writeXml)
        {
            using (var memoryStream = new MemoryStream())
            {
                using (var xmlWriter = XmlWriter.Create(
                    memoryStream, new XmlWriterSettings
                    {
                        Indent = true
                    }))
                {
                    writeXml(xmlWriter);
                }

                memoryStream.Position = 0;

                return XDocument.Load(memoryStream);
            }
        }
    }

            //In Program.cs
            using (var db = new DbContext())
            {
                var model = db.GetModel();
                using (var streamWriter = new StreamWriter(@"D:\Current.xml"))
                {
                    streamWriter.Write(model);
                }
            }

**The code to extract the model from the migration in XML**

    //Code from Trailmax Tech Blog
    public class MigrationDecompressor
    {
        public string ConnectionString { get; set; }

        public String DecompressMigrationFromSource(IMigrationMetadata migration)
        {
            var target = migration.Target;
            var xmlDoc = Decompress(Convert.FromBase64String(target));
            return xmlDoc.ToString();
        }

        public String DecompressDatabaseMigration(String migrationName)
        {
            var sqlToExecute = String.Format("select model from __MigrationHistory where migrationId like '%{0}'", migrationName);

            using (var connection = new SqlConnection(ConnectionString))
            {
                connection.Open();

                var command = new SqlCommand(sqlToExecute, connection);

                var reader = command.ExecuteReader();
                if (!reader.HasRows)
                {
                    throw new Exception("Now Rows to display. Probably migration name is incorrect");
                }

                while (reader.Read())
                {
                    var model = (byte[])reader["model"];
                    var decompressed = Decompress(model);
                    return decompressed.ToString();
                }
            }

            throw new Exception("Something went wrong. You should not get here");
        }

        /// <summary>
        /// Stealing decomposer from EF itself:
        /// http://entityframework.codeplex.com/SourceControl/latest#src/EntityFramework/Migrations/Edm/ModelCompressor.cs
        /// </summary>
        private XDocument Decompress(byte[] bytes)
        {
            using (var memoryStream = new MemoryStream(bytes))
            {
                using (var gzipStream = new GZipStream(memoryStream, CompressionMode.Decompress))
                {
                    return XDocument.Load(gzipStream);
                }
            }
        }
    }

            //Inside Program.cs

            var decompresser = new MigrationDecompressor
            {
                ConnectionString = "<connection string>"
            };

            var databaseSchemaRecord = decompresser.DecompressDatabaseMigration("<migration name>");
            using (var streamWriter = new StreamWriter(@"D:\LastMigration.xml"))
            {
                streamWriter.Write(databaseSchemaRecord);
            }

Unfortunately I still cannot find the issue, the only difference between the model and the one hashed with the last migration is the expected change of the added property, none of the unexpected changes show up, also after running the migration suggested by EF, then comparing the current model with the suggested migration, still the model doesn't match the changes, what should be not null is still not null in the model, while the suggested migration show it as nullable.

**The expected changes show up**

    <Property Name="NewProperty" Type="String" MaxLength="Max" FixedLength="false" Unicode="true" />
    .
    .
    .
    <ScalarProperty Name="NewProperty" ColumnName="NewProperty" />
    .
    .
    .
    <Property Name="NewProperty" Type="nvarchar(max)" Nullable="true" />

  [1]: http://stackoverflow.com/a/22703515/895167
  [2]: http://tech.trailmax.info/2014/03/inside_of_ef_migrations/

**Note**: this was also posted on [stackoverflow](http://stackoverflow.com/questions/39022877/ef-6-codefirst-migrations-detecting-changes-that-dont-exist)

**Comment by meywd** [comment] 2016-08-22 12:39
Finally found the issue, the `AssertThat` attribute from `ExpressiveAnnotations`, commenting the attribute solves the issue, however why is that so, is this a bug?

**Comment by divega** [comment] 2016-08-23 20:29
@meywd There is nothing obvious that could cause an attribute that EF doesn't reason about to cause spurious differences in the model to appear. Have you had other changes made? E.g. did you upgrade to a newer version of .NET Framework, Visual Studio/C# compiler or the JIT compiler?

Regardless, now that you have identified an attribute which causes spurious operations, would it be possible for you to provide a minimal repro that we can test internally?

**Comment by divega** [comment] 2016-08-29 18:35
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed by divega** 2016-08-29 18:35 UTC
