### ISSUE TITLE
One to One update

### ISSUE THREAD

**Issue by masterprogrammer513** [aspnet/EntityFramework6#97] opened 2016-11-04 11:45 UTC
Hello.
I can not update one to one relationship in EF.
Give me duplicated primary key error and if I remove the field the ef make it automatically !
This error returned this is not insert only update one field in another table.
Model: 
modelBuilder.Entity<ApplicationUser>()
               .HasOptional(e => e.UsersProfiles)
               .WithRequired(e => e.User)
               .WillCascadeOnDelete(false);

Violation of PRIMARY KEY constraint 'PK_dbo.UsersProfiles'. Cannot insert duplicate key in object 'dbo.UsersProfiles'. The duplicate key value is (ae0e7068-ffbb-4261-a354-0e39aa1b38ee).
The statement has been terminated.

**Comment by AlbertoMonteiro** [comment] 2016-11-04 12:20
**EF Team Triage**: This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
> 
> Ideally include a complete code listing that we can run to reproduce the issue.
> Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean 😄... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).

**Comment by cinohee** [comment] 2016-11-04 12:28
I can update field in database directly but I can not update field by EF
full code is this `
//error happen here or  any update database command  application user is standard Identityclass that map to new name User       
       var result = await UserManager.ChangePasswordAsync(User.Identity.GetUserId(), model.OldPassword, model.NewPassword);

namespace dbModel
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class UsersProfile
    {
        public string id { get; set; }

        
        public string name { get; set; }

        
        public string family { get; set; }

        
        public string nickName { get; set; }

        public bool receiveNewsletterEmail { get; set; }

        public DateTime? dateOfBirth { get; set; }

        public bool? sex { get; set; }

        
        public string nationalCode { get; set; }

        
        public string city { get; set; }

        
        public string address { get; set; }

        public DateTime? registerDate { get; set; }

        public DateTime? lastUpdateDate { get; set; }

        [Required]
        public virtual ApplicationUser User { get; set; }
    }
}

public ApplicationUser()
        {
 public virtual UsersProfile UsersProfiles { get; set; }
}
       
`

**Comment by ajcvickers** [comment] 2019-03-18 22:18
@masterprogrammer513 I am still not able to reproduce this behavior. Can you post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

**Comment by ajcvickers** [comment] 2019-06-26 18:32
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-06-26 18:32 UTC
Labels: blocked
