### ISSUE TITLE
Failed to run migrate.exe with error "ERROR: Value cannot be null. Parameter name: String"

### ISSUE THREAD

**Issue by dragonsappire** [aspnet/EntityFramework6#674] opened 2018-12-12 17:20 UTC
Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

When running cmd ‘migrate.exe XXX.dll /connectionString="Server=tcp:xxx.database.chinacloudapi.cn,1433;Initial Catalog=xxx_prerelease;Persist Security Info=False;User ID=xxx;Password=xxx;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30" /connectionProviderName="System.Data.SqlClient" /force  ’
```
Exception message:
ERROR: Value cannot be null.
Parameter name: String
Stack trace:
```

### Steps to reproduce

run migrate.exe command under bin\Release folder

```

### Further technical details
EF version: (EntityFramework.6.2.0)
Operating system: (e.g. Windows 7) 

When I use "Update-database" in package management console, it is ok.

But I need to do some automation work, so I have to use cmd for upgrading.

**Comment by ajcvickers** [comment] 2019-03-19 20:44
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment] 2019-06-26 18:57
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-06-26 18:57 UTC
Labels: blocked
