### ISSUE TITLE
EntityFramework.6.4.0-preview1 add-migration issus

### ISSUE THREAD

**Issue by neozhu** [aspnet/EntityFramework6#1386] opened 2019-10-16 05:29 UTC
PM> add-migration md47
Exception calling "LoadFrom" with "1" argument(s): "Could not load file or assembly 
'file:///D:\tfsonline\opensource\SmartCode-Engine\CustomBasicScaffolder\packages\EntityFramework.6.4.0-preview1-19506-01\tools\EntityFramework.PowerShell.Utility.dll' or one of its 
dependencies. The system cannot find the file specified."
At D:\tfsonline\opensource\SmartCode-Engine\CustomBasicScaffolder\packages\EntityFramework.6.2.0\tools\EntityFramework.psm1:782 char:5
+     $utilityAssembly = [System.Reflection.Assembly]::LoadFrom((Join-P ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException
 
You cannot call a method on a null-valued expression.
At D:\tfsonline\opensource\SmartCode-Engine\CustomBasicScaffolder\packages\EntityFramework.6.2.0\tools\EntityFramework.psm1:783 char:5
+     $dispatcher = $utilityAssembly.CreateInstance(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Exception calling "CreateInstanceFrom" with "8" argument(s): "Could not load file or assembly 
'file:///D:\tfsonline\opensource\SmartCode-Engine\CustomBasicScaffolder\packages\EntityFramework.6.4.0-preview1-19506-01\tools\EntityFramework.PowerShell.dll' or one of its 
dependencies. The system cannot find the file specified."
At D:\tfsonline\opensource\SmartCode-Engine\CustomBasicScaffolder\packages\EntityFramework.6.2.0\tools\EntityFramework.psm1:811 char:5
+     $domain.CreateInstanceFrom(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException

**Comment by neozhu** [comment] 2019-10-16 06:11
"EntityFramework" version="6.3.0-beta1-62412" add-migration is work
6.3,6.4-pre has bug

**Comment by neozhu** [comment] 2019-10-16 06:15
why not found EntityFramework.PowerShell.dll,EntityFramework.PowerShell.Utility.dll,migrate.exe files in
packages\EntityFramework.6.4.0-preview1-19506-01\tools\ and packages\EntityFramework.6.3.0\tools\

**Comment by bricelam** [comment] 2019-10-16 22:21
Duplicate of 1294?

**Closed** 2019-10-16 23:43 UTC
