### ISSUE TITLE
Cant run EF 6.2.0 code first migrations on VSTS using migrate.exe

### ISSUE THREAD

**Issue by rohitiscancerian** [aspnet/EntityFramework6#643] opened 2018-10-06 18:08 UTC
I get the following error when I run the migrate.exe on VSTS with following arguments. I have no clue what the error is suggesting. My.dll is in the same directory as migrate.exe.

D:\a\r1\a_Build My API\drop\Migrations\migrate.exe" My.dll /connectionString="Server=tcp:sqlserv-XXXX.database.windows.net,1433;Initial Catalog=sqldb-portal;Persist Security Info=False;User ID=sqluseracct;Password=mypass;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;" /connectionProviderName="System.Data.SqlClient" /startUpConfigurationFile:"My.dll.config" /verbose

```
Exception message:

2018-10-06T17:22:15.2556319Z System.Data.Entity.Migrations.Design.ToolingException: The type initializer for 'System.Data.Entity.Migrations.DbMigrationsConfiguration1' threw an exception.
2018-10-06T17:22:15.2556933Z    at System.Data.Entity.Migrations.Design.ToolingFacade.Run(BaseRunner runner)
2018-10-06T17:22:15.2557546Z    at System.Data.Entity.Migrations.Console.Program.Run()
2018-10-06T17:22:15.2557722Z    at System.Data.Entity.Migrations.Console.Program.Main(String[] args)
2018-10-06T17:22:15.2557855Z ERROR: The type initializer for 'System.Data.Entity.Migrations.DbMigrationsConfiguration1' threw an exception.
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

### Further technical details
EF version: EntityFramework.6.2.0
Database Provider: (e.g. EntityFramework.SqlServer)

**Comment by rikrak** [comment] 2018-10-23 14:04
does "my.dll" depend on another assembly?  It could be that the runtime cannot load a dependency of my.dll

**Comment by ajcvickers** [comment] 2019-03-18 23:35
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment] 2019-06-26 18:55
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-06-26 18:55 UTC
Labels: blocked
