### ISSUE TITLE
API that has custom schema, falls back to DefaultSchema if initialized via another Application or Service

### ISSUE THREAD

**Issue by tiwari-abhishek** [aspnet/EntityFramework6#573] opened 2018-07-03 18:07 UTC
**Describe what is not working as expected.**
I have a Service (has API + UI) that uses a custom EF Schema name. A strange issue happens when the service hasn't been initialized or accessed yet, because of a redeployment, IIS or AppPool reset .

If I call the Application first, which then invokes the service, for whatever reason, the service defaults to expecting a "dbo" schema. The "dbo" schema doesn't exist and I never created it. I have a custom schema for the service. So the service complains that it did not find the "dbo" schema and fails to return results, totally ignoring what I have specified as the schema name in code.

To fix this, I have make sure every time, that before the application calls the service, I first warm up the service, by hitting its UI or API endpoints first. When I do this, the service picks up my Custom Schema name and it works fine. So when my application calls this pre-initialized service, it is able to find the tables under my Custom Schema and returns results.

The only difference in these two cases is that, the service can work with the database only if it was invoked separately first, followed by subsequent application calls. However, if it was initialized as a result of a first call from application, it goes looking for "dbo" schema and complains when it doesnt find a table under "dbo" schema.

I tried setting  `Database.SetInitializer<MyDbContext>(null);` to disable automatic migrations but that didn't work.

The only place that I could find the string "dbo" getting mentioned is the ".resx" file of my first migration (I only have one right now). I assume it was auto-generated when I called "Add-Migration".

I haven't tried changing the ".resx" file DefaultSchema entry manually, as the migration is already applied, and it would be a dirty trick even if it worked.

Is there a way to control the schema name when calling "Add-Migration"? 

If you are seeing an exception, include the full exceptions details (message and stack trace).
```System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while executing the command definition. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Invalid object name 'dbo.MyTable'.```

### Further technical details
EF version: 6.2.0
Database Provider: (EntityFramework.SqlServer)
Operating system: (Windows 10) 
IDE: (Visual Studio 2017 15.6)

**Comment by ajcvickers** [comment] 2018-07-06 17:45
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment] 2018-07-27 16:01
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2018-07-27 16:01 UTC
