### ISSUE TITLE
Update-Database failing in 6.3.0

### ISSUE THREAD

**Issue by nprieto95** [aspnet/EntityFramework6#1306] opened 2019-09-27 03:43 UTC
I launch the Package Manager console, select the project which contains my migrations, and run `Update-Database`

Expected behavior: the database gets migrated.

Actual behavior:

![image](https://user-images.githubusercontent.com/33283964/65740383-edd3ce80-e0be-11e9-839e-346acbb64d3e.png)

```
PM> Update-Database
Update-Database : Cannot bind argument to parameter 'Path' because it is null.
At line:1 char:1
+ Update-Database
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Update-Database], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Update-Database
```

### Further technical details
EF version: 6.3.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10 
IDE: Visual Studio 2019 16.2.5

**Comment by ErikEJ** [comment] 2019-09-27 05:43
Dupe of #49

**Comment by nprieto95** [comment] 2019-09-27 05:48
Is it possible you might have mistyped the number? #49 is talking about DateTime and an upgrade to SQL Server 2016; I honestly don't see the relationship with this issue

**Comment by ErikEJ** [comment] 2019-09-27 06:16
Try a search for the error message

**Comment by neozhu** [comment] 2019-09-27 10:30
> I launch the Package Manager console, select the project which contains my migrations, and run `Update-Database`
> 
> Expected behavior: the database gets migrated.
> 
> Actual behavior:
> 
> ![image](https://user-images.githubusercontent.com/33283964/65740383-edd3ce80-e0be-11e9-839e-346acbb64d3e.png)
> 
> ```
> PM> Update-Database
> Update-Database : Cannot bind argument to parameter 'Path' because it is null.
> At line:1 char:1
> + Update-Database
> + ~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidData: (:) [Update-Database], ParameterBindingValidationException
>     + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Update-Database
> ```
> 
> ### Further technical details
> EF version: 6.3.0
> Database Provider: EntityFramework.SqlServer
> Operating system: Windows 10
> IDE: Visual Studio 2019 16.2.5

 add-migration command execute succeed? I have exceptions for add-migration execution.

**Comment by bricelam** [comment] 2019-09-27 22:42
Duplicate of #1290?

**Closed** 2019-09-30 18:36 UTC
