### ISSUE TITLE
Issue with SQL table name generation

### ISSUE THREAD

**Issue by magcius** [aspnet/EntityFramework6#528] opened 2018-04-27 04:39 UTC
I'm new to Entity Framework. I'm seeing what I believe to be a bug when it generates the table name. I have inherited a codebase that is using EF Designer for its models (EDMX). I have an Entity Type named "DbGame", which has an Entity Set Name of "DbGames". The Model Viewer in Visual Studio shows that the table for this entity should be called "DbGame":

![image](https://user-images.githubusercontent.com/40890/39344856-d816bec6-4999-11e8-96b4-d6fa231a807b.png)

However, the generated table name seems to be "DbGames":

![image](https://user-images.githubusercontent.com/40890/39344869-ede6b134-4999-11e8-81c2-6cf58a3a8c78.png)

The MSL file for the entity looks like this. Again suggesting the table should be called "DbGame", not "DbGames":

![image](https://user-images.githubusercontent.com/40890/39344908-3a2c274a-499a-11e8-9d27-8c94f5011584.png)

The end result is that at runtime, EntityFramework tries to look for a table named "DbGame", while it has tried to generate "DbGame".

### Steps to reproduce

Unfortunately, I cannot share any source code other than the above screenshots. However, I will happily try troubleshooting steps.

### Further technical details
EF version: 6.2.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: 15.6.6

**Comment by Rhino95** [comment] 2018-04-27 16:16
The setting you are looking for is 
entity framework plural table names - Stack ...
https://stackoverflow.com › questions › e...


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: "Jasper St. Pierre" <notifications@github.com> Date: 2018/04/27  06:39  (GMT+02:00) To: aspnet/EntityFramework6 <EntityFramework6@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [aspnet/EntityFramework6] Issue with SQL table name generation (#528) 
I'm new to Entity Framework. I'm seeing what I believe to be a bug when it generates the table name. I have inherited a codebase that is using EF Designer for its models (EDMX). I have an Entity Type named "DbGame", which has an Entity Set Name of "DbGames". The Model Viewer in Visual Studio shows that the table for this entity should be called "DbGame":

However, the generated table name seems to be "DbGames":

The MSL file for the entity looks like this. Again suggesting the table should be called "DbGame", not "DbGames":

The end result is that at runtime, EntityFramework tries to look for a table named "DbGame", while it has tried to generate "DbGame".
Steps to reproduce
Unfortunately, I cannot share any source code other than the above screenshots. However, I will happily try troubleshooting steps.
Further technical details
EF version: 6.2.0

Database Provider: EntityFramework.SqlServer

Operating system: Windows 10

IDE: 15.6.6

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/aspnet/EntityFramework6","title":"aspnet/EntityFramework6","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/aspnet/EntityFramework6"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Issue with SQL table name generation (#528)"}],"action":{"name":"View Issue","url":"https://github.com/aspnet/EntityFramework6/issues/528"}}}

**Comment by ajcvickers** [comment] 2018-07-06 17:20
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment] 2018-07-27 15:59
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2018-07-27 15:59 UTC
