### ISSUE TITLE
Regression in 6.2.0: Contains(...) gives NullReferenceException (works in 6.1.3)

### ISSUE THREAD

**Issue by pascalhaakmat** [aspnet/EntityFramework6#445] opened 2018-01-15 22:56 UTC
In 6.2.0 a query containing .Contains(...) throws a NullReferenceException when performing .Count() on the query.

For example:

	using (var pdc = new DbContext())
	{
		var q = pdc.Books.Where(o => o.Title.Contains("search"));
		q.Count();
	}

This code works in 6.1.3 but throws the below stacktrace in 6.2.0:

    System.NullReferenceException: Object reference not set to an instance of an object
      at System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodCall (System.Linq.Expressions.Expression obj, System.Reflection.MethodInfo method, System.Linq.Expressions.IArgumentProvider methodCallExpr, System.Linq.Expressions.Compiler.LambdaCompiler+CompilationFlags flags) [0x00002] in <521f3fe476f34ea88748e97b3b984d05>:0 
      at System.Linq.Expressions.Compiler.LambdaCompiler.EmitInvocationExpression (System.Linq.Expressions.Expression expr, System.Linq.Expressions.Compiler.LambdaCompiler+CompilationFlags flags) [0x0002d] in <521f3fe476f34ea88748e97b3b984d05>:0 
      at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression (System.Linq.Expressions.Expression node, System.Linq.Expressions.Compiler.LambdaCompiler+CompilationFlags flags) [0x00263] in <521f3fe476f34ea88748e97b3b984d05>:0 
      at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression (System.Linq.Expressions.Expression node) [0x00000] in <521f3fe476f34ea88748e97b3b984d05>:0 
      at System.Linq.Expressions.Compiler.LambdaCompiler.EmitInstance (System.Linq.Expressions.Expression instance, System.Type& type) [0x00035] in <521f3fe476f34ea88748e97b3b984d05>:0 
      at System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberExpression (System.Linq.Expressions.Expression expr) [0x00018] in <521f3fe476f34ea88748e97b3b984d05>:0 
      at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression (System.Linq.Expressions.Expression node, System.Linq.Expressions.Compiler.LambdaCompiler+CompilationFlags flags) [0x00288] in <521f3fe476f34ea88748e97b3b984d05>:0 
      at System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaBody (System.Linq.Expressions.Compiler.CompilerScope parent, System.Boolean inlined, System.Linq.Expressions.Compiler.LambdaCompiler+CompilationFlags flags) [0x00085] in <521f3fe476f34ea88748e97b3b984d05>:0 
      at System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaBody () [0x0001a] in <521f3fe476f34ea88748e97b3b984d05>:0 
      at System.Linq.Expressions.Compiler.LambdaCompiler.Compile (System.Linq.Expressions.LambdaExpression lambda) [0x0000d] in <521f3fe476f34ea88748e97b3b984d05>:0 
      at System.Linq.Expressions.LambdaExpression.Compile (System.Boolean preferInterpretation) [0x00000] in <521f3fe476f34ea88748e97b3b984d05>:0 
      at System.Linq.Expressions.LambdaExpression.Compile () [0x00000] in <521f3fe476f34ea88748e97b3b984d05>:0 
      at System.Data.Entity.Core.Objects.ELinq.QueryParameterExpression.EvaluateParameter (System.Object[] arguments) [0x0008d] in <b7b192e5a05f4f14a14aa0d5b14aeeeb>:0 
      at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan (System.Nullable`1[T] forMergeOption) [0x002e5] in <b7b192e5a05f4f14a14aa0d5b14aeeeb>:0 
      at System.Data.Entity.Core.Objects.ObjectQuery`1+<>c__DisplayClass7[T].<GetResults>b__6 () [0x0000b] in <b7b192e5a05f4f14a14aa0d5b14aeeeb>:0 
      at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T] (System.Func`1[TResult] func, System.Data.Entity.Infrastructure.IDbExecutionStrategy executionStrategy, System.Boolean startLocalTransaction, System.Boolean releaseConnectionOnSuccess) [0x0008a] in <b7b192e5a05f4f14a14aa0d5b14aeeeb>:0 
      at System.Data.Entity.Core.Objects.ObjectQuery`1+<>c__DisplayClass7[T].<GetResults>b__5 () [0x00033] in <b7b192e5a05f4f14a14aa0d5b14aeeeb>:0 
      at System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult] (System.Func`1[TResult] operation) [0x00000] in <b7b192e5a05f4f14a14aa0d5b14aeeeb>:0 
      at System.Data.Entity.Core.Objects.ObjectQuery`1[T].GetResults (System.Nullable`1[T] forMergeOption) [0x00093] in <b7b192e5a05f4f14a14aa0d5b14aeeeb>:0 
      at System.Data.Entity.Core.Objects.ObjectQuery`1[T].<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0 () [0x00000] in <b7b192e5a05f4f14a14aa0d5b14aeeeb>:0 
      at System.Data.Entity.Internal.LazyEnumerator`1[T].MoveNext () [0x00008] in <b7b192e5a05f4f14a14aa0d5b14aeeeb>:0 
      at System.Linq.Enumerable.Single[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0003d] in <521f3fe476f34ea88748e97b3b984d05>:0 
      at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<GetElementFunction>b__3[TResult] (System.Collections.Generic.IEnumerable`1[T] sequence) [0x00000] in <b7b192e5a05f4f14a14aa0d5b14aeeeb>:0 
      at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult] (System.Collections.Generic.IEnumerable`1[T] query, System.Linq.Expressions.Expression queryRoot) [0x00006] in <b7b192e5a05f4f14a14aa0d5b14aeeeb>:0 
      at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult] (System.Linq.Expressions.Expression expression) [0x00014] in <b7b192e5a05f4f14a14aa0d5b14aeeeb>:0 
      at System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult] (System.Linq.Expressions.Expression expression) [0x00022] in <b7b192e5a05f4f14a14aa0d5b14aeeeb>:0 
      at System.Linq.Queryable.Count[TSource] (System.Linq.IQueryable`1[T] source) [0x0002f] in <521f3fe476f34ea88748e97b3b984d05>:0

**Comment by motownandy** [comment] 2018-01-24 12:23
that is odd that this is happening. you could help yourself by putting a .ToList() at the end. As your goal is to get the count of the books try use this method as it gets just the count result without loading the books data for faster performance (just in case you only need the count in this case) https://msdn.microsoft.com/en-us/library/jj574232(v=vs.113).aspx#Anchor_3 .

**Comment by pascalhaakmat** [comment] 2018-02-08 07:22
Adding .ToList() does not solve the problem at all. The problem happens before that, in the expression evaluator.

This is still a vexing problem. Any other recommendations for a workaround?

**Comment by ajcvickers** [comment] 2018-08-24 21:58
@pascalhaakmat Sorry for the slow response. I have not been able to reproduce this issue--my code is below. Can you please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

```C#
namespace SizTwoRider
{
    public class Book
    {
        public int Id { get; set; }
        public string Title { get; set; }
    }
   
    public class SizTwoContext : DbContext
    {
        static SizTwoContext()
        {
            Database.SetInitializer(new DropCreateDatabaseAlways<SizTwoContext>());
        }

        public SizTwoContext()
            : base(@"Server=(localdb)\mssqllocaldb;Database=SixTwo;ConnectRetryCount=0")
        {
        }

        public DbSet<Book> Books { get; set; }
    }

    public class Program
    {
        public static void Main()
        {
            using (var context = new SizTwoContext())
            {
                context.Books.Add(new Book {Title = "findme search findme"});
                context.Books.Add(new Book {Title = "dontfindme"});
                context.Books.Add(new Book( ));

                context.SaveChanges();
            }

            using (var context = new SizTwoContext())
            {
                var q = context.Books.Where(o => o.Title.Contains("search"));

                Console.WriteLine(q.Count());
            }
        }
    }
}
```

**Comment by MaximLipnin** [comment] 2019-03-06 12:36
Hello, it looks like [this](https://github.com/mono/mono/issues/13298#issuecomment-469693976) is a good repro sample.

**Comment by ajcvickers** [comment] 2019-03-18 22:48
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment] 2019-03-18 22:49
Closing this as external as the only repro we have points to it being an issue with the mono expression compiler.

**Closed by ajcvickers** 2019-03-18 22:48 UTC
Labels: blocked
