### ISSUE TITLE
Entity Framework Relationship Fix-up Failure

### ISSUE THREAD

**Issue by john-larson** [aspnet/EntityFramework6#592] opened 2018-08-14 00:02 UTC
For the below code, the expected behavior of EF is to commit order and the `orderItem` with `orderID=100` and as far as I know, this auto assignment of the field `orderID` is known as relatinship fix-up. So, we do not have to provide the `orderID` field for the `orderItem` to be added.          

            Entities ctx = new Entities();

            Order order = new Order()
            {
                ID = 100,
                name = "abc"
            };
 
            // ID field of OrderItem is auto-increment and the primary field
            //OrderItem is a navigation property of Order through the orderID field
            OrderItem orderItem = new OrderItem ()
            {
                name = "oi_abc"
            };
            order.OrderItems.Add(orderItem);

            ctx.Orders.Add(order);
            ctx.SaveChanges();

This piece of sample code works as expected. But the problem is, a similar piece of code in our project fails to do proper relationship fix-up. (I know it would be best if I could provide the whole code but it is impossible due to other complexities of the code and database and also due to our company policy.)

The code in our project simply sets `orderID` as 0 during commit. 

Some important things to note:

 1. We do not disable tracking changes of the context anywhere
 2. Setting orderID manually works but it is not desired for us
 3. If we have the `ctx.Orders.Add(order);` line right after creating the `order` object, then it work as expected.

Do you have any guesses as to why such a failure would happen, given the circumstances above? Especially given the third bullet point, can this be a bug?

**Comment by ajcvickers** [comment] 2018-08-14 15:28
@john-larson The only thing that comes to mind is that fixup does not work fully when the same property is shared my multiple FKs. Other than that, it could be a bug, but we would need code to reproduce the behavior in order to confirm this.

**Comment by john-larson** [comment] 2018-08-16 03:35
@ajcvickers Thanks for the prompt response. 
> The only thing that comes to mind is that fixup does not work fully when the same property is shared my multiple FKs. 

How can I check if this is the case?

I also tried to debug using the EF source code but to no avail. I guess the relevant code is inside the `ObjectStateManager.DetectChanges` method but the property in the dependent entity does not change before all is committed, so I could not figure out what to look for during the DetectChanges method.

**Comment by ajcvickers** [comment] 2018-08-16 15:46
@john-larson It should be apparent from the model if the same property is being used in multiple foreign keys, either in the Code First configuration or in the EDMX, depending which you are using.

**Comment by john-larson** [comment] 2018-08-16 16:28
We are using db first edmx. Going by the sample code I provided, double click the OrderItem entity, clicking on the Navigation properties in the diagram shows the property used and only the Order navigation property uses the orderID property. Is this what you meant I should check?

**Comment by ajcvickers** [comment] 2018-08-16 16:38
@john-larson It didn't occur to me to look at it in the designer, but yes that should be the same as looking directly in the EDMX.

**Comment by ajcvickers** [comment] 2019-03-18 23:20
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-03-18 23:20 UTC
