### ISSUE TITLE
netstandard 2.0 or netcore 2.0

### ISSUE THREAD

**Issue by springy76** [aspnet/EntityFramework6#383] opened 2017-10-20 10:57 UTC
Portability analyzer of EF6 reports 95.50% for netstandard2.0 and 98.38% for netcore2.0.
Please reconsider if EF6 could be ported the these "platforms" nowadays.

Of course I know that EFcore exists, but it is rewritten from scratch and therefore has all problems all rewritten-from-scratch software has: Missing features, new bugs, old bugs reintroduced, different unforeseeable behaviors, ...

**Comment by ajcvickers** [comment] 2017-10-20 16:47
@springy76 Thanks for the feedback--this is something we are considering, which is why #271 is not closed. Form an issue tracking perspective, I'm closing this as a duplicate of #271.

**Closed by ajcvickers** 2017-10-20 16:47 UTC
