### ISSUE TITLE
Generic Error on EF with Oracle

### ISSUE THREAD

**Issue by kmilovm** [aspnet/EntityFramework6#349] opened 2017-08-30 14:14 UTC
Every single error on any process reports the following:

Type is not resolved for member Oracle.ManagedDataAccess.Client.OracleException,Oracle.ManagedDataAccess, Version=4.122.1.0, Culture=neutral, PublicKeyToken=89b483f429c47342'

would be so easy for us as developers to have the real error on database operations (it appears when adding migration, executing seeding or any other initial step with EF)

**Comment by ajcvickers** [comment] 2017-08-30 17:52
@kmilovm This is an exception coming from the Oracle provider; please follow up with them. Closing this for now--if it turns out that this is caused by an issue in EF, then please re-open with full details.

**Closed by ajcvickers** 2017-08-30 17:52 UTC
