### ISSUE TITLE
Creating new object tries to create existing referenced objects

### ISSUE THREAD

**Issue by Jbonavita** [aspnet/EntityFramework6#1360] opened 2019-10-07 16:29 UTC
This is truly one of the strangest issues I've run into. 

I have a Web API which uses EF. I have an audit table which takes an ApplicationUser. I create the new object, add it to the collection and then call SaveChangesAsync(). The weird part is, I get "User name MyUserName is already taken." error.

    using (var context = new ApplicationDbContext())
	{
		var user = context.Users.Single<ApplicationUser>(x => x.UserName == model.UserName);

		var sid = context.SessionIds.FirstOrDefault(x => x.Id == model.SessionId);

		var audit = new Audit
		{
			Data = model.Data,
			User = user,
			IpAddress = Helper.GetClientIp(Request),
			Session = sid != null ? sid : ItsMyChance.Entities.Entities.SessionId.Create(scoreModel.UserName, scoreModel.GameId)
		};

		context.Audits.Add(audit);
		await context.SaveChangesAsync();
	}

This code has been working for years. The difference is I upgrade from .NET 4.5 to .NET 4.61

I also tried the following but still receive the same error

        [ForeignKey("User")]
        public string UserId { get; set; }

        public ApplicationUser User { get; set; }

Trying to track this issue down I call

    var entries = context.ChangeTracker.Entries();

It returns several entries, 1 for each object, including User. User shows Added and another as Unchanged. I can't figure out how this is happening.

In addition, I added the following before making any changes but there's no effect.

    context.Configuration.AutoDetectChangesEnabled = false;

**Comment by ajcvickers** [comment] 2019-10-14 23:26
@Jbonavita Please post a small, runnable project/solution or complete code listing that reproduces the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-10-21 16:37
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-10-21 16:37 UTC
