### ISSUE TITLE
SetClause value is empty when using EdmFunctions in Interceptor

### ISSUE THREAD

**Issue by balticer** [aspnet/EntityFramework6#371] opened 2017-10-04 12:19 UTC
Hi,

i tried to implement a ModifiedInterceptor and want to use database based UTC-date, like GETUTCDATE() in T-SQL, but the generated SQL is empty. I tried to use EdmFunctions.CurrentUtcDateTime(). See code below. The output including the generated SQL is:

``` SQL
UPDATE [dbo].[ProductionSite]
SET [Latitude] = @0, [Picture] = @1, [Modified] = 
WHERE ([Id] = @2)

2017-10-04 14:15:15.1352|DEBUG|EntityFramework|-- @0: '1' (Type = Double)

2017-10-04 14:15:15.1352|DEBUG|EntityFramework|-- @1: 'System.Byte[]' (Type = Binary, Size = -1)

2017-10-04 14:15:15.1352|DEBUG|EntityFramework|-- @2: '87b042ae-5c3a-43e9-99b5-8fd4f9f41b7c' (Type = Guid)

2017-10-04 14:15:15.1352|DEBUG|EntityFramework|-- Executing at 04.10.2017 14:15:15 +02:00

2017-10-04 14:15:15.1506|DEBUG|EntityFramework|-- Failed in 11 ms with error: Incorrect syntax near the keyword 'WHERE'.

2017-10-04 14:15:15.1506|DEBUG|EntityFramework|

2017-10-04 14:15:15.1576|DEBUG|EntityFramework|Closed connection at 04.10.2017 14:15:15 +02:00
```
As you can see the function call is missing.

``` csharp
    /// <summary>
    /// Implements a modified pattern.
    /// </summary>
    /// <seealso cref="System.Data.Entity.Infrastructure.Interception.IDbCommandTreeInterceptor" />
    public class ModifiedInterceptor
        : IDbCommandTreeInterceptor
    {
        /// <summary>
        /// This method is called after a new <see cref="T:System.Data.Entity.Core.Common.CommandTrees.DbCommandTree" /> has been created.
        /// The tree that is used after interception can be changed by setting
        /// <see cref="P:System.Data.Entity.Infrastructure.Interception.DbCommandTreeInterceptionContext.Result" /> while intercepting.
        /// </summary>
        /// <param name="interceptionContext">Contextual information associated with the call.</param>
        /// <exception cref="System.NotImplementedException"></exception>
        /// <remarks>
        /// Command trees are created for both queries and insert/update/delete commands. However, query
        /// command trees are cached by model which means that command tree creation only happens the
        /// first time a query is executed and this notification will only happen at that time
        /// </remarks>
        public void TreeCreated(DbCommandTreeInterceptionContext interceptionContext)
        {
            if (interceptionContext.OriginalResult.DataSpace == DataSpace.SSpace)
            {
                if (interceptionContext.Result is DbUpdateCommandTree updateCommand)
                {
                    var column = nameof(IEntity.Modified);
                    if (column != null)
                    {
                        // create set clause
                        var setClause = DbExpressionBuilder.SetClause(
                            DbExpressionBuilder.Property(
                                DbExpressionBuilder.Variable(updateCommand.Target.VariableType, updateCommand.Target.VariableName),
                                column
                            ),
                           EdmFunctions.CurrentUtcDateTime()
                        );

                        var newUpdateCommand = new DbUpdateCommandTree(
                            updateCommand.MetadataWorkspace,
                            updateCommand.DataSpace,
                            updateCommand.Target,
                            updateCommand.Predicate,
                            new ReadOnlyCollection<DbModificationClause>(
                                (updateCommand.SetClauses.Concat(new List<DbModificationClause>() { setClause })).ToList()
                            ),
                            null
                        );

                        interceptionContext.Result = newUpdateCommand;
                    }
                }
            }
        }
    }
}
```
Bug?! Any Suggestions?

regards
Kai

**Comment by jflord78** [comment] 2017-10-13 22:22
I'm encountering the same issue...

**Comment by ajcvickers** [comment] 2019-03-18 22:41
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment] 2019-06-26 18:37
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-06-26 18:37 UTC
Labels: blocked
