### ISSUE TITLE
migrate.exe RemotingExecption - occurs during long running migrations

### ISSUE THREAD

**Issue by dschuermans** [aspnet/EntityFramework6#258] opened 2017-04-28 15:17 UTC
> _TLDR:_
> 
> Generating a script using the arguments -Script and -SourceMigration 0 in a migration scenario where migrations have been merged together (some already applied to the database), the script fails to recognize the migrations in between.
> 
> Using migrate.exe causes a timeout exception in windows remoting, probably due to the logger being GC'ed because a migration takes too long.

Wall of text / situational sketch:

Up untill now, I have been using the generated script to perform my database updates in our automated release system (VSTS).
This script can be obtained by running the following command:
`Update-Database -Script -SourceMigration 0`

When looking at the script, it will add checks to see if a migration is already applied or not, making it an ideal script when used in a automated release environment because it can basically be executed against any version a database.

A small example would be:

timestamp_Migration_A
timestamp_Migration_B
timestamp_Migration_C

Let's assume that A has already been applied to the database, so the script would have timestamp_Migration_A as it's latest migration, and it would then check if it has to apply B and C by using 
`IF @current_migration < timestamp_Migration_B THEN`
`IF @current_migration < timestamp_Migration_C THEN`

This works well when your migration are straight forward and ours have been up until recently.
We had the situation where we'd have a develop branch and we started a new develop branch off of that (lets call it develop2) which was going to contain reworks of existing stuff in already in develop, including database tables and moving data around etc etc.
So in order to keep it simple, working on a separate branch would allow us to do any changes on develop but we just had to make sure that we'd always merge those changes into develop2 as well.

After reading [this article](https://msdn.microsoft.com/en-us/library/dn481501(v=vs.113).aspx) a few times and playing around in a dummy solution mimicking our scenario I was confident that it would work.

So whenver we made db changes on develop, we'd merge them to develop2 as well and create a blanco migration that fixes the metadata.

Example:

develop has A, B, C. At this point we created develop2
After that we added D to develop2 and E to develop

So now we have
develop => A, B, C, E
develop2 => A, B, C, D

After merge it and fixing it with a blanco migration it becomes:

develop => A, B, C, E
develop2 => A, B, C, D, E, F
with F being the blanco migration ofcourse.

So eventually we were done with develop2 and merged it back to develop.
This however means that develop has E as latest migration, so it wouldn't detect the D migration when doing it through the script.

I then noticed that migrate.exe does properly detect that it hadn't applied that migration yet, however one of the migrations is long running data migration and migrate fails with the following error:

> 2017-04-28T14:41:15.9156545Z System.Runtime.Remoting.RemotingException: Object '/698346e2_b30a_4c97_9793_a95e2ff5bee5/fylnvmkw+b03mldupipu8zng_3.rem' has been disconnected or does not exist at the server.
2017-04-28T14:41:15.9156545Z    at System.Data.Entity.Migrations.Design.ToolingFacade.ToolLogger.Verbose(String sql)
2017-04-28T14:41:15.9156545Z    at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.ExecuteSql(MigrationStatement migrationStatement, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
2017-04-28T14:41:15.9156545Z    at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
2017-04-28T14:41:15.9156545Z    at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinTransaction(IEnumerable`1 migrationStatements, DbTransaction transaction, DbInterceptionContext interceptionContext)
2017-04-28T14:41:15.9156545Z    at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinNewTransaction(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
2017-04-28T14:41:15.9156545Z    at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
2017-04-28T14:41:15.9156545Z    at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection)
2017-04-28T14:41:15.9156545Z    at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
2017-04-28T14:41:15.9156545Z    at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
2017-04-28T14:41:15.9156545Z    at System.Data.Entity.Migrations.DbMigrator.ExecuteStatements(IEnumerable`1 migrationStatements, DbTransaction existingTransaction)
2017-04-28T14:41:15.9156545Z    at System.Data.Entity.Migrations.DbMigrator.ExecuteOperations(String migrationId, VersionedModel targetModel, IEnumerable`1 operations, IEnumerable`1 systemOperations, Boolean downgrading, Boolean auto)
2017-04-28T14:41:15.9156545Z    at System.Data.Entity.Migrations.DbMigrator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
2017-04-28T14:41:15.9156545Z    at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
2017-04-28T14:41:15.9156545Z    at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
2017-04-28T14:41:15.9156545Z    at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
2017-04-28T14:41:15.9156545Z    at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
2017-04-28T14:41:15.9156545Z    at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
2017-04-28T14:41:15.9156545Z    at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
2017-04-28T14:41:15.9156545Z    at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
2017-04-28T14:41:15.9156545Z    at System.Data.Entity.Migrations.Console.Program.Run()
2017-04-28T14:41:15.9156545Z    at System.Data.Entity.Migrations.Console.Program.Main(String[] args)
2017-04-28T14:41:15.9156545Z ERROR: Object '/698346e2_b30a_4c97_9793_a95e2ff5bee5/fylnvmkw+b03mldupipu8zng_3.rem' has been disconnected or does not exist at the server.

I have tried creating a migrate.exe.config file with the following contents:

```
<system.runtime.remoting>
      <application>
         <lifetime 
          leaseTime = "30M" 
          sponsorshipTimeOut = "30M"
          renewOnCallTime = "15M" 
          LeaseManagePollTime = "8s"
         />
      </application>
   </system.runtime.remoting>
```
 but it still fails with the same exeception.
It's all caused by the logger used in migrate that is GC'ed due to inactivity (because of the long running migration)

The following SO posts seem to be related to my issue:

[http://stackoverflow.com/questions/6339469/object-has-been-disconnected-or-does-not-exist-at-the-server-exception](http://stackoverflow.com/questions/6339469/object-has-been-disconnected-or-does-not-exist-at-the-server-exception)
[http://stackoverflow.com/questions/18900204/errors-during-code-first-add-migration](http://stackoverflow.com/questions/18900204/errors-during-code-first-add-migration)

**Comment by dschuermans** [comment] 2017-04-28 15:38
Another related post on SO:

[http://stackoverflow.com/a/42609870/5903834](http://stackoverflow.com/a/42609870/5903834)

**Comment by ajcvickers** [comment] 2017-04-28 17:39
Note for triage: The RemotingException is tracked by #96

**Comment by ajcvickers** [comment] 2017-05-01 18:38
Closing this as a dupe of #96. @dschuermans Please let us know if we missed something that is not covered by #96.

**Closed by ajcvickers** 2017-05-01 18:38 UTC
