### ISSUE TITLE
Entity Framework 6 - projection issue with extern aliases

### ISSUE THREAD

**Issue by 1saeedsalehi** [aspnet/EntityFramework6#471] opened 2018-02-20 14:40 UTC
Hi

we are using entity framework 6 in our enterprise project
there is a NotSupportedException with complex types 
it  means "EntityFramework can't project two class with the same name using extern aliases" 

I have made a repository [here](https://github.com/1saeedsalehi/EfProjectionProblemSample) 
it briefly describes what the problem is

this issue is resolved in ef-core but what should we do in legacy version?

**Comment by ajcvickers** [comment] 2018-03-06 02:30
@1saeedsalehi From what I can tell you are hitting the issue described here: #362. To summarize:
* EF6.1.3 and above with Code First can map types with the same simple name but a different namespace as other referenced types so long as no two mapped types have the same simple name.
* The same behavior can be achieved when using Database First though manual addition of attributes to the EDMX as described in #362.
* No version of EF6 can map two types with the same simple name into the same model

With regard to types with the same namespace-qualified name, but in different assemblies, I expect that EF6 will also run into issues, but I don't remember specifically.

I'm going to close this as a duplicate of #362 since it seems to be that case.

**Closed by ajcvickers** 2018-03-06 02:30 UTC
