### ISSUE TITLE
Issue about add-migration

### ISSUE THREAD

**Issue by levonyang** [aspnet/EntityFramework6#347] opened 2017-08-28 16:33 UTC
I working on a asp.net mvc project and using entityframework as database access tool. and using code first mode.

Today, I encounter a problem:
1. I added a property to a domain entity, then run add-migration xxx, it generated a migration file, but the motheds up and down are all empty. then i run update-database, database din't change anything.

2. I tried to added another property to another entity. then run add-migration yyy, it generated a migration file, and the up and down methods have **only one** regarding this property changes.

3. the problem is i lost a property to update to database. how can i fix this problem.

-------------------
I think the best solution about migration is to compare domain entities and database scheme, then generate a migration file about the differences between two.

or add a parameter to force to compare with database scheme.

but entityframework  using history migration saved in the database table to compare in fact.  so sad....

first, i must add the missing property to the database, i don't want to delete all table to rebuild.

Hope somebody can help..
thanks in advance.

**Comment by ajcvickers** [comment] 2017-09-02 00:43
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment] 2017-09-11 18:53
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2017-09-11 18:53 UTC
