### ISSUE TITLE
Display Name with ResourceType  causes column tag doesn't work

### ISSUE THREAD

**Issue by DetectiveW** [aspnet/EntityFramework6#502] opened 2018-03-19 17:44 UTC
Hi to all,

I try to use Entity Framework to an application with a front end with multiple languages.

I have this sample code:

        [Key]
        [Display(Name = "MID", ResourceType = typeof(Translation.Common))]
        [Column("master_id")]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int? ID { get; set; }

Entity Framework try to use ID column name instead of master_id.

If I use Display Name with ResourceType causes column tag doesn't work.

PD: It seems to work well on ASP MVC but not in console app.

**Comment by ajcvickers** [comment] 2018-07-27 15:58
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2018-07-27 15:58 UTC
