### ISSUE TITLE
Entity Framework Spatial

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/EntityFramework6#1438] opened 2019-11-01 19:03 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/794844/entity-framework-spatial.html)._

---
Working with Spatial data in Entity and C# in general is a pain in the *. None of your fixes fix anything. The nuget package from 10 8 years ago doesn't do anything to fix the issue. Why do you guys make it so difficult to work with spatial data and having to jump through 100 hoops? Much less, none of these half *ed work arounds are documented any where at Microsoft.

---
#### Visual Studio Feedback System on 10/28/2019, 02:49 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 11/1/2019, 02:13 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2019-11-01 19:44
We would be happy to try to help with any specific question that you have.

**Comment by bricelam** [comment] 2019-11-04 22:54
Here are some of the hoops we had to jump through:

### *.csproj

``` xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net45</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.SqlServer.Types" Version="14.0.1016.290" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Include="$(NuGetPackageRoot)microsoft.sqlserver.types\14.0.1016.290\content\SqlServerTypes\Loader.cs">
      <Link>SqlServerTypes\Loader.cs</Link>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Content Include="$(NuGetPackageRoot)microsoft.sqlserver.types\14.0.1016.290\content\readme.htm">
      <Link>SqlServerTypes\readme.htm</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)microsoft.sqlserver.types\14.0.1016.290\nativeBinaries\x64\msvcr120.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>SqlServerTypes\x64\msvcr120.dll</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)microsoft.sqlserver.types\14.0.1016.290\nativeBinaries\x64\SqlServerSpatial140.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>SqlServerTypes\x64\SqlServerSpatial140.dll</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)microsoft.sqlserver.types\14.0.1016.290\nativeBinaries\x86\msvcr120.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>SqlServerTypes\x86\msvcr120.dll</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)microsoft.sqlserver.types\14.0.1016.290\nativeBinaries\x86\SqlServerSpatial140.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>SqlServerTypes\x86\SqlServerSpatial140.dll</Link>
    </Content>
  </ItemGroup>

</Project>

```

### Program.cs

``` csharp
SqlServerTypes.Utilities.LoadNativeAssemblies(
    Path.GetDirectoryName(typeof(Program).Assembly.Location));
```

### App.config

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.SqlServer.Types" publicKeyToken="89845dcd8080cc91" culture="neutral" />
        <bindingRedirect oldVersion="10.0.0.0-14.0.0.0" newVersion="14.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by ajcvickers** [comment] 2019-11-11 17:48
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-11-11 17:48 UTC
